### ISSUE TITLE
Is there any way that I can set value from tagModel used in ngx-chips in angular?

### ISSUE THREAD

**Issue by krunalm94** [Gbuomprisco/ngx-chips#1004]
HTML Code: 
` <tag-input
class="martop20 tag-adder width100 heightauto"
[onAdding]="onAdding"
(onAdd)="addInternalDomain($event)"
type="text"`

TS code: 
```
addInternalDomain(tagText: TagModel) {
 console.log(tagText.value)
}

```

Getting error : Property 'value' does not exist on type 'TagModel'. Property 'value' does not exist on type 'string'.

**Comment by Gbuomprisco** [comment]
Please complete the template. If possible, add a reproduction
