### ISSUE TITLE
ngx-chips not working with angular 12

### ISSUE THREAD

**Issue by rajkumarg736** [Gbuomprisco/ngx-chips#1011]
**Current behavior**
If do a npm install with angular 12 throws exception

$ npm install ngx-chips --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.0.1
npm ERR! Found: @angular/core@12.2.15
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^12.2.12" from the root project
npm ERR!   peer @angular/core@">=10.1.5" from ngx-chips@3.0.0
npm ERR!   node_modules/ngx-chips
npm ERR!     ngx-chips@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"13.1.1" from @angular/animations@13.1.1
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@">=10.1.5" from ngx-chips@3.0.0
npm ERR!   node_modules/ngx-chips
npm ERR!     ngx-chips@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Expected behavior**
I should be able to add ngx-chips with angular 12 version

**Minimal reproduction of the problem with instructions (if applicable)**
1. Create an app with angular 12
2. Do **npm install ngx-chips --save** you able to see the issue

**What do you use to build your app?. Please specify the version**
Webpack

**Angular version:** 
12.2.12

**ngx-chips version:**
3.0.0

**Browser:**
all

**Comment by Gbuomprisco** [comment]
Use anything below v3.0 or upgrade to Angular 13

**Comment by rajkumarg736** [comment]
Thanks for the recommendation. I used previous version 2.2.2, its working fine with angular 12.
