### ISSUE TITLE
Error Compiler ngx-chips 3 and angular 13

### ISSUE THREAD

**Issue by elvispdosreis** [Gbuomprisco/ngx-chips#1012]
I'm having trouble using ngx-chips on version 3 on angular 13, version 2 compiles without problems

ERROR in ./node_modules/ngx-chips/fesm2015/ngx-chips.mjs 2548:24-32

export 'filter' (imported as 'filter$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

**Angular version:** 
13.1.1

**ngx-chips version:**
3.0.0

**Comment by Gbuomprisco** [comment]
You'd have to update your rxjs version to v7

**Comment by elvispdosreis** [comment]
resolved
