### ISSUE TITLE
Wrong imports are used for rxjs operators

### ISSUE THREAD

**Issue by 11mb** [Gbuomprisco/ngx-chips#1029]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
When using ngx-chips 3.0.0 in my angular 13 project, I got errors about wrong imports:
Error: 39mexport 'first' (imported as 'first$1') was not found in 'rxjs'

**Expected behavior**
I Expect no errors when running ng serve.

**Minimal reproduction of the problem with instructions (if applicable)**
npm install version 3.0, use ngx-chips and try to ng serve your project

**What do you use to build your app?. Please specify the version**
Angular-CLI

**Angular version:** 

**ngx-chips version:**
Angular 13.3.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A

**Comment by Gbuomprisco** [comment]
Have you tried it upgrading rxjs? The imports from rxjs/operators will be deprecated eventually

**Comment by 11mb** [comment]
I have tried now, and you're right. Rxjs versions from 7.2 it is possible and advised to use the 'rxjs' import. Thx for letting me know!

**Comment by Gbuomprisco** [comment]
Glad it worked :)
