### ISSUE TITLE
 ./node_modules/ngx-chips/fesm2015/ngx-chips.mjs:2540:24-32 - Error: export 'filter' (imported as 'filter$1') - Error

### ISSUE THREAD

**Issue by dineshmaths1** [Gbuomprisco/ngx-chips#1036]
Hi 

Am using ionic angular

"ngx-chips": "^3.0.0",
    "rxjs": "^7.0.0",
   "@angular/common": "^14.0.0",

Am getting this error
./node_modules/ngx-chips/fesm2015/ngx-chips.mjs:2540:24-32 - Error: export 'filter' (imported as 'filter$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, NEVER, NotFoundError, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, SequenceError, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, animationFrames, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, connectable, defer, empty, firstValueFrom, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, lastValueFrom, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
[ng]
[ng] ./node_modules/ngx-chips/fesm2015/ngx-chips.mjs:2543:53-56 - Error: export 'map' (imported as 'map') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, NEVER, NotFoundError, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, SequenceError, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, animationFrames, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, connectable, defer, empty, firstValueFrom, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, lastValueFrom, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
[ng]
[ng] ./node_modules/ngx-chips/fesm2015/ngx-chips.mjs:2586:50-57 - Error: export 'first' (imported as 'first$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, NEVER, NotFoundError, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, SequenceError, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction,

**Comment by Gbuomprisco** [comment]
Update rxjs, a newer version is required
