### ISSUE TITLE
Semantic release proposal

### ISSUE THREAD

**Issue by AndriiDidkivsky** [Gbuomprisco/ngx-chips#121]
Hi.
Would be a pretty cool if you'll use [semantic-release](https://github.com/semantic-release/semantic-release) or something like that.

I have try to update component via npm and got few breaking changes.
I don't know which version were fixed or broke some features and spent so much time looking for some information in your commits. 

Are you planning add a changelog in the near future?

**Comment by Gbuomprisco** [comment]
Hi @AndriiDidkivsky,

Yeah, you're absolutely right. I will definitely start considering the releases more seriously. There are more breaking changes on the way :| (for the best)
