### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AndriiDidkivsky** [Gbuomprisco/ngx-chips#123]
Hi, I found bug that lead to memory leak.

So, I just use tag-input in popup. Every time when I open popup - new [ng2-dropdown] (http://prntscr.com/doskm0) component appear in the body,

I think you should remove dropdown on ng2-tag-input destroy hook.

Version: 0.4.4

**Comment by Gbuomprisco** [comment]
Hi @AndriiDidkivsky,

I believe this is handled here https://github.com/Gbuomprisco/ng2-material-dropdown/blob/master/src/modules/components/menu/ng2-dropdown-menu.ts#L217?

**Comment by AndriiDidkivsky** [comment]
@Gbuomprisco as I understand, [it'll](https://github.com/Gbuomprisco/ng2-material-dropdown/blob/master/src/modules/components/menu/ng2-dropdown-menu.ts#L217) remove dropdown element from DOM only when dropdown component destroy hook fired.
But we should remove related dropdown when some tag-input destroyed.

Something like this. 
```
class Ng2TagInputComponent {
    ...
    ngOnDestroy () {
        this.dropdown.destroy();
    }
}
```

Do you understand what I mean ?

**Comment by Gbuomprisco** [comment]
Yeah, makes sense :)
