### ISSUE TITLE
focusFirstElement does not work

### ISSUE THREAD

**Issue by tonysparks** [Gbuomprisco/ngx-chips#148]
Hello,

The `tag-input-dropdown` `focusFirstElement` doesn't appear to work.  When the dropdown appears, the first element is not `selected`, which requires the user to press the down arrow key.

![image](https://cloud.githubusercontent.com/assets/1552968/21810599/14dcbdd4-d712-11e6-8745-ecd5b80dcd0f.png)

Here is an example [application](http://www.webpackbin.com/Eyx1X1CSG).

Example:
```html
<tag-input [ngModel]="[]"
                       [placeholder]="'Enter a new repo'"
                       [secondaryPlaceholder]="'Search in Github'"
                       [onlyFromAutocomplete]="true">
                <tag-input-dropdown [autocompleteObservable]="requestAutocompleteItems"
                                     [focusFirstElement]="true">
                    <template let-item="item" let-index="index">
                        {{ item.display }}
                    </template>
                </tag-input-dropdown>
</tag-input>
```

Thank you,

Tony

**Comment by Gbuomprisco** [comment]
Must be a regression in `ng2-material-dropdown` :| will fix there and upgrade here

**Comment by rosslavery** [comment]
I can verify this issue is occurring for me as well.

**Comment by Gbuomprisco** [comment]
Yep it is definitely an issue: the focus function is called before the items actually are parsed by the template (although existing in the model). I will have to fix it in the ng2-material-dropdown

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/185

**Comment by Gbuomprisco** [comment]
Will be fixed by https://github.com/Gbuomprisco/ng2-tag-input/pull/187

**Comment by tonysparks** [comment]
Thank you @Gbuomprisco!

It seems to be working correctly most of the time.  I think I found a slight corner case when this feature is coupled with `matchingFn`:

```typescript
    // ignore any leading/trailing whitespace
    public customMatchingFn (value: string, target: any) : boolean {
        if(target.value != null) {
            if(target.value.toLowerCase().includes(value.trim().toLowerCase())) {
                return true;
            }
        }
        return false;
    }
```

Steps:

1) Tagify an entry
2) enter in a space
3) start typing
4) notice the first element is not highlighted, however if you press enter, the first element is tagified correctly.

![image](https://cloud.githubusercontent.com/assets/1552968/22788141/559bde8c-eea4-11e6-821f-fce35fba0c6a.png)

**Comment by paninee** [comment]
@Gbuomprisco

this is issue is still happening.

**Comment by phare2013** [comment]
I am still having the that issue as well. Please, it would be nice to see this bug addressed. The search suggestion functionality is a powerful part of this component's usefulness.

**Comment by bartholomej** [comment]
@Gbuomprisco yes, same issue.
`Angular 7.2.15` + `ngx-chips 1.9.8` or `2.0.0-beta.0`
Here is what we know about this issue. Maybe this will help. https://github.com/Gbuomprisco/ngx-chips/issues/815#issuecomment-487902951

**Comment by zhuweid** [comment]
any work-around or fix?
