### ISSUE TITLE
On Android/iOS tags can't be deleted

### ISSUE THREAD

**Issue by saschwarz** [Gbuomprisco/ngx-chips#263]
When I visit the demo page in Safari or Chrome on my iPad or iPhone tags aren't deleted when tapping on the "x" in the tag or when the backspace key on the virtual keyboard is pressed. When the backspace key is pressed the tag is selected/highlighted and the keyboard hides without deleting. The same thing happens in Chrome on my Android tablet.

Clicking on the "x" with a mouse on my desktop in Safari or Chrome or using the delete/backspace key on my desktop does delete tags.

**Comment by noomz** [comment]
My android Chrome `$event.keyCode` is always 229, and `$event.key` is not supported (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key). Should we update the code since `keyCode` is deprecated due to https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by noomz** [comment]
I'm working on this, please wait #266

**Comment by avikt** [comment]
When will this be fixed?

**Comment by noomz** [comment]
I can't promise, may be next week. I am now on deadline of my daily works 😅

**Comment by quanvhframgia** [comment]
@noomz @Gbuomprisco Has this bug fixed yet? I see [#266](https://github.com/Gbuomprisco/ng2-tag-input/pull/266) has not been merged. Thanks you!

**Comment by saschwarz** [comment]
In testing this with Ionic 3.4.0/Angular 4 deleting by tapping on the "X" it seems to work on iOS and Angular all the time. On an older/slower iPad there is a timing issue where the tag will select but not delete.

**Comment by saschwarz** [comment]
On Android everything is working fine. FWIW on iOS selecting from the autocomplete dropdown doesn't work. It could be interacting with the focus or the hide/show of the mobile keyboard is moving divs around on the tap(?).
