### ISSUE TITLE
EXCEPTION: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by ui9** [Gbuomprisco/ngx-chips#320]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Issue-1:
As soon as I click on the form, I'm getting the error Cannot read property 'trim' of null in console.
Attaching the pic below which only relates to this issue. I'm not sure why I'm causing this issue, can you please suggest me with an example?
I tried setting the trimTags to false, but its not working and I'm not sure it's a right way of doing it.

issue-2:
This issue is related to auto dropdown is not opening on clicking inside the form. Though I used [showDropdownIfEmpty]="true"
Please suggest me!

![trim error](https://cloud.githubusercontent.com/assets/26394947/24557669/7cbd5340-1606-11e7-82e5-51be33e124cc.JPG)

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**
jenkins

* **Angular version:** 2.4.5

* **ng2-tag-input version:** 1.0.0

* **Browser:** IE 11

**Comment by Gbuomprisco** [comment]
Looks like the line involved is 
https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/dropdown/tag-input-dropdown.component.ts#L240

Not sure why that value would be null at all, must be an IE thing..:\

**Comment by ui9** [comment]
ok thanks

**Comment by ui9** [comment]
Hi @Gbuomprisco ,

Did you get a chance to fix this issue?

**Comment by Gbuomprisco** [comment]
no sorry not yet

**Comment by ui9** [comment]
I have a concern @Gbuomprisco , if you fix this under a new release, Do I need to upgrade my angular to 4? because we do not have a time to upgrade it to the latest.

**Comment by Gbuomprisco** [comment]
No worries, I can release under a different tag branching from 1.0.0

**Comment by ui9** [comment]
Just FYI, can you also fix the issues for ticket number #319,  under the 1.0.0?

**Comment by ui9** [comment]
Hi @Gbuomprisco , can please update me the status on above fixes? Thanks in advance

**Comment by ui9** [comment]
Hi @Gbuomprisco , Issue 2 from my comment is working fine.
But I have issue where dropdown should close as soon as I select the items from the dropdown. Can You please suggest me!

**Comment by Gbuomprisco** [comment]
@ui9,

so if you select an item the dropdown won't close automatically?

**Comment by omprakash9** [comment]
Yes, it is not closing

**Comment by ui9** [comment]
Yes @Gbuomprisco,
 Do we have to use any other event for closing?

**Comment by Gbuomprisco** [comment]
I'm really not sure why it won't close really
