### ISSUE TITLE
UI Behavior

### ISSUE THREAD

**Issue by temelj** [Gbuomprisco/ngx-chips#357]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[?] feature request
[ ] support request/question
```

# **Current behavior**
### When selecting a new tag:
1. Focus on the tag-input
2. tag-input-dropdown shows the options
3. Select an option
**4. tag-input-dropdown hides**
One must click out of the tag-input and re-focus to get the 
 
### When deleting a tag:
1. Delete a tag (by pressing the X)
2. tag-input-dropdown shows the options (**without the deleted item**)

# **Expected # behavior**
### When selecting a new tag:
1. Expected behavior would be for the tag-input-dropdown to remain open (**without the added item**)
### When deleting a tag:
1. Expected behavior would be for the tag-input-dropdown **with the deleted item**.

# Version Information

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
Webpack 2.2.0

**Angular version:** 
4.0.1

**ng2-tag-input version:**
1.0.5

**Comment by Gbuomprisco** [comment]
Sorry, none of these are possible at the moment, but I may think about additional options.

**Comment by fifafu** [comment]
This would be awesome! Not hiding the dropdown (or immediately showing it again) after adding a new tag would make it much easier to add multiple tags in sequence.

**Comment by itssuyog96** [comment]
I got the same feedback from multiple users. So Yeah, that would make it more usable and friendly.

**Comment by Gbuomprisco** [comment]
Hi everyone, 1.4.9 takes care of this I think
