### ISSUE TITLE
API repopulate autocomplete - show dropdown when the autocomplete is repopulated

### ISSUE THREAD

**Issue by hsuanweifu** [Gbuomprisco/ngx-chips#375]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request/question
```

**Current behavior**

Currently if you update the autocomlete list, it will still use the old list if there is a match and not show if there is no match. You will have to refocus on the input to show the updated dropdown.

Work Around:
call this function after list is updated.

```
    public blurThenFocus(target: string) {
        let targetElement = $(target);

        targetElement.blur();
        setTimeout(function () {
            targetElement.focus();
        }, 10);
    }
```

setTimeout is required in this case because using callback and chaining blur and focus does not work.

**Expected behavior**

Show updated dropdown when the autocomplete list is updated.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

The auto complete list has 1000+ (and potentially more in the future) entries if loaded all the entries. Therefore the API search is required and the result is used to populate the autocomplete dropdown.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli: 1.0.0

**Angular version:** 

angular: 4.0.2

**ng2-tag-input version:**

1.0.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by sangwin** [comment]
Parameter target is the ID of element?
