### ISSUE TITLE
Modal Autocomplete Offset Off with Materialize Framework

### ISSUE THREAD

**Issue by hsuanweifu** [Gbuomprisco/ngx-chips#385]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

The autocomplete drop down will move to the bottom right when on materialize modal.
The offset is the offset of the modal top/left of modal to body.
It also does not take into account of the bottom margin of the input field.

To align to the bottom you need to set top, left to 0 and top margin to negative bottom margin of the tag input.

**Expected behavior**

Autocomplete dropdown locate under input field.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

Having tag input on modal to allow crud operation.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular/cli: 1.0.0
windows 10
phpstorm
materialized

**Angular version:** 

4.0.2

**ng2-tag-input version:**

1.2.0

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
have you tried setting appendToBody=false already?

**Comment by hsuanweifu** [comment]
Yes.

Here is the code for the dropdown.

`
            <tag-input-dropdown [showDropdownIfEmpty]="true"
                                [identifyBy]="'id'"
                                [displayBy]="'name'"
                                [autocompleteItems]="productTypeList"
                                [appendToBody]="false">
            </tag-input-dropdown>
`

**Comment by Gbuomprisco** [comment]
The it's a bug of the dropdown (ng2-material-dropdown)

**Comment by hsuanweifu** [comment]
I think there is a miss communication here.

The autocomplete dropdown from tag input in on the modal which is intended, but the left and top is set to the modal's left and top.

Here is an image. As you see the autocomplete is no the bottom right of the modal dude it using the modal's left and top css.

![tag input autocomplete](https://cloud.githubusercontent.com/assets/9949366/25596728/879679d6-2e7f-11e7-8c9b-41b0736ce15a.png)

**Comment by Gbuomprisco** [comment]
No, I understood perfectly. I think appendToBody is the property causing that.

If you remove appendToBody, the dropdown should appear in the right position but display below the modal, right? In that case, you'd just need to overwrite the z-index

**Comment by hsuanweifu** [comment]
I've tried your suggested method.

It does solve this problem. However it creates other issues. Multiple autocomplete dropdowns can now be opened at the same time.
