### ISSUE TITLE
Adding new Tag with autocomplete 

### ISSUE THREAD

**Issue by magarbikram** [Gbuomprisco/ngx-chips#437]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
autocomplete using a remote endpoint
onlyFromAutocomplete='false', so that user can input new tag as well
when user inputs a new tag, 'tag new',

**onAdding** event will be called with new tag input that will be a string only
   => I am returning a Observable of Tag model, instead of tag input, which means it will have a tag model with display and value property properly set {value: 23, display:'tag new' }. Note: new tag will be created by calling api from service

```

onAddingSinger = (singer): Observable<any> => {
    if(typeof singer === 'string'){
        if (confirm(`Would you like to add new singer ${singer}`)) {
        debugger;
        return this.addNewSingerService.add(singer);
      } else {
        debugger;
        return Observable.of(undefined)
          .filter(() => false)
          .mapTo(singer);
      }
    }
    return Observable.of(undefined)
          .filter(() => false)
          .mapTo(singer);
}
```

but tag input adds a new tag {value: 'tag new', display: 'tag new'} instead of 
{value: 23, display:'tag new' }

**Source Code**

```
 private addItem(fromAutocomplete = false, item: TagModel = this.formValue): void {
 ....
 ....
      Observable
            .of(this.getItemDisplay(item))
            .map(display => this.setInputValue(display))
            .filter(display => this.inputForm.form.valid && !!display)
            .map((display: string) => this.createTag(fromAutocomplete ? item : display))
            .filter(validationFilter)
            .subscribe(appendItem, undefined, reset);
 }

public createTag(model: TagModel): TagModel {
        const trim = (val: TagModel, key: string): TagModel => {
            return typeof val === 'string' ? val.trim() : val[key];
        };

        return {
            ...typeof model !== 'string' ? model : {},
            [this.displayBy]: this.trimTags ? trim(model, this.displayBy) : model,
            [this.identifyBy]: this.trimTags ? trim(model, this.identifyBy) : model
        };
    }
```

is it necessary 
.map((display: string) => this.createTag(fromAutocomplete ? item : display))

I think, we can just pass an item to creatTag function which is handling a string/object case
![screen shot 2017-06-10 at 6 15 30 am](https://user-images.githubusercontent.com/493559/27003046-4935c0ae-4da4-11e7-984d-bcf7efbe4916.png)

**Expected behavior**
a new tag {value: 23, display:'tag new' } should be added

**Minimal reproduction of the problem with instructions (if applicable)**

html:
```
<tag-input [(ngModel)]="newSong.singers" theme='bootstrap' placeholder='Add more singer' secondaryPlaceholder='Add singer'
              [onAdding]='onAddingSinger' (onAdd)='singerAdded($event)' (onRemove)='singerRemoved($event)' [onlyFromAutocomplete]="false" identifyBy='artistRoleId' displayBy='artistName'>
              <tag-input-dropdown [autocompleteObservable]='requestAutocompleteItems' identifyBy='artistRoleId' displayBy='artistName'>
                <ng-template let-item="item" let-index="index" style="padding:5px;">
                  <img style="width:50px;height: 50px; padding:5px;" src="{{item.profilePicture?.imageUrl}}" alt="{{item.artistName}}">                  {{ item.artistName }}
                </ng-template>
              </tag-input-dropdown>
            </tag-input>
```

1. Add a new tag which is not from auto complete
2. Implement [onAdding] where new tag model will be created and returned as an observable

**What is the motivation / use case for changing the behavior? (if applicable)**
Add a new tag in server if it doesn't exist and assign it in another entity

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
MacOs, Studio Code, angular-cli, 

**Angular version:** 
4.0

**ng2-tag-input version:**
1.3.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by Gbuomprisco** [comment]
Hi @magarbikram,

if you are using identifyBy='artistRoleId' displayBy='artistName', how come are you changing it to value and display?

@eyalhakim do you have the same issue?

**Comment by magarbikram** [comment]
@Gbuomprisco , oh that was just an example, item is still { artistRoleId, artistname }, sorry for confusion.
The line I have changed is 
**.map((display: string) => this.createTag(fromAutocomplete ? item : display))**

to 

**.map((display: string) => this.createTag(item))**

and then it worked as expected,

**Comment by Gbuomprisco** [comment]
Ok, I see. and could you paste this.addNewSingerService.add?

**Comment by magarbikram** [comment]
here is the service:

```
add(singerName: string): Observable<ArtistRole> {
    let newSingerAPI = `${environment.API_ENDPOINT}/singers/new`;
    return this.http.post(newSingerAPI, { artistName: singerName })
                            .map(data => <ArtistRole>data.json());
  }

```

ArtistRole Class:
```
export class ArtistRole {
    artistRoleId:number;
    artistId:string;
    artistName:string;
    artistUrlFriendlyName:string;
    coverPhoto:Image;
    profilePicture:Image;
}
```

**Comment by Gbuomprisco** [comment]
That seems alright as well. I tried to reproduce with my Github example but unsuccessfully.....

**Comment by eyalhakim** [comment]
Hey @Gbuomprisco, any news about this one? I can help you reproduce the issue...

**Comment by Gbuomprisco** [comment]
Hi guys would you be able to check v1.3.6? thanks

**Comment by eyalhakim** [comment]
@Gbuomprisco works for me!

Thank you

**Comment by Gbuomprisco** [comment]
Great :)
