### ISSUE TITLE
separatorKeys and separatorKeyCodes do not work on Android device. 

### ISSUE THREAD

**Issue by ali85h** [Gbuomprisco/ngx-chips#446]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

I have added [separatorKeyCodes]="[32, 188]" to separate tags for (space) and (,). It works great in IOS and browsers, but does not work on Android. When pressing space or comma in android, it gets added as a tag. 

**Expected behavior**

If (space) or (,) characters are pressed in Android, a new tag should be created. 

**Angular version:** 

angular 2.4.8

**ng2-tag-input version:**

1.0.0 (had to use older version because I am still running ionic 2)

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Android 7.0

**Comment by Gbuomprisco** [comment]
Hi @ali85h,

Have you also tried with separatorKeys? The title says so but not the description of the ticket so I am wondering if you actually did

**Comment by msaiyaff** [comment]
Something related to this issue but not fully related to this since I am not trying it in android.
@Gbuomprisco I tried with `[separatorKeys]="[]"` which was not working. But, `[separatorKeyCodes]="[]"`  worked for me in chrome/browser.
Any idea on this or separatorKeys is not working anymore?

**Comment by Gbuomprisco** [comment]
Can you show me what values you were trying with?

**Comment by msaiyaff** [comment]
Sure @Gbuomprisco 
![image](https://user-images.githubusercontent.com/17147255/29770857-9beac990-8c0e-11e7-863a-33624780e489.png)
Here goes the code.

**Comment by Gbuomprisco** [comment]
From the doc:
```
separatorKeyCodes - [?number[]]

Array of keyboard keys with which is possible to define the key for separating terms. By default, only Enter is the defined key.

separatorKeys - [?string[]]

Array of input characters with which is possible to define the key for separating terms. Default is empty. Can use with separatorKeyCodes, either one method matched will trigger tag separation.
```

In your case, you have keyCodes, not keys.

**Comment by msaiyaff** [comment]
Oh! My bad.
Thanks for the kind reply. 👍

**Comment by orvelin** [comment]
@msaiyaff  how solved his problem?

**Comment by orvelin** [comment]
@msaiyaff  How did you solve your problem?

**Comment by msaiyaff** [comment]
@orvelin If you look at it, I've used the separatorKeys attribute that needs string input but, I've added the number input which is normally used to separatorKeyCodes.
This @Gbuomprisco 's [answer](https://github.com/Gbuomprisco/ngx-chips/issues/446#issuecomment-325327029) explains it well.

**Comment by needke** [comment]
`[separatorKeyCodes]="[32]"` is not adding a new tag when hitting space button on android for me.

**Comment by LFeh** [comment]
Some problem here, `separatorKeyCodes` doesn't work on Android devices.

**Comment by roroettg** [comment]
I am facing this problem as well. It works in browsers and iOS, but not on Android devices.

**Comment by orvelin** [comment]
@xKloc I solved using the event onTextChange, I declare an array with separate character when the text change find if the text contain any character of the array push the value in the form.

**Comment by jordanorc** [comment]
Same problem here. Any workaround to make it work on Android?

**Comment by BaneDC** [comment]
The problem is in android and how it sends key code. It is always 229. Here is a link that might help:
https://stackoverflow.com/questions/36753548/keycode-on-android-is-always-229
