### ISSUE TITLE
Autocomplete Position

### ISSUE THREAD

**Issue by hsuanweifu** [Gbuomprisco/ngx-chips#450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

Currently the autocomplete will block the input field if it is above the input field. Also the dropdown can exceed the bottom screen if the list is populated dynamically.

**Expected behavior**

Autocomplete dropdown not block the input field. Maybe set the dropdown to be on the top side if the input field is on the button side of the screen?

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Webpack
angular-cli 1.0.0
Windows 10
PHPStorm

**Angular version:** 

Angular 4.0.1

**ng2-tag-input version:**

1.3.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by sangwin** [comment]
Is there any update on this??

**Comment by hsuanweifu** [comment]
Custom CSS

This uses relative position.

```
tag-input {
  width: 100%;

  > div.ng2-tag-input {
    border-bottom: 1px solid #9e9e9e !important;
    margin-bottom: 0 !important;

    & :focus {
      border-bottom: 1px solid #ff4081 !important;
    }

    > div.ng2-tags-container {
      width: 100%;

      > tag-input-form {
        width: 98%;

        > form > input {
          padding-bottom: 0 !important;
          margin-bottom: 0 !important;
          border-bottom: 0 !important;
          box-shadow: 0 0 0 0 white !important;
        }
      }
    }
  }

  > tag-input-dropdown {
    width: 100%;

    > ng2-dropdown {
      width: 100%;

      > div.ng2-dropdown-container {
        width: 100%;

        > ng2-dropdown-menu {
          width: 100%;

          > div.ng2-dropdown-menu {
            position: relative !important;
            top: auto !important;
            left: auto !important;
            width: 100% !important;
            max-height: 200px !important;
          }
        }
      }
    }
  }
}

```

**Comment by BrsJsk** [comment]
Same issue here. If the input is near the bottom of the page, the autocomplete(dropdown) goes over the input, so the input is hidden and typing does not work. Could it be a problem with updatePosition? Is there any solution to this as the CSS above does not work properly.

**Comment by Gbuomprisco** [comment]
Check out the option [dynamicUpdate] in version 1.7.5
