### ISSUE TITLE
Can't select item from dropdown in Safari [iPad]

### ISSUE THREAD

**Issue by phamtienmanh** [Gbuomprisco/ngx-chips#452]
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question

Currently:
- I'm doing a filter by selecting tags: [(ngModel)]="filterTags" onlyFromAutocomplete = "true", it works good in chrome but in safari I can't select item from dropdown. 
- If I remove () from ngModel it wont be error but filter wont work.

Expected behavior:
- 

Minimal reproduction of the problem with instructions (if applicable)

What is the motivation / use case for changing the behavior? (if applicable)

What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version

Webpack
angular-cli 1.0.0
Windows 10
Webstorm
Angular version: Angular 4.0.3
ng2-tag-input version: 1.3.3

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, Safari

**Comment by Gbuomprisco** [comment]
Hi @phamtienmanh, noy sure what you mean by "I'm doing a filter by tags". Can you please paste some code?

**Comment by phamtienmanh** [comment]
@Gbuomprisco 
<tag-input class=""
                     placeholder="+ Tags"
                     secondaryPlaceholder="Filter by tags"
                     [(ngModel)]="filterTags"
                     [identifyBy]="'id'" [displayBy]="'name'"
                     theme='bootstrap'
                     [onlyFromAutocomplete]="true">
            <tag-input-dropdown [showDropdownIfEmpty]="true"
                                [autocompleteItems]="tagData"
                                [identifyBy]="'id'" [displayBy]="'name'">
            </tag-input-dropdown>
          </tag-input>

**Comment by Gbuomprisco** [comment]
is filterTags an array?

**Comment by phamtienmanh** [comment]
@Gbuomprisco yes

**Comment by Gbuomprisco** [comment]
Not sure I can reproduce on Safari...

**Comment by phamtienmanh** [comment]
why in document, it always [ngModel] come with [onlyFromAutocomplete]="true" but not [(ngModel)]

**Comment by phamtienmanh** [comment]
demo page work good in ipad but I'm not sure is that   [(ngModel)] or [ngModel]

**Comment by phamtienmanh** [comment]
oh, sorry, it work in MAC safari, but not in ipad safary

**Comment by phamtienmanh** [comment]
This is error when select item from dropdown in ipad
[Error] ERROR
TypeError: Object.values is not a function. (In 'Object.values(this.subscriptions)', 'Object.values' is undefined)

**Comment by phamtienmanh** [comment]
it will work if : [onlyFromAutocomplete]="false"

**Comment by Gbuomprisco** [comment]
[(ngModel)] is the correct one as  you may want to have two-way data binding
