### ISSUE TITLE
Not able to use ng2-tag-input in Modal Dialog

### ISSUE THREAD

**Issue by hiteshgupta9193** [Gbuomprisco/ngx-chips#453]
I am trying to use ng2-tag-input in Modal Dialog.
When I click on input field dropdown appears below dropdown.

Issue:-
Dropdown has z-index 100
whereas modal dialog has 1050

refer screenshot attached.

Note: I am using bootstrap 4

![screen shot 2017-06-18 at 11 42 37 pm](https://user-images.githubusercontent.com/10322073/27263079-a8a46b34-5480-11e7-8e40-21ed462088c6.png)

**Comment by Gbuomprisco** [comment]
Try using [appendToBody]="false" (see the doc)

**Comment by hiteshgupta9193** [comment]
Now it appears like this. Somewhat dislocated from its expected position.

![screen shot 2017-06-19 at 9 20 01 pm](https://user-images.githubusercontent.com/10322073/27293813-1e47e816-5535-11e7-905f-7f81b827c691.png)

**Comment by mrsan22** [comment]
Works fine with md-dialog component after adding [appendToBody]="false".

**Comment by vgogov** [comment]
@hiteshgupta9193 Can you try the following in your css:

`:host /deep/ ng2-dropdown-menu div {
  left: inherit !important;
  top: inherit !important;
}`

**Comment by eloyleonardo** [comment]
Other workaround that works without use` [appendToBody]` is decrease the z-index of the modal: 
`.cdk-overlay-container {
  z-index: 5 !important;
}
`

**Comment by irowbin** [comment]
I am also having this issues with bootstrap modal.  https://github.com/Gbuomprisco/ngx-chips/issues/355#issuecomment-345896432

**Comment by Gbuomprisco** [comment]
Check out the option [zIndex] in version 1.7.5
