### ISSUE TITLE
No Maintenance Intended - WIll fix bugs only - No new features

### ISSUE THREAD

**Issue by Gbuomprisco** [Gbuomprisco/ngx-chips#457]
TL;DR: I will try to fix bugs when I can, no new features will be added/considered by myself. PRs are very welcome.

Due to workload - I cannot actively maintain the project as I could in the past. I suggest to fork the project, I will add it to the readme to point users to the updated version (please comment in this ticket with the URLs).

I may (and hope to) go back working on this once I will be more available to work on open source code.

**Comment by saschwarz** [comment]
Thank you for creating this project and for all the work you put into supporting it. I really appreciate it!!

**Comment by iperevozchikov** [comment]
+1 Good job!
Currently I'm working on under virtualized infinity scroll support. If someone else want it, I may create pull request.

**Comment by Gbuomprisco** [comment]
Thanks both!I really appreciate it :)

**Comment by osahner** [comment]
@iperevozchikov 
oh yes please!
