### ISSUE TITLE
Tabindex is being set to 0 after disabling and enabling again

### ISSUE THREAD

**Issue by jakubstrama** [Gbuomprisco/ngx-chips#459]
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

A set tabindex is being evaluated to 0 if disabled and enabled again.
 
**Expected behavior**

A  tabindex should be set to to the value from attribute after enabling.

**Minimal reproduction of the problem with instructions (if applicable)**

```        
       <div>
            <h3>Partially editable input with two items as objects</h3>
            <tag-input [(ngModel)]="itemsAsObjects"
                       [identifyBy]="'id'"
                       tabindex="1"
                       [disabled]="disable"
                       [displayBy]="'name'"></tag-input>
              <button (click)="disable=!disable" >Disable ME {{ disable }}</button>
        </div>
```

_tag-input-form.template.html_ line:8 should be changed from
`tabindex="{{ disabled ? -1 : 0 }}"`
to
`tabindex="{{ disabled ? -1 : tabindex ? tabindex : 0 }}"`

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Windows, Intellij, Webpack,

**Angular version:** 

4.0.1

**ng2-tag-input version:**

1.3.5

**Browser:** 
Chrome

**Comment by Gbuomprisco** [comment]
Will be fixed in https://github.com/Gbuomprisco/ng2-tag-input/pull/461/files

**Comment by Gbuomprisco** [comment]
Hi @jakubstrama,

thanks for this. Would you be able to check v1.3.6? I added your suggested fix

 thanks
