### ISSUE TITLE
ng2-tag-input trimTag not working 

### ISSUE THREAD

**Issue by Shrishti007** [Gbuomprisco/ngx-chips#460]
Hi,

I am using ng2-tag-input in my application and i found that the tag input is accepting white-space for the first time and after that it is working fine.

As per the documentation ng2-tag-input has a property of trimTag which is by default true which restrict user to create a blank tag but as i observed it is accepting space for the first time.

Please look into this.

version i am using  :
 "ng2-tag-input": 1.3.5,
Browser : Google chrome.

Thanks in advance.

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/461

**Comment by Gbuomprisco** [comment]
Hi @Shrishti007,

would you be able to check v1.3.6? thanks
