### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by Gbuomprisco** [Gbuomprisco/ngx-chips#468]
I'm renaming the project and the npm package, as we now "ng2" is not an appropriate prefix anymore. My thoughts were to initially rename it to ngx-tag-input, but a user forked this project and used that name already ( :disappointed: ). An alternative is "ngx-tags-input" or "ngx-chips".

**Comment by kkotak** [comment]
My vote is for 'ngx-chips'.

**Comment by Gbuomprisco** [comment]
Think I like that too!
