### ISSUE TITLE
onTagEdited fires while editing and not when editing is done.

### ISSUE THREAD

**Issue by Lakston** [Gbuomprisco/ngx-chips#469]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**
`onTagEdited` fires when there is a keypress event so the event will fire multiple times while typing during an edit.

**Expected behavior**
I would expect `onTagEdited` to fire only once when pressing enter when the edit is done, or on blur when, again, the editing of the tag is done so I can make an call to my API and update the tag in my DB.

**Minimal reproduction of the problem with instructions (if applicable)**
Simply putting a console log in the `onTagEdited` method that is called will show that the event is fired multiple times (every keystroke with a debounce from my understanding).

**What is the motivation / use case for changing the behavior? (if applicable)**
Beeing able to make an API call when the user has finished editing to update the tag in the database.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
Angular CLI 1.0.4

**Angular version:** 
4.1.3

**ng2-tag-input version:**
1.3.9

**Browser:** Chrome Canary

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/471#issuecomment-312894804 will be fixing this issue

**Comment by Gbuomprisco** [comment]
Hi @Lakston,

try using v 1.4.1 I just released
