### ISSUE TITLE
Autocomplete Items not showing recent data in dropdown

### ISSUE THREAD

**Issue by cibi246** [Gbuomprisco/ngx-chips#470]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
In our component, we have set API call to backend to fetch autocomplete suggestions on type of each letter in tag input. We expect ng2-tag-input to wait and display the data after the backend call gets completed. But the component displays previously stored data (even before call gets completed)which is not expected.
Say for example, when we type "TE" a call will be triggered to backend and it might take sometime to receive response. But after receiving response, no data are displayed as autocomplete dropdown suggestions. When we further type "TES", another call will be triggered to backend. In the meanwhile, component displays autocomplete data based on the result received for "TE" and it doesn't wait and show the results received for "TES".

**Expected behavior**
We expect the component to show autocomplete after we receive response from backend (dynamically)

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
Webpack

**Angular version:** 

**ng2-tag-input version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, do you have some code you can show?

**Comment by cibi246** [comment]
Hi Gbuomprisco,

Sample demo code is given below. Please help.

HTML : 
====
 <tag-input [ngModel]="tagValues" [clearOnBlur]="true"
           (onAdd)='addElement($event)' (onRemove)='removeValue($event)' [onlyFromAutocomplete]="true" (onTextChange)='onTextChange($event)'>
    <tag-input-dropdown [autocompleteItems]="tagOptions" >
    </tag-input-dropdown>
</tag-input>


TYPESCRIPT : 
=========
  onTextChange(event) {
    this.tagOptions = [];
    if(event && event.length > 1){
      this.suggestionFetch(event.toUpperCase()).subscribe(
        data => {
               this.tagOptions = data.suggestions;
        }
      );
    }
  }

**Comment by Gbuomprisco** [comment]
Hi, I would suggest trying out the autocompleteObservable option. It is suitable to your use case. Look at the demo in this repository and the doc to see how to implement it

**Comment by bbholtest** [comment]
Hi Gbuomprisco,

Thanks for your suggestion. The same scenario we faced and we used autocompleteObservable and it worked fine as expected. But We are facing one more problem here.

For ex, when we type "TE", a call will be triggered to the backend and when user types "TES" another call will be triggered. Now the first call for "TE" needs to be canceled since that is unnecessary also if the results come after "TES", then it will show data in screen only for "TE" and not for "TES".

So, please suggest us how to cancel previous service call, if another service call is triggered.

**Comment by Gbuomprisco** [comment]
Hi @bbholtest,

I think you'd need to play with the rxjs operators to cancel subsequent calls. Try debounce/switch operators for instance.

**Comment by HDaghash** [comment]
@Gbuomprisco thanks for the awesome work,

small question why this guy **[autocompleteItems]** does not have two-way data binding, it seems it only works on initial time only, 
in my case, I'm populating the data on the client side I don't have a response of type <Response>

Thanks in advance .

**Comment by Gbuomprisco** [comment]
Because it's not a model, just a property to pass down a list of options
