### ISSUE TITLE
Dropdown not closing when tag is created by enter

### ISSUE THREAD

**Issue by chrsadk** [Gbuomprisco/ngx-chips#478]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**
I'm using the latest published ngx-chips. I insert the html and js exactly as shown in the demo folder in the autocomplete example:

```
<div>
<h3>Tags within an autocomplete component</h3>
     <tag-input [ngModel]="['@item']"
                    [addOnBlur]="true"
                    [clearOnBlur]="true">
           <tag-input-dropdown [autocompleteItems]="autocompleteItems">
            </tag-input-dropdown>
    </tag-input>
</div>
```

```
autocompleteItems = ['Item1', 'item2', 'item3'];
```

When i enter a string in the tag-input control, the dropdown opens as expected. If i then hit enter to create the tag, or if i finish typing and hit enter (without selecting anything in the dropdown), then the dropdown stays open.

Note: This does not happen on the demo page (http://www.buompris.co/ng2-tag-input/). So my bug report is more a question as to if something has changed that would result in the behaviour of the dropdown only closing if something is selected by mouse. The other possibility is of course that something is wrong with my setup.

**Expected behavior**
The dropdown is expected to close when a tag is created.

**Minimal reproduction of the problem with instructions (if applicable)**
See code provided above.

**What is the motivation / use case for changing the behavior? (if applicable)**
n/a

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli  1.1.3

**Angular version:** 
angular 4

**ng2-tag-input version:**
Most recent published version of ngx-chips

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

Thank you for an otherwise excellent component!

Best regards,
Christian

**Comment by Gbuomprisco** [comment]
Hi @chrsadk,

the bug you encountered is a regression, so nothing is wrong with your code. However, the bug will be fixed as soon as I merge https://github.com/Gbuomprisco/ngx-chips/pull/479/files

**Comment by chrsadk** [comment]
Excellent. Thank you.

**Comment by Gbuomprisco** [comment]
Hi @chrsadk can you try the newest version?

**Comment by chrsadk** [comment]
@Gbuomprisco It works in the newest version, thank you again :)

The only exception is if i already have a tag called "Item1", and them write "Item1" again. Then the dropdown opens. If i then hit enter, it clears the text (as expected because the tag is already added before), but in this case it doesn't close the dropdown. It's a small thing though...

**Comment by anafreitas** [comment]
Hi, I'm having a similar issue. In my situation, when I start to type a tag the dropdown shows, but then when I erase the word, the dropdown keeps showing until I type add another tag.

**Comment by Gbuomprisco** [comment]
Hi @anafreitas, just a question: do you select the whole text and remove it or do you remove it letter by letter?

**Comment by anafreitas** [comment]
@Gbuomprisco letter by letter

**Comment by anafreitas** [comment]
In my case I erase the word without clicking the dropdown

**Comment by Gbuomprisco** [comment]
Works on the demo so it must be a regression.. I'll check it out

**Comment by Gbuomprisco** [comment]
Hi @anafreitas, try version 1.4.5, it should fix your issue

**Comment by anafreitas** [comment]
@Gbuomprisco It worked, thanks!
