### ISSUE TITLE
AOT build fails

### ISSUE THREAD

**Issue by Malanin** [Gbuomprisco/ngx-chips#482]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

AOT build fails.

> ERROR in Unexpected value 'TagInputModule in ...node_modules/ngx-chips/dist/modules/tag-input.module.d.ts' imported by the module 'AppModule in .../src/app/app.module.ts'. Please add a @NgModule annotation.

**Expected behavior**

AOT build runs without errors

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli

**Angular version:** 

> angular/cli: 1.2.0 node: 6.11.0
> os: win32 x64
> angular/animations: 4.2.5
> angular/common: 4.2.5
> angular/compiler: 4.2.5
> angular/compiler-cli: 4.2.5
> angular/core: 4.2.5
> angular/forms: 4.2.5
> angular/http: 4.2.5
> angular/material: 2.0.0-beta.7
> angular/platform-browser: 4.2.5
> angular/platform-browser-dynamic: 4.2.5
> angular/platform-server: 4.2.5
> angular/router: 4.2.5
> angular/cli: 1.2.0

**ng2-tag-input version:**

   ngx-chips@1.4.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Hi, try upgrading

**Comment by Malanin** [comment]
Thanks, update solved the problem.

**Comment by msaiyaff** [comment]
So the latest version is 1.4.5-beta that you're using @Malanin ?
Cuz I've had the error in version 1.4.2 saying `ERROR in TagInputModule is not an NgModule`
