### ISSUE TITLE
ERROR in TagInputModule is not an NgModule

### ISSUE THREAD

**Issue by Shrishti007** [Gbuomprisco/ngx-chips#487]
Hi,
I am importing  tagInput module in my module.
import { TagInputModule } from 'ng2-tag-input';
i have imported it in my ngModule as well but it is giving me error

version : "ng2-tag-input": "^1.4.1",
 "@angular/core": "^4.1.0",

i am getting Error : ERROR in TagInputModule is not an NgModule on npm start.

Please let me know if i am missing something.

Resolve it asap.

thanks,

**Comment by Gbuomprisco** [comment]
use ngx-chips, that module is deprecated
