### ISSUE TITLE
onTagEdited doesn't pass existing vlaue

### ISSUE THREAD

**Issue by eyalhakim** [Gbuomprisco/ngx-chips#488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

When editing a tag that has a certain value and display, the old value in not being passed to the onTagEdited function, making it impossible to know which tag was edited.

**Expected behavior**

Upon editing a tag, we should pass the old value as well as the new value, or alternatively, pass the old value and the new display.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

**Angular version:** 

**ng2-tag-input version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by eyalhakim** [comment]
@Gbuomprisco What are you thoughts on this?

**Comment by Gbuomprisco** [comment]
This was voluntarily changed as i thought it was a bug, but maybe the best thing will be passing (oldValue, newValue)

**Comment by eyalhakim** [comment]
Yes, i think it's the best solution.

**Comment by NeilMulholland** [comment]
Really love the control but had to drop it out and use a custom solution because of this bug! Would love to add the control back in, as it's prettier and simpler than most. Is there an ETA for a fix for this?

**Comment by Gbuomprisco** [comment]
Hi, I am not sure when I can get back on this. If you want to submit a PR, the change should not be difficult :)

**Comment by Gbuomprisco** [comment]
Also, if you play a little bit with rx subjects it shouldn't be too hard to get previous and current value. Just subscribe to the output emitted and use pairwise :)
