### ISSUE TITLE
Animation error thrown

### ISSUE THREAD

**Issue by eyalhakim** [Gbuomprisco/ngx-chips#489]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

An error message is thrown when tag-input is loaded:

`Error: Unable to process animations due to the following failed trigger transitions
@animation has failed due to:
- Please provide a value for the animation param enter
- The provided timing value "" is invalid.

    at TransitionAnimationEngine._flushAnimations (browser.es5.js:3774)
    at TransitionAnimationEngine.flush (browser.es5.js:3635)
    at InjectableAnimationEngine.AnimationEngine.flush (browser.es5.js:4530)
    at animations.es5.js:293
    at ZoneDelegate.webpackJsonp.711.ZoneDelegate.invoke (zone.js:391)
    at Zone.webpackJsonp.711.Zone.run (zone.js:141)
    at NgZone.runOutsideAngular (core.es5.js:3844)
    at AnimationRendererFactory.end (animations.es5.js:291)
    at DebugRendererFactory2.end (core.es5.js:13503)
    at ViewRef_.detectChanges (core.es5.js:10169)`

**Expected behavior**

No error should be thrown

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

**Angular version:** 

**ng2-tag-input version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, you need to update Angular to >= 4.2.0

**Comment by eyalhakim** [comment]
@Gbuomprisco Already have, i'm running 4.2.6.

**Comment by Gbuomprisco** [comment]
Can you check the animations module has the same version?

**Comment by eyalhakim** [comment]
checked, it does.

**Comment by Gbuomprisco** [comment]
strange I can't reproduce :(

**Comment by eyalhakim** [comment]
@Gbuomprisco I have created an environment which replicates my settings and was able to reproduce:

http://plnkr.co/edit/Tlp9V5fI2e7bV1TEBUGx?p=preview

hope this helps you in finding and squashing that bug 👍

**Comment by Gbuomprisco** [comment]
my guess is i was using a previous angular version, not sure..i'll fix it around the weekend!

**Comment by eyalhakim** [comment]
cool, thanks!
