### ISSUE TITLE
Clean up NPM ngx-tag-input linking probably to old repo

### ISSUE THREAD

**Issue by nolazybits** [Gbuomprisco/ngx-chips#491]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

npm install ngx-tag-input install nothing (link to github is broken)

**Expected behavior**

install the package
solution is to remove it from npm registry?

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

**Angular version:** 

**ng2-tag-input version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
ngx-tag-input is a fork of this project and not belonging to me.
