### ISSUE TITLE
[Feature Request] Materialize tag input 

### ISSUE THREAD

**Issue by be4code** [Gbuomprisco/ngx-chips#496]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request/question
```

**Current behavior**

Component has different animations and colors than from `@angular/material`

**Expected behavior**

Animations should be like these from `@angular/material`

**What is the motivation / use case for changing the behavior? (if applicable)**

Builded app should have same design and behaviour across all inputs.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

All

**Angular version:** 

**ng2-tag-input version:**

**Browser:** 
all

**Comment by Gbuomprisco** [comment]
Hi,

this component is just inspired by Angular material, but doesn't aim at resembling it 100%. Besides, I'm sure they're building an angular material chips component :)

Happy to accept a PR that adds a `material` theme though
