### ISSUE TITLE
 Component does not appear

### ISSUE THREAD

**Issue by danielswater** [Gbuomprisco/ngx-chips#498]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request/question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Webpack:
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: {
        'app': './app/app.module.ts',
        'vendor': './app/vendor/vendor.ts'
    },
    resolve: {
        extensions: ['', '.ts', '.js', '.css', '.html'],
        modulesDirectories: ["node_modules", "assets\\js"]
    },
    output: {
        filename: '[name].bundle.js',
    },
    module: {

        noParse: [/jszip.js$/],

        loaders: [{
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular2-router-loader'
                ]
            },
            {
                test: /\.html$/,
                loader: 'html'
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?.*$|$)/,
                loader: 'file?name=assets/[name].[hash].[ext]'
            },
            {
                test: /\.css$/,
                exclude: './app',
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
            },
            {
                test: /\.css$/,
                include: './app',
                loader: 'raw'
            },
            {
                test: /[\\\/]assets[\\\/]js[\\\/]modernizr\.min\.js$/,
                loader: "imports?this=>window!exports?window.Modernizr"
            }
        ]
    },

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
            KJUR: "jsrsasign-latest-all-min",
            b64utoutf8: "base64x",
            dateFormat: "dateformat",
            moment: "moment"
        }),
        new ExtractTextPlugin('[name].bundle.css'),
        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor']
        })
    ],
    devServer: {
        historyApiFallback: true,
        stats: 'minimal'
    }
};

package:
{
    "name": "MedTimeWebApp",
    "version": "1.1.0",
    "description": "MedTime Web Application",
    "main": "index.js",
    "scripts": {
        "start": "webpack-dev-server --inline --progress --port 8080",
        "lite": "lite-server",
        "tsc": "tsc",
        "tsc:w": "tsc -w",
        "typings": "typings",
        "postinstall": "typings install"
    },
    "keywords": [],
    "author": "",
    "license": "",
    "devDependencies": {
        "concurrently": "^3.1.0",
        "lite-server": "^2.2.2",
        "typescript": "^2.0.3",
        "typings": "^1.4.0"
    },
    "dependencies": {
        "@angular/animations": "^4.3.1",
        "@angular/common": "~4.2.5",
        "@angular/compiler": "~4.2.5",
        "@angular/core": "^4.2.5",
        "@angular/forms": "~4.2.5",
        "@angular/http": "^4.2.5",
        "@angular/platform-browser": "~4.2.5",
        "@angular/platform-browser-dynamic": "~4.2.5",
        "@angular/router": "^4.2.5",
        "@angular/upgrade": "~4.2.0",
        "angular-in-memory-web-api": "^0.1.17",
        "angular-l10n": "^2.0.6",
        "angular2-router-loader": "^0.3.5",
        "angular2-template-loader": "^0.6.2",
        "awesome-typescript-loader": "^3.0.0-beta.18",
        "bootstrap": "^3.3.7",
        "bootstrap-colorpicker": "^2.5.1",
        "core-js": "^2.4.1",
        "css-loader": "^0.26.1",
        "dateformat": "^1.0.12",
        "del": "^2.2.0",
        "es6-shim": "^0.35.3",
        "exports-loader": "^0.6.3",
        "extract-text-webpack-plugin": "^1.0.1",
        "file-loader": "^0.9.0",
        "file-saver": "^1.3.3",
        "gulp": "^3.9.1",
        "gulp-concat": "^2.6.1",
        "gulp-inject": "^4.2.0",
        "gulp-minify": "0.0.14",
        "gulp-minify-css": "^1.2.4",
        "gulp-symdest": "^1.1.0",
        "gulp-task-listing": "^1.0.1",
        "gulp-uglify": "^2.0.0",
        "hammerjs": "^2.0.8",
        "html-loader": "^0.4.4",
        "html-webpack-plugin": "^2.15.0",
        "imports-loader": "^0.7.0",
        "jquery": "^2.1.4",
        "libphonenumber-js": "^0.4.5",
        "ng2-bootstrap": "^1.4.0",
        "ng2-dnd": "^2.2.2",
        "ng2-tag-input": "^1.4.1",
        "ngx-chips": "^1.4.6",
        "path": "^0.12.7",
        "popsicle": "^9.1.0",
        "reflect-metadata": "^0.1.10",
        "run-sequence": "^1.2.2",
        "rxjs": "^5.0.1",
        "shim": "^0.6.0",
        "style-loader": "^0.13.1",
        "systemjs": "0.19.39",
        "ts-loader": "^0.8.1",
        "typescript": "2.3.4",
        "typings": "^1.4.0",
        "webpack": "^1.14.0",
        "webpack-dev-server": "^1.16.2",
        "webpack-merge": "^2.3.1",
        "webpack-stream": "^3.2.0",
        "xlsx": "^0.10.8",
        "zone": "^0.3.4",
        "zone.js": "^0.8.12"
    },
    "repository": {
        "type": "git",
        "url": "https://symbioz.visualstudio.com/MedTime/_git/MedTimeWebDeploy"
    },
    "engines": {
        "node": "6.11.0"
    }
}

**Angular version:** 

4.2.5

**ng2-tag-input version:**

1.2.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
"ng2-tag-input": "^1.4.1",
"ngx-chips": "^1.4.6"


Use only one (the latter)

**Comment by danielswater** [comment]
I removed the old version, but the problem continues. Here is my Html and Typescript
Html:
`<h3>Simple Input with two items</h3>
        <tag-input [(ngModel)]="items" (onSelect)="onSelect($event)" [modelAsStrings]="true">
        </tag-input>`

Typescript:
`import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/filter';

@Component({
    selector: 'filter-tag',
    templateUrl: 'app/common/tags/tags.component.html'
})

export class TagsComponent implements OnInit {

    constructor(private http: Http) { }
    disabled = true;

    items = ['Javascript', 'Typescript'];

    inputText = 'text';

    itemsAsObjects = [{ id: 0, name: 'Angular', readonly: true }, { id: 1, name: 'React' }];

    autocompleteItems = ['Item1', 'item2', 'item3'];

    autocompleteItemsAsObjects = [
        { value: 'Item1', id: 0, extra: 0 },
        { value: 'item2', id: 1, extra: 1 },
        'item3'
    ];

    dragAndDropExample = ['C#', 'Java'];

    dragAndDropObjects = [{ display: 'Javascript', value: 'Javascript' }, { display: 'Typescript', value: 'Typescript' }];
    dragAndDropStrings = ['CoffeScript', 'Scala.js'];

    ngOnInit() {
        console.log('INICIOU AS TAGS')
    }

    public requestAutocompleteItems = (text: string): Observable<Response> => {
        const url = `https://api.github.com/search/repositories?q=${text}`;
        return this.http
            .get(url)
            .map(data => data.json().items.map(item => item.full_name));
    };

    public requestAutocompleteItemsFake = (text: string): Observable<string[]> => {
        return Observable.of([
            'item1', 'item2', 'item3'
        ]);
    };

    public options = {
        readonly: undefined,
        placeholder: '+ Tag'
    };

    public onAdd(item) {
        console.log('tag added: value is ' + item);
    }

    public onRemove(item) {
        console.log('tag removed: value is ' + item);
    }

    public onSelect(item) {
        console.log('tag selected: value is ' + item);
    }

    public onFocus(item) {
        console.log('input focused: current value is ' + item);
    }

    public onTextChange(text) {
        console.log('text changed: value is ' + text);
    }

    public onBlur(item) {
        console.log('input blurred: current value is ' + item);
    }

    public onTagEdited(item) {
        console.log('tag edited: current value is ' + item);
    }

    public onValidationError(item) {
        console.log('invalid tag ' + item);
    }

    public transform(value: string): Observable<object> {
        const item = { display: `@${value}`, value: `@${value}` };
        return Observable.of(item);
    }

    private startsWithAt(control: FormControl) {
        if (control.value.charAt(0) !== '@') {
            return {
                'startsWithAt@': true
            };
        }

        return null;
    }

    private endsWith$(control: FormControl) {
        if (control.value.charAt(control.value.length - 1) !== '$') {
            return {
                'endsWith$': true
            };
        }

        return null;
    }

    private validateAsync(control: FormControl) {
        return new Promise(resolve => {
            const value = control.value;
            const result = isNaN(value) ? {
                isNan: true
            } : null;

            setTimeout(() => {
                resolve(result);
            }, 1);
        });
    }

    public asyncErrorMessages = {
        isNan: 'Please only add numbers'
    };

    public validators = [this.startsWithAt, this.endsWith$];

    public asyncValidators = [this.validateAsync];

    public errorMessages = {
        'startsWithAt@': 'Your items need to start with \'@\'',
        'endsWith$': 'Your items need to end with \'$\''
    };

    public onAdding(tag): Observable<any> {
        const confirm = window.confirm('Do you really want to add this tag?');
        return Observable
            .of(tag)
            .filter(() => confirm);
    }

    public onRemoving(tag): Observable<any> {
        const confirm = window.confirm('Do you really want to remove this tag?');
        return Observable
            .of(tag)
            .filter(() => confirm);
    }

    public asyncOnAdding(tag): Observable<any> {
        const confirm = window.confirm('Do you really want to add this tag?');
        return Observable
            .of(tag)
            .filter(() => confirm);
    }
}`

And here, the print:
![capturar](https://user-images.githubusercontent.com/20691771/28424194-5c8bb780-6d43-11e7-9753-b6a2209f8d25.PNG)

**Comment by Gbuomprisco** [comment]
Is there any error? Can you check the element in the dev tools and see what happens? Sorry, impossible to debug for me..

**Comment by danielswater** [comment]
No error in console. Only the component does not appear. See:
![capturar](https://user-images.githubusercontent.com/20691771/28428152-cbfb2b68-6d4e-11e7-8349-a011a7ccdbbd.PNG)
![console](https://user-images.githubusercontent.com/20691771/28428153-cbfde0c4-6d4e-11e7-9283-dbf8cfdaced9.PNG)

**Comment by Gbuomprisco** [comment]
can you share a repo?

**Comment by danielswater** [comment]
Sorry I cant. The code is the company I work for :(

**Comment by danielswater** [comment]
Is it necessary to add something in the Webpack?

**Comment by Gbuomprisco** [comment]
try to follow this project's demo config as much as possible

**Comment by danielswater** [comment]
Ok. In the Webpack I added this line, as in the example:
`'ngx-chips': './node_modules/ngx-chips/index.ts `

But the following errors occurred to me:
vendor.bundle.js:sourcemap:8409 Uncaught TypeError: Reflect$1.getOwnMetadata is not a function
vendor.bundle.js:8290 Uncaught reflect-metadata shim is required when using class decorators

**Comment by Gbuomprisco** [comment]
that shouldn't be needed in your project

**Comment by danielswater** [comment]
Okay. Webpack is the only thing other than example :(
