### ISSUE TITLE
AutocompleteObservable and onTextChange events not working

### ISSUE THREAD

**Issue by jeanmalves** [Gbuomprisco/ngx-chips#499]
Hello,

I am using tagInput in my application. I need use with external request, so i tested with observable and onTexChange event but when i visit de browser the debugger report error:

ERROR TypeError: this.inputForm.form.valueChanges.debounceTime is not a function

I imported 'rxjs/add/operator/filter' but not success. i used the example from demo and not working too.

version i am using :
Angular: 4.2.6,
"ngx-chips": 1.4.6,
Browser : Google chrome and firefox.

**Comment by Gbuomprisco** [comment]
debounceTime is defined here, so the issue must be somewhere in your config.

see https://github.com/Gbuomprisco/ngx-chips/search?q=debounceTime&type=Code&utf8=%E2%9C%93.

I suggest you to add package.json and some code (please next time complete the template, don't remove it)

**Comment by jeanmalves** [comment]
Thanks @Gbuomprisco!
The next time i will complete the template.
