### ISSUE TITLE
onAdding gives security error

### ISSUE THREAD

**Issue by itssuyog96** [Gbuomprisco/ngx-chips#500]
**I'm submitting a ...**
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
Gives following error on using [onAdding]

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Binding to event property 'onAdding' is disallowed for security reasons, please use (Adding)=...
If 'onAdding' is a directive input, make sure the directive is imported by the current module. ("isplayBy]="'username'" [identifyBy]="'$key'" [autocompleteItems]="requestAutocompleteItems | async" [ERROR ->][onAdding]="onAdding">
                                <ng-template let-item="item">
                "): ng:///PreproModule/ViewDetailedAssetComponent.html@33:206
Can't bind to 'onAdding' since it isn't a known property of 'tag-input-dropdown'.
1. If 'tag-input-dropdown' is an Angular component and it has 'onAdding' input, then verify that it is part of this module.
2. If 'tag-input-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("isplayBy]="'username'" [identifyBy]="'$key'" [autocompleteItems]="requestAutocompleteItems | async" [ERROR ->][onAdding]="onAdding">
                                <ng-template let-item="item">
                "): ng:///PreproModule/ViewDetailedAssetComponent.html@33:206


```

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version** : Webpack 2.2.0

**Angular version:** 4.1.3

**ng2-tag-input version:** 1.4.6

**Browser:** all

**Comment by itssuyog96** [comment]
I think this is an issue in angular 4^. "`on`" prefixes to any directives gives security error.

**Comment by Gbuomprisco** [comment]
sounds odd as I've never encountered this error

**Comment by itssuyog96** [comment]
Ok, it was my fault. I was using square brackets '['. I should have used parenthesis '('.

Thank you @Gbuomprisco for your efforts.

**Comment by kimamula** [comment]
I got the same error when I run `ng test`, though it works without any error when I run `ng serve`.
`onAdding` should be used with brackets as it is `@Input()`.

It seems `on*` properties are actually forbidden.

https://github.com/500tech/angular-tree-component/issues/223
https://github.com/valor-software/ngx-bootstrap/issues/1000
https://github.com/angular/angular/issues/11756

**Comment by fallenreaper** [comment]
Anyone know how to suppress this `ng test` error?
