### ISSUE TITLE
Autocomplete drop down doesn't allow to add duplicate items 

### ISSUE THREAD

**Issue by pmr93** [Gbuomprisco/ngx-chips#501]
I'm submitting a ... (check one with "x")

[x] bug report => search github for a similar issue or PR before submitting
[] feature request
[ ] support request/question

**Current behavior**

Currently we only can select unique items from the autocomplete dropdown. Once we add a value it won't show again in the drop down for the user to select.

**Expected behavior**

Duplicate items should be able to select from autocomplete drop down.

**Angular version:** 
4

What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version : angular-cli

ng2-tag-input version: 1.4.6

Browser: all

**Comment by Gbuomprisco** [comment]
To clarify: this is a feature request, not a bug.

**Comment by Gbuomprisco** [comment]
Can you please check if this works with the latest version? Thanks!
