### ISSUE TITLE
Create on onClick event

### ISSUE THREAD

**Issue by eyalhakim** [Gbuomprisco/ngx-chips#503]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request/question
```

**Current behavior**

I would like to be notified when a tag was clicked. Possible solutions might be to create an onClick output or to pass the original event to onSelect.

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

**Angular version:** 

**ng2-tag-input version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @eyalhakim,

wouldn't onSelect work?

**Comment by eyalhakim** [comment]
hi @Gbuomprisco, it does but also on keyboard selection and i need click specifically.

**Comment by bxcodec** [comment]
Any update about this feature ? 🤔

**Comment by Gbuomprisco** [comment]
New features won't be added for now
