### ISSUE TITLE
Unexpected behavior when onlyFromAutocomplete=false with focusFirstElement=true

### ISSUE THREAD

**Issue by needsmorecoffee** [Gbuomprisco/ngx-chips#504]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

Tag doesn't get added properly with certain configuration options,

**Expected behavior**

Full tag should be added.

**Minimal reproduction of the problem with instructions (if applicable)**

If a <tag-input> sets [onlyFromAutocomplete]=false with [focusFirstElement]=true on the <tag-input-dropdown>, when enter is pressed to add a tag only the first letter of the tag is added. Also using [autocompleteObservable] but this didn't seem to matter.

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli on windows

**Angular version:** 

4.2.6

**ng2-tag-input version:**

1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
SOrry, I've never encountered this. Closing for now, but maybe add an online demo if you still see this and I will investigate.
