### ISSUE TITLE
Autocompletion dropdown list shown when nothing to show

### ISSUE THREAD

**Issue by AVykhrystyuk** [Gbuomprisco/ngx-chips#506]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

I use the following markup
```
<tag-input [ngModel]="['@item']">
      <tag-input-dropdown [autocompleteItems]="['item1', 'item2', 'item3']"></tag-input-dropdown>
</tag-input>
```
when I start typing "ite" I see autocompletion dropdown populated with items:
![tag-before-bug](https://user-images.githubusercontent.com/5488533/28642934-c4f05f92-725c-11e7-85e0-2a00abcc9c20.png)
and even when I input an nonexistent character I still see the dropdown, but now it's empty:
![tag-bug](https://user-images.githubusercontent.com/5488533/28642828-59b5d5f4-725c-11e7-89d9-d6d2b8f36336.png)

**Expected behavior**
Autocompletion dropdown should be hidden when there is nothing to show.

**What is the motivation / use case for changing the behavior? (if applicable)**
Opened empty dropdown looks really weird :(

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
windows 10,
webpack: 3.3.0

**Angular version:** 
4.3.0

**ng2-tag-input version:**
"ngx-chips": "1.4.6"

**Browser:** 
All modern: Chrome 59, Firefox 54, Opera 46,  IE11, Microsoft Edge 40

**Comment by Gbuomprisco** [comment]
Hi @AVykhrystyuk can you check out v1.4.9? releasing in a few minutes

**Comment by AVykhrystyuk** [comment]
Hi @Gbuomprisco I've just tested the issue with ngx-chips v1.5.0.
Works like a charm. The issue is gone!
Thank you man

**Comment by Gbuomprisco** [comment]
Awesome :)
