### ISSUE TITLE
showDropdownIfEmpty option makes overlay appear after tag add

### ISSUE THREAD

**Issue by szanella** [Gbuomprisco/ngx-chips#508]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
~~[ ] feature request~~ [new feature requests are not considered at this time]
[ ] support request/question
```

**Current behavior**
I'm using the tag-input with the showDropdownIfEmpty option and the following issue happens: I focus the input, the dropdown shows up (along with its backdrop); now if I select an element, the dropdown and backdrop will disappear, for the backdrop to then suddenly appear (without the dropdown) and cover the whole screen, forcing me to click again to use the interface.

This is my setup:
```
<tag-input
      [placeholder]="''"
      [secondaryPlaceholder]="''"
      [name]="filter.key"
      [ngModel]="filter.value"
      (ngModelChange)="updateFilter($event)"
      [onlyFromAutocomplete]="true"
      [ripple]="false">
      <tag-input-dropdown [showDropdownIfEmpty]="true"
                          [autocompleteItems]="filter.options">
      </tag-input-dropdown>
    </tag-input>
```

**Expected behavior**

The overlay should not appear.

**Minimal reproduction of the problem with instructions (if applicable)**

This is the sequence of events:

focus the tag-input, dropdown appears
select an item, it gets added, the dropdown disappears
the tag-input automatically gets focused again, and the overlay appears again

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app?. Please specify the version**

Angular-CLI

**Angular version:** 

4.2.5

**ngx-chips version:** 
1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 59.0.3071.115

**Comment by Gbuomprisco** [comment]
@szanella do you see any console errors?

**Comment by szanella** [comment]
Nope, I've never seen any console error while this problem happens

**Comment by Gbuomprisco** [comment]
No, but the issue is I can't reproduce at all, which leads me to think it's the interaction with other components causing this

**Comment by szanella** [comment]
Good news (I think)! I gave the latest version a go (1.4.9), and now the behaviour is slightly different; still not the one I'd like, but definitely more consistent.
Now the dropdown will always display after a tag add, which is what #222 was about. How exactly am I supposed to prevent this? Thanks for the support :)

**Comment by Gbuomprisco** [comment]
That was requested by a number of users. Is showDropdownIfEmpty important in your case?

**Comment by szanella** [comment]
That option allows me to effectively use the component as a normal select input, allowing me to open the dropdown by simply clicking on the text input (as well as by typing, of course), which is greatly useful. I think this was the whole purpose of it, and I can also see why it would make sense to open it again after each addition; it's perfectly consistent.

My question is: wasn't #222 asking to prevent the dropdown from displaying after adding a tag, or am I reading it wrong? If that's the case, that behaviour would be A-Okay for my use-case, but unfortunately it's not happening, as the dropdown is still appearing at every addition :)

**Comment by Gbuomprisco** [comment]
Yes, #222 was actually about adding a new option to prevent this behaviour (but I just changed it completely, which pissed of some:). Maybe a new option could be useful

**Comment by Gbuomprisco** [comment]
This https://github.com/Gbuomprisco/ngx-chips/pull/522 will added a keepOpen option to prevent that

**Comment by szanella** [comment]
I've tested it, and it seems to work perfectly as intended, great job!

As far as I'm concerned, this issue can be closed, thanks for the kind support :)

**Comment by Gbuomprisco** [comment]
Great!
