### ISSUE TITLE
It it possible to dynamically push a chip into the list?

### ISSUE THREAD

**Issue by joshterrill** [Gbuomprisco/ngx-chips#513]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request~~ [new feature requests are not considered at this time]
[x] support request/question
```

**Current behavior**

I have this in my HTML:
```
<tag-input [(ngModel)]="selectedRecipients" [onlyFromAutocomplete]="true" (onAdd)="onAdding($event)">
        <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="contacts" [identifyBy]="'Oid'" [displayBy]="'DisplayName'"></tag-input-dropdown>
</tag-input>
```

When I select items in my `contacts` array, I see the objects getting added to `selectedRecipients`. However, when I load the component, I would like to dynamically insert an object so that the component renders with one chip already added. 

Currently it adds a chip, but the chip has nothing in it, just a blank chip with an X button.

**Expected behavior**

I would expect to be able to push an object to `selectedRecipients`, and as long as that object had the properties that were being looked at by the component, the chip would show up being filled out.

**Minimal reproduction of the problem with instructions (if applicable)**

In my case, I have objects that have a display by `DisplayName` and an identifyBy as `Oid`. So I would figure if I instantiate `selectedRecipients` with `{"DisplayName": "Some Name", "Oid": 1}` or `this.selectedRecipients.push({"DisplayName": "Some Name", "Oid": 1})`. When the component loads, it has a blank chip with an X icon.

**What is the motivation / use case for changing the behavior? (if applicable)**

N/A

**What do you use to build your app?. Please specify the version**

Angular CLI

**Angular version:**

Angular: 4.3.0

**ngx-chips version:**

1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 

Chrome

**Comment by Gbuomprisco** [comment]
Hi @joshterrill,

I think what you're missing is assigning displayBy and identifyBy to the tag-input. Notice: you added it to the dropdown, but you need to also tell tag-input what to display. Which is why is empty.
Programmatically, you can edit the model whenever you want as it uses 2-way data binding.
