### ISSUE TITLE
Unexpected errors when I select item

### ISSUE THREAD

**Issue by Wanted92** [Gbuomprisco/ngx-chips#514]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
~~[ ] feature request~~ [new feature requests are not considered at this time]
[ x] support request/question
```

**Current behavior**

I have this in my HTML:
```
<tag-input formControlName="elementi_controllo_analogo_iesimo" [modelAsStrings]="true" [maxItems]="1" id="elementi_controllo_analogo_iesimo" [animationDuration]="{enter: '0ms', leave: '0ms'}">
   <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="this.items"></tag-input-dropdown>
</tag-input>
```
When I render this HTML in console there is the following error:

> ERROR TypeError: this.inputForm.form.valueChanges.debounceTime is not a function
    at TagInputComponent.setUpTextChangeSubscriber (ngx-chips.bundle.js:2212)
    at TagInputComponent.ngAfterViewInit (ngx-chips.bundle.js:2110)
    at callProviderLifecycles (core.es5.js:11180)
    at callElementProvidersLifecycles (core.es5.js:11155)
    at callLifecycleHooksChildrenFirst (core.es5.js:11139)
    at checkAndUpdateView (core.es5.js:12244)
    at callViewAction (core.es5.js:12601)
    at execEmbeddedViewsAction (core.es5.js:12559)
    at checkAndUpdateView (core.es5.js:12237)
    at callViewAction (core.es5.js:12601)

and when I select my item from dropdown there is the following error:

> ERROR Error: Unable to process animations due to the following failed trigger transitions
> @animation has failed due to:
> - Please provide a value for the animation param enter
> - The provided timing value "" is invalid.

**Expected behavior**

I want no errors on my actions

**Minimal reproduction of the problem with instructions (if applicable)**

N.A

**What is the motivation / use case for changing the behavior? (if applicable)**

N.A

**What do you use to build your app?. Please specify the version**

Angular CLI

**Angular version:** 

Angular 4.0.0

**ngx-chips version:**

1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
The component requires v4. 2.0 at least

**Comment by Gbuomprisco** [comment]
For the denounce issue, you may want to check you can import that with rxjs

**Comment by Wanted92** [comment]
Ok thanks, it works
