### ISSUE TITLE
The editable functionality is wonky at selecting all of the text to edit

### ISSUE THREAD

**Issue by xtianus79** [Gbuomprisco/ngx-chips#515]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
~~[x?] feature request~~ [new feature requests are not considered at this time]
[ ] support request/question
```

I created a plunkr here of how we will use this. 
http://plnkr.co/edit/j3C499?p=preview

**Current behavior**
When you are editing a tag / chip it doesn't really hold onto the text... it takes a few tries or brining the cursor icon to the very far right of the word / text input and then backspacing

**Expected behavior**

selects the entire text area for tht word

**Minimal reproduction of the problem with instructions (if applicable)**

check out the plunkr
http://plnkr.co/edit/j3C499?p=preview

**What is the motivation / use case for changing the behavior? (if applicable)**

would it be nice / proper to do a select all of the text area when doubling clicking to edit chip occurs?  

**What do you use to build your app?. Please specify the version**

systemjs webpack angular 4 blah blah blah 

**Angular version:** 

4

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, just released v.1.4.7. Should improve this a little bit. Issue was that dblclick event was active even when editing the text. Only issue is when you select and remove all test you won't see the cursor blinking which is a little misleading.

Will reopen if still an issue

**Comment by xtianus79** [comment]
@Gbuomprisco thanks, I will test that out.  Can you do releases here in git so that there is version tracking?

**Comment by xtianus79** [comment]
@Gbuomprisco thanks, that works a lot better!!! 

I would however like it if when doubling clicking and the editable field is ediable that the work would already be selected... but that might be personal preference.  In any event great work.
