### ISSUE TITLE
Editable Chip's content is not editable on Touch devices.

### ISSUE THREAD

**Issue by kkotak** [Gbuomprisco/ngx-chips#518]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
~~[ ] feature request~~ [new feature requests are not considered at this time]
[ ] support request/question
```

**Current behavior**

There is no way to edit the text of a chip on touch devices like iPad, iPhone.

**Expected behavior**

There should be a way to do this either through an edit icon, long press, or double tap.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

To allow for consistent user experience across devices.

**What do you use to build your app?. Please specify the version**

Angular-cli 1.30

**Angular version:** 

4.3.1

**ngx-chips version:**

1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Hi @kkotak,

I tried on my Android and double tap is working OK. I don't own an iPhone so I'm afraid I can only accept PRs.
