### ISSUE TITLE
autocompleteObservable not working in 1.4.9

### ISSUE THREAD

**Issue by karencuberodesigner** [Gbuomprisco/ngx-chips#521]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
~~[ ] feature request~~ [new feature requests are not considered at this time]
[ ] support request/question
```

**Current behavior**
autocompleteObservable method does not work well. It should trigger the function but it doesn't in the last release 1.4.9 but it does in 1.4.8.

**Expected behavior**
Show a dropdown list from an Observable.

**Minimal reproduction of the problem with instructions (if applicable)**
This is the HTML:
```
          <tag-input name="auto" (onRemove)="onRemove($event)" (onAdd)="onAdd($event)" [maxItems]="maxItems" #auto theme="bootstrap"
            class="autocompleter" [(ngModel)]="items" [placeholder]="placeholder" [onTextChangeDebounce]="500" [secondaryPlaceholder]="placeholder"
            [onlyFromAutocomplete]="true">
            <tag-input-dropdown [offset]="'59 5'" [displayBy]="'label'" [identifyBy]="'label'" [autocompleteObservable]="requestAutocompleteItems">
              <ng-template let-item="item" let-index="index">
                {{ item.label }} ({{item.hotels ? 'CIU' : 'HOT'}})
              </ng-template>
            </tag-input-dropdown>
          </tag-input>
```
Here it's the requestAutocompleteItems method:
```
  requestAutocompleteItems = (text: string): Observable<any> => {
    console.log("SELECT");
    return this.apiService.getSearch(text, this.onlyHotels);
  };
```

**What is the motivation / use case for changing the behavior? (if applicable)**
Solve a bug.

**What do you use to build your app?. Please specify the version**
Angular CLI

**Angular version:** 
Angular CLI 1.2.6 and Angular 4.3.3

**ngx-chips version:**
1.4.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 60.0.3112.90 (Build oficial) (64 bits) (cohorte: 60_90_win)

**Comment by Gbuomprisco** [comment]
to be fixed by https://github.com/Gbuomprisco/ngx-chips/pull/522

**Comment by karencuberodesigner** [comment]
@Gbuomprisco Really thanks!

Another thing I have seen is that I have to import rxjs opperators manually if I use onRemoving method. Is it a mistake or is it fine?

**Comment by Gbuomprisco** [comment]
Those imports are within your application and a peer dependency for ngx-chips to work, so it's the right thing to do :)
