### ISSUE TITLE
ERROR in TagInputModule is not an NgModule

### ISSUE THREAD

**Issue by anil-agrawal** [Gbuomprisco/ngx-chips#524]
**I'm submitting a bug report** 

**Current behavior**

My project not being complied, getting error "**ERROR in TagInputModule is not an NgModule**"

**Expected behavior**

Project should be compiled without any issue.

_If I change the declaration file tag-input.module.d.ts  as below , issue got solved._

import { Options } from './core';
import { NgModule } from '@angular/core';
@NgModule() export declare class TagInputModule {
    static withDefaults(options: Options): void;
}

**Minimal reproduction of the problem with instructions (if applicable)**

Just install module ng2-tag-input in angular2 project and import module TagInputModule in any custom module. And try to run the project.

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app?. Please specify the version**

My project dependencies are as below
"devDependencies": {
        "@angular/cli": "1.2.0",
        "@angular/compiler-cli": "^4.0.0",
        "@angular/language-service": "^4.0.0",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "angular-ide": "^0.9.29",
        "codelyzer": "~3.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.0.4",
        "tslint": "~5.3.2",
        "typescript": "~2.3.3"
    }

**Angular version:** 

**ngx-chips version:**

 "ng2-tag-input": "^1.4.1",

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
@anil-agrawal ng2-tag-input is not supported, if you want to use this component you need to instal ngx-chips (and likely update your deps)

**Comment by anil-agrawal** [comment]
thanks
