### ISSUE TITLE
 Iteration with formBuilder array

### ISSUE THREAD

**Issue by renanmoraes** [Gbuomprisco/ngx-chips#530]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

``formBuilder structure``
![captura de tela de 2017-08-10 16-51-13](https://user-images.githubusercontent.com/12611706/29189521-3e23dede-7ded-11e7-94ea-9032327be363.png)

``html structure``
![captura de tela de 2017-08-10 17-00-17](https://user-images.githubusercontent.com/12611706/29189574-7184590c-7ded-11e7-897a-e7f19354a340.png)

```Error```
![captura de tela de 2017-08-10 17-18-00](https://user-images.githubusercontent.com/12611706/29190286-e894f284-7def-11e7-9096-69585fc0a345.png)

This problem is happening when I am submitting a tag. I need it to add the tags along with my formBuild at times which is a string array.

```Method transform values```
![captura de tela de 2017-08-10 17-20-09](https://user-images.githubusercontent.com/12611706/29190396-5d4261a2-7df0-11e7-9dc1-6f767612964b.png)

```The array is thus becoming an array of objects.```
![captura de tela de 2017-08-10 17-51-15](https://user-images.githubusercontent.com/12611706/29191610-b6b0c022-7df4-11e7-995d-bdaf82a1d684.png)

```I need it to save me an array of string.```

```Objeto: { "name": "", "code": "", "rate": "", "status": true, "accessibility": true, "_city": "", "_categoryLine": "", "_operator": "", "daysOperations": { "week": { "status": true, "tripA": { "origin": "", "destiny": "", "schedules": [ "25:36" , "15:63", "23:46"], "routes": { "schedules": {}, "name": "" } } } } } ```

**Expected behavior**
I need to add a string array. But I'm using formBuilder

**What do you use to build your app?. Please specify the version**
```Angular CLI```

**Angular version:** 
```@angular/cli: 1.2.0
node: 6.11.1
os: linux x64
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/upgrade: 4.3.0
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
```

**ngx-chips version:**
```version 1.5.0```

**Browser:** 
```Chrome```

**Comment by Gbuomprisco** [comment]
Use modelAsString property
