### ISSUE TITLE
CSS changes for invalid tags?

### ISSUE THREAD

**Issue by dland512** [Gbuomprisco/ngx-chips#531]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```
<br>

### Question

Does the system support changing the CSS of a tag if it's determined to be invalid? I'd like for the user to be able to enter any tag they want but to change the background color to red if the tag is not considered valid.
<br>

**Current behavior**
n/a

**Expected behavior**
n/a

**Minimal reproduction of the problem with instructions (if applicable)**
n/a

**What do you use to build your app?. Please specify the version**
webpack

**Angular version:** 
2.4.8

**ngx-chips version:**
0.8.6

**Browser:** 
n/a

**Comment by Gbuomprisco** [comment]
Hi @dland512,

if you add a validator, the model won't accept the tag, and the system does not support what you'd need (e.g. let invalid tags in, but mark them as invalid as well). 

If you don't add a validator, and let all tags be entered, you could add a custom check called on each tag, maybe using the template to get the item's value. You could do some styling based on that, but am pretty sure you will have to move a few bits around for the desired result.

**Comment by na-le** [comment]
@dland512 
I need to implement something like you described.
did you success?
if so, can you share your changes?

**Comment by dland512** [comment]
@na-le No, we just went with the library as it currently works (which may not support every last thing we need but it still a pretty sweet control).

**Comment by chelaruc** [comment]
@na-le have you managed to change the style of error tags?
