### ISSUE TITLE
 Tag input does not work without using ngModel

### ISSUE THREAD

**Issue by renanmoraes** [Gbuomprisco/ngx-chips#533]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
When shooting ngModel does not work, it issues the following error on the console.

![captura de tela de 2017-08-11 16-04-59](https://user-images.githubusercontent.com/12611706/29228300-a05d86c8-7eaf-11e7-8a43-38eb0f636ca4.png)

This is the html code in question
![captura de tela de 2017-08-11 16-11-24](https://user-images.githubusercontent.com/12611706/29228342-c9351fac-7eaf-11e7-844e-f2a180d3dbd7.png)

This way it is sending the error, and it does not work.

**Expected behavior**
I need the tag-input to work without ngModel only with formControlsName.

**Minimal reproduction of the problem with instructions (if applicable)**
I can not reproduce the error.

**What do you use to build your app?. Please specify the version**
Angular CLI

**Angular version:** 

```node: 6.11.1
os: linux x64
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/upgrade: 4.3.0
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
```

**ngx-chips version:**
v1.5.0

**Browser:** 
Chrome

**Comment by Gbuomprisco** [comment]
It looks like you are using an object instead of an array

**Comment by renanmoraes** [comment]
Yes, it is an array of objects. However I need to use without ngModel because this field is added dynamically.

**Comment by Gbuomprisco** [comment]
From the error message it seems it's an object of objects.. Can you double check that? Can you write here the structure of the model too?

**Comment by renanmoraes** [comment]
This is the total part that competes with the example
```
tripA: this.formBuilder.group({
            origin: ['', Validators.required],
            destiny: ['', Validators.required],
            schedules: [{}, Validators.required],
            routes: this.formBuilder.array([
              this.initRouteItem()
            ])
```
There is and the dynamic part I'm adding to each click of the button
```
    return this.formBuilder.group({
      name: [''],
      schedules: [{}]
    });
```
My add button performs this function
```
  private addRoute(): void {
    const control = <FormArray>this.formLine.get('daysOperations').get('week').get('tripA').get('routes');
    control.push(this.initRouteItem());
  }
```

**Comment by Gbuomprisco** [comment]
basically: what is `schedules`, what is its full structure?

**Comment by renanmoraes** [comment]
Schedules is an array of string:
```{"22:56", "21:24", "25:66"}```

**Comment by Gbuomprisco** [comment]
but I see an object
```
schedules: [{}, Validators.required],
```

**Comment by renanmoraes** [comment]
Maybe that's the error, how can I improve this, what I need is a string array. But how?

**Comment by Gbuomprisco** [comment]
Just replace the object to an array
```
schedules: [[], Validators.required],

```
