### ISSUE TITLE
how to make it take the object like object not arr[0]

### ISSUE THREAD

**Issue by OdaiTu** [Gbuomprisco/ngx-chips#534]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

 im using the ng2-tags-input and its awesome but when i make the maxItem to one
i think the right behavior to take its like object not array on one object
tag: [
           {
                 name: 'tag'
                  id: 5
           }
]

**Expected behavior**

but the right is to be like this 
 {
                 name: 'tag'
                  id: 5
           }
right ?

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli
**Angular version:** 

 2.4

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @OdaiTu,

The value provided (ngModel) will always need to be an array. It internally uses an ngFor, and that requires arrays. I don't see why this would be a problem anyway? Besides, it's also to keep consistency.
