### ISSUE TITLE
error when aot compile

### ISSUE THREAD

**Issue by OdaiTu** [Gbuomprisco/ngx-chips#536]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

![image](https://user-images.githubusercontent.com/12837840/29310923-5e5500f6-81b8-11e7-8b61-f2864c80f01b.png)

**Expected behavior**

--

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli
**Angular version:** 

2.4.10

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
upgrade your angular version

**Comment by OdaiTu** [comment]
@Gbuomprisco  to what version  ?
i dont want to use angular 4 ?
 can you give me the command to do that using angular cli ?

**Comment by Gbuomprisco** [comment]
If you don't want to use angular 4 you can only install ng2-tag-input version 1.0.0 but it's unsupported and any bug will not be fixed

**Comment by OdaiTu** [comment]
@Gbuomprisco  how to target the version when doing npm install ?

**Comment by Gbuomprisco** [comment]
package@1.0.0

**Comment by OdaiTu** [comment]
![image](https://user-images.githubusercontent.com/12837840/29517519-369a080c-867e-11e7-9e71-f41b522f45b1.png)

!
