### ISSUE TITLE
Dropdown Menu overflow is set to initial

### ISSUE THREAD

**Issue by lcecil** [Gbuomprisco/ngx-chips#538]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Using the `<tag-input-dropdown>` component, when I type in the input field, the list of menu items isn't being hidden by its container.

**Expected behavior**

The dropdown menu container should hide the extra menu items and scroll, by having the element set to `overflow-Y: auto;`. This is getting overridden right now by styles set with javascript (I'm assuming) directly on the element as `overflow: initial`

**Minimal reproduction of the problem with instructions (if applicable)**

See image below for visual of the problem as well as the css on the right-hand side
![image](https://user-images.githubusercontent.com/15719045/29375311-600255e6-8269-11e7-9c56-a2cda1da4a80.png)

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

4.2.4

**ngx-chips version:**

1.5.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 60.0.3112.90

**Comment by lcecil** [comment]
For now, i've just set the the `limitItemsTo` property so that the menu items fit in the container. But this should probably still be fixed at some point (if it's a reproducible bug).

**Comment by Gbuomprisco** [comment]
v1.5.3 released :)
