### ISSUE TITLE
Sort times ascending

### ISSUE THREAD

**Issue by renanmoraes** [Gbuomprisco/ngx-chips#541]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Expected behavior**

I need to get the items entered in the field and sorted in ascending order. The field I am using to add hours then for example to entered 00:00, 02:00, 05:00 it should always remain in this order ai in case I type 00:05 it should enter the middle between 00:00 and 02:00

**Minimal reproduction of the problem with instructions (if applicable)**

```
  <tag-input [onAdding]="transform"
                   [editable]="true"
                   [modelAsStrings]="true"
                   formControlName="schedules"
                   theme="dark"
                   placeholder="+ Horarios"
                   [secondaryPlaceholder]="'Adicione horarios'"></tag-input>
```
```
  /**
   * Function that is validated and added : at the times inserted
   * @param {string} value
   * @returns {Observable<string>}
   */
  public transform(value: string): Observable<string> {
    const reg = new RegExp('^[0-9]*$');
    if (value.length < 4 || !reg.test(value)) {
      return Observable.of('');
    }
    const val = value.split('');
    const formated = val[0] + val[1] + ':' + val[2] + val[3];
    return Observable.of(formated);

  }
```

**What do you use to build your app?. Please specify the version**
``` ANGULAR CLI ```

**Angular version:** 
 ```
node: 6.11.1
os: linux x64
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/upgrade: 4.3.0
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.5
```

**ngx-chips version:**
``` 1.5.0 ```

**Browser:** 
``` CHROME ```

**Comment by Gbuomprisco** [comment]
You have access to the model so all you should do is reorder the items yourself when the model changes. You can use outputs to be notified when that happens.

**Comment by renanmoraes** [comment]
Could you give me an example of how to do this?

**Comment by Gbuomprisco** [comment]
check the demo, it has examples with outputs
