### ISSUE TITLE
Lazy loading is not working

### ISSUE THREAD

**Issue by h4mit** [Gbuomprisco/ngx-chips#543]
Hi, not working tag input when use on lazy loading and 'loadchildren' page module, need import BrowserAnimationModule while only import CommonModule. when import BrowserAnimationModule  to loadchildren module error *ngIf and *ngFor.

**Angular version:** 4.3.4

**ngx-chips version:** 1.5.2

**Browser:**  Chrome XX | Firefox XX

**Comment by Gbuomprisco** [comment]
@h4mit are you loading both modules?

**Comment by igmdvc** [comment]
@Gbuomprisco if you are creating a library for being consumed by an application that potentially uses lazy load modules, as @h4mit says, you don't need to add BrowserModule or BrowserAnimationModule but CommonModule.

Just in the instructions of how to integrate it just explaining that in the main module BrowserAnimationsModule should be added.

Being this straightforward, would you accept a pull request for that?.

Thanks.
