### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by itcozum** [Gbuomprisco/ngx-chips#544]
Hi,

I'm getting this error after installing this component,

ERROR in C:/TPS/2017/tps-hr/web/node_modules/ngx-chips/dist/modules/components/tag-input/tag-input.d.ts (72,17): Cannot find name 'object'.

and more-so whats is the diff, betwwn ng2-tag-input and ngx-chips as its the same author and same link

Thanks in advance.
Nel

PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
The name has changed to be consistent with other packages based on angular > 2. It seems you need to upgrade your ts version
