### ISSUE TITLE
Autocomplete dropdown doesn't appear anymore.

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ngx-chips#545]
**I'm submitting a ...** 
```
[x] bug report 
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
I recently migrated my app to angular 4, so I replaced ng2-tag-input with ngx-chips.
I use the autocomplete dropdown, but it doesn't appear anymore.

**Expected behavior**
The autocomplete dropdown should appear.

**Minimal reproduction of the problem with instructions (if applicable)**
By cloning the project ngx-chips and trying the demo, I obtain following behavior : at beginning the autocomplete appears normally. But if I focus to an other page and if I go again to the app, it doesn't work anymore.
On my own project, the dropdown doesn't appears at the beginning.

**What do you use to build your app?. Please specify the version**
Webpack

**Angular version:** 
4.3 or more

**ngx-chips version:**
1.5.3

**Browser:** 
all

**Comment by Gbuomprisco** [comment]
Can you please provide a demo?

**Comment by sancaruso** [comment]
Do you have a plunker or somewhat with your package? I don't know how to use a package on plunker.

More precisions after some tests: I use an autocompleteObservable. But when I tried with a simple array using autocompleteItems I have no problem.
Did you changed the using of autocompleteObservable? (When I read the doc it seems that you don't, but I don't know why it doesn't work anymore like before I migrate to ng4.)

**Comment by sancaruso** [comment]
It seems that the dropdown don't update when the observable emits a new value: I tried with
`observable = (text: string) => Observable.of([], ['item1', 'item2']);`
and the dropdown is empty.
With
`observable = (text: string) => Observable.of(['item1', 'item2'], ['item3', 'item4']);`
the dropdown displays item1 and item 2, not item3 and item4.

**Comment by Gbuomprisco** [comment]
Not sure why you are sending two arrays.. You need to send only 1 array which will populate the autocomplete items

**Comment by sancaruso** [comment]
I was sending two arrays only to give a simple example, but it is not exactly my usecase.
I understand that you want to avoid leaks, but actually I nevertheless need to keep the subscription to the observable because I use lasy loading of my data. (I first load the 60 first results, and if the user scroll to the end I load the 60 following, etc...)
Perhaps it would be possible to unsubscribe only when the input text changes ?

**Comment by sancaruso** [comment]
@Gbuomprisco I don't know how to reopen the issue...

**Comment by Gbuomprisco** [comment]
create a new ticket as it is a different issue altogether I think
