### ISSUE TITLE
Autocomplete problem

### ISSUE THREAD

**Issue by chocmah** [Gbuomprisco/ngx-chips#546]
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

**Current behavior**

And i got the following console error :
ERROR TypeError: this.tagInput.onTextChange.debounceTime is not a function

**Expected behavior**

should display the dropdown

**Minimal reproduction of the problem with instructions (if applicable)**
Tryed a simple dropdown with autocomplete using array of string as per example:
```
                  <tag-input  inputId="fctInput" 
                    
                              addOnBlur="true" 
                              modelAsStrings="true" 
                              addOnPaste="true" 
                              formControlName="fonctions" 
                              class="form-control" placeholder="+ Fonction" secondaryPlaceholder="Enter Fonctions" >
                              <tag-input-dropdown 
                                [autocompleteItems]="['iTem1', 'item2', 'item3']">
                              </tag-input-dropdown>
                  </tag-input>
```

**What do you use to build your app?. Please specify the version**
    "@angular/cli": "1.3.0",

**Angular version:** 
   "@angular/animations": "^4.3.5",
    "@angular/common": "^4.3.5",
    "@angular/compiler": "^4.3.5",
    "@angular/core": "^4.3.5",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.3.5",
    "@angular/http": "^4.3.5",
    "@angular/platform-browser": "^4.3.5",
    "@angular/platform-browser-dynamic": "^4.3.5",
    "rxjs": "^5.4.3",

**ngx-chips version:**
    "ngx-chips": "^1.5.3",

**Browser:**  Chrome  lastest

**Comment by Gbuomprisco** [comment]
import debounceTime in your file

**Comment by chocmah** [comment]
Thanks it's worked! i added import 'rxjs/add/operator/debounceTime';


Don't you think it's should be documented or automatically imported in the component?

I found it counter-intuitive to add a import to a third party in my form component

Best regards and good job on the component btw

**Comment by Gbuomprisco** [comment]
Yeah it must be missing somewhere. I'll add it in the next release
