### ISSUE TITLE
Continue typing while dropdown focus

### ISSUE THREAD

**Issue by kadosh1000** [Gbuomprisco/ngx-chips#548]
**I'm submitting a ...**
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```
**Current behavior**
The text input looses focus while navigating in the dropdown using the keyboard

**Expected behavior**
The text input should stay in focus even while navigating the dropdown so the user can continue typing.
You can see the following exmaples:
https://www.primefaces.org/primeng/#/autocomplete
https://material.angular.io/components/autocomplete/examples

**Minimal reproduction of the problem with instructions (if applicable)**

- Start typing,
- Results ropdown appears
- navigate using the keyboard's arrows
- try to continue typing / changing the input text

**What do you use to build your app?. Please specify the version**
Webpack

**Angular version:** 4.3.3

**ngx-chips version:** 1.5.3

**Browser:** all

**Comment by Gbuomprisco** [comment]
Hi, I get what you mean but as described in the issue I am not working on new features

**Comment by kadosh1000** [comment]
In my opinion this is a bug and not a feature request (as mentioned in the issue). This is a simple UX of this kind of field that is currently missing.

**Comment by Gbuomprisco** [comment]
I understand that you prefer the other way, but it's a simple UX difference, not something malfunctioning. I'd accept PRs if you are interested

**Comment by Danieltamir** [comment]
Any updates regarding this behavior?

**Comment by tomavic** [comment]
No Update yet!! I will have to make a PR by myself.
