### ISSUE TITLE
please update the npm and `create custom theme` page

### ISSUE THREAD

**Issue by EnslavedEagle** [Gbuomprisco/ngx-chips#549]
The project's NPM page hasn't been updated with the latest package name (the old one doesn't even compile in Angular 4.0.0). Also, the [create a custom theme](https://github.com/gbuomprisco/ngx-chips/blob/master/docs/custom-themes.md) page is outdated and shows a wrong path to the Sass folders inside node_modules directory.

Should be:
`@import "~ngx-chips/dist/modules/core/styles/core/_core.scss";`

Is now:
`@import "~node_modules/ng2-tag-input/dist/modules/core/styles/core/_core.scss";`

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] support request/question
```

**Comment by Gbuomprisco** [comment]
Hi @EnslavedEagle, the npm page is a completely different one because one cannot change the name of a npm package. So the two are two different packages. I deprecated ng2-tag-input so users will receive a warning when trying to install it.
