### ISSUE TITLE
Unexpected behaviour when bundling with Webpack

### ISSUE THREAD

**Issue by pablogarciamiranda** [Gbuomprisco/ngx-chips#552]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When i am bundling everything in production mode, the component seems to not apply in a right way the styles.
![](https://i.imgur.com/foP34qg.png)

**Expected behavior**

In development mode it works perfectly
![](https://i.imgur.com/PxHpjbW.png)

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Webpack

**Angular version:** 

Angular 4.3.6

**ngx-chips version:**

ngx-chips 1.5.3

**Browser:**

All

Should i do something special in order to make it compatible with webpack? My script to bundle it is the following:
```
  "scripts": {
    "start": "node ./bin/www",
    "build": "del-cli public/js/app && webpack --config webpack.config.dev.js --progress --profile --watch",
    "build:prod": "del-cli public/js/app && ngc -p tsconfig.aot.json && ngc -p tsconfig.aot.json && webpack --config webpack.config.prod.js --progress --profile --bail && del-cli 'public/js/app/**/*.js' 'public/js/app/**/*.js.map' '!public/js/app/bundle.js' '!public/js/app/*.chunk.js' 'assets/app/**/*.ngfactory.ts' 'assets/app/**/*.shim.ts' 'assets/app/**/*.ngsummary.json' 'assets/app/**/*.ngstyle.ts'"
  },
```

**Comment by AustinHatem** [comment]
I am having this same problem.

**Comment by pablogarciamiranda** [comment]
@Gbuomprisco do you know something about this?

**Comment by Gbuomprisco** [comment]
Hi @pablogarciamiranda,

unfortunately I haven't had time to investigate this yet

**Comment by pablogarciamiranda** [comment]
@Gbuomprisco i am not using angular-cli, i am using instead webpack to bundle everything. Hope you fix it soon. Best regards

**Comment by pablogarciamiranda** [comment]
@Gbuomprisco any update?

**Comment by Gbuomprisco** [comment]
closing as this should be fixed?
