### ISSUE TITLE
The context ('this') is lost

### ISSUE THREAD

**Issue by jordymeow** [Gbuomprisco/ngx-chips#554]
With autocompleteObservable:

`<tag-input-dropdown [autocompleteObservable]="getObservableCollections"></tag-input-dropdown>`

And also onAdding:

`<tag-input [ngModel]="myCollections" [onAdding]="onAdding">`

I lost the context of my component:

```
  onAdding(tag: any): Observable<any> {
    console.log(this)
    return Observable.of(tag).filter(() => false)
  }

  getObservableCollections() {
    console.log(this)
    return Observable.of([])
  }
```

The 'this' is actually related to tag-input. I have no idea if it's a bug, or if it's normal and I am missing something. I have checked the examples and it seems like I should be able to have access to my component but it is not the case for me. Thanks for your help :)

**Comment by Gbuomprisco** [comment]
Hi @jordimeow, have a look at this ticket, it's the same issue https://github.com/Gbuomprisco/ngx-chips/issues/540

(remember to fill out the template next time)

**Comment by jordymeow** [comment]
Thanks for your answer @Gbuomprisco, and I have actually checked this issue before. But it doesn't apply to me, I am indeed using functions (look above, they are functions), but I don't get the proper "this". Or maybe there is something I really don't understand?

**Comment by Gbuomprisco** [comment]
if you check the examples real close, you can see the arrow function used for the methods. It's used to retain the scope of the class that defines the method

**Comment by jordymeow** [comment]
You are totally right, I didn't understand the usage of the arrow function earlier but thanks to you I got it :) I will close the issue and don't hesitate to remove it completely if needed.

**Comment by Celebes** [comment]
How did you resolve your problem? I try to set local variable to true in onAdding() but it gets ignored.
