### ISSUE TITLE
Performance Issue on scroll

### ISSUE THREAD

**Issue by immohitcoder** [Gbuomprisco/ngx-chips#555]
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: Hello, I'm using ngx-chips tag input and its functionality is working totally fine but when I'm scrolling to my listing on browser even if tag input have no value or just 1 value it starts hanging on scroll but when I comment tag input my application starts working smooth like normal.

**Current behavior** : Hanging on scroll

**Expected behavior** : Smoothness

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version** : angular-cli

**Angular version:** : 4

**ngx-chips version:** : latest

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by EvanWieland** [comment]
I'm feeling the same pain.

**Comment by Gbuomprisco** [comment]
Sorry I haven't experienced any performance issues so I am not sure how to help. Maybe post some code/repository I can check out.

**Comment by EvanWieland** [comment]
There probably isn't much that can be done, really. I've got a webpage with over 90 elements that all have ngx-chips forms. Just a lot for the DOM to juggle at one time I think.

**Comment by Gbuomprisco** [comment]
Does prod mode improve things?

**Comment by EvanWieland** [comment]
Like `ng build --prod`? I haven't tried that yet. Let me see what happens.

**Comment by EvanWieland** [comment]
It looks like the problem persists. There's some non-passive event listener that's locking up the thread. I'm getting a lot of violations in Chrome:

`[Violation] 'scroll' handler took 3462ms`
`[Violation] 'scroll' handler took 1095ms`
`[Violation] 'transitionend' handler took 273ms`
`[Violation] 'blur' handler took 371ms`
...

**Comment by Gbuomprisco** [comment]
I'd try ng build - -prod env=prod. I suspect the amount of events on the scroll event is the issue

**Comment by EvanWieland** [comment]
Still a lot of jank going on. I'm probably going to have to conjure up a work around for this one.

**Comment by Gbuomprisco** [comment]
I would try a virtual scrolling component that allows you to limit the amount of items in your page, and make sure you use ngIfs wherever appropriate too

**Comment by EvanWieland** [comment]
Yeah. What I'm doing now is showing a static list of tags that looks like ngx-chips, but only *ngIf show ngx-chips when a user clicks of the list to edit it. When the user is done editing, I  *ngIf hide ngx-chips again. Buttery smooth.

**Comment by Gbuomprisco** [comment]
Neat :)

**Comment by EvanWieland** [comment]
I don't want to speak for the OP, but you could probably close this issue if you wanted to. Since there are plenty of work-arounds.

**Comment by Gbuomprisco** [comment]
Agree :)
