### ISSUE TITLE
ngx-chips tag-input-dropdown not working with ionic

### ISSUE THREAD

**Issue by hussainanver52** [Gbuomprisco/ngx-chips#557]
hello everyone. I tried to use autocomplete tag input for my angular app, input tag is working fine, but when i add `<tag-input-dropdown>` element i can see inside my app the ui is distorted only in page where i have used the tag and also the dropdown is not coming properly

i tried to use the sample code also but still not working 
i have added sample code i used

```
<tag-input [ngModel]="talks">
        <tag-input-dropdown [autocompleteItems]="[{display: 'Item1', value: 0}, 'item2', 'item3']" [appendToBody]="false">
       </tag-input-dropdown>
    </tag-input>
```

any help would be appreciated

my ionic version is 

 ```
@ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : Linux 4.10

```

**Comment by Gbuomprisco** [comment]
Sorry I need a better explanation, can you please post images?

**Comment by hussainanver52** [comment]
![whatsapp image 2017-09-08 at 10 43 08 am](https://user-images.githubusercontent.com/4954234/30197032-ae3425ac-9482-11e7-9404-7dad546597a7.jpeg)
![whatsapp image 2017-09-08 at 10 43 08 am 1](https://user-images.githubusercontent.com/4954234/30197033-ae38ac9e-9482-11e7-822a-e4e8477260db.jpeg)

see the red color marked difference  im image 1 and 2 its when keyboard is opened.
i will list down the issues
1. when i try to go to the page where i have created the dropdown the header ui gets distorted and navigation doesnt seems to be working and when i click back button then only its going to that page, other pages dont have this issue

2. the dropdown is not searchable for ex if i type `an` in searchbox it should display text only which contains `an`

3. the search suggestion dropdown display conflict when keybord opens as given in image

4. and when i reopen the page the app dont respond for some time, additionally there is a delay in app open if i add the dropdown also 

can u help to sort out these issues.

Thank you for the reply

**Comment by jcbowyer** [comment]
I am not sure if you have tried the suggestion in another post for 

1.  add custom css
```
:host /deep/ ng2-dropdown-menu div {
  left: inherit !important;
  top: inherit !important;
}

```

2.  set   [appendToBody]="false" 

That said I have spent a week working with the control and it looks great on my desktop but for some reason does not show the dropdown on my iphone.   I really want to continue to use the control but I can't find examples or support of it being used successfully with ionic on mobile devices with the autocomplete.

**Comment by Gbuomprisco** [comment]
The component has never been designed for a mobile device. While I close all the bugs this will not be a priority.
