### ISSUE TITLE
Change title in live Demo for "An input which requires all tags to start with '@' @item "

### ISSUE THREAD

**Issue by usmandap** [Gbuomprisco/ngx-chips#558]
**I'm submitting an issue regarding the live demo of ngx chips. I am attaching a screenshot as you can see in title it says "An input which requires all tags to start with '@' @item" but it also needs the input to be end at "$" which is not mentioned in the title, also the preset tag containing "@item" does not contain "$" at the end if I am trying to do the same it does not allow me to do.
![screen shot 2017-09-09 at 10 20 15 am](https://user-images.githubusercontent.com/15185299/30237298-8c04e04a-9548-11e7-90ac-4a05bf48e46a.png)
.
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
open live demo [here](http://www.buompris.co/ng2-tag-input/)

**Expected behavior**
Since according to title of input it should only make sure the input starts with "@" but do not make it necessary to end on "$"

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
This has been addressed, thanks for reporting
