### ISSUE TITLE
this.engine.setProperty is not a function

### ISSUE THREAD

**Issue by mayurbais** [Gbuomprisco/ngx-chips#559]
**I'm submitting a ...** 
```
[* ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I follwed the exact same steps on readme to add tag input to my app. 
1.yarn add ngx-chips then import two modules, tagInputModule and BrowserAnimationsModule.
2. added this to my html, by looking at example under demo directory
```
    <tag-input [ngModel]="[]"
                       [theme]="'bootstrap'"
                       [separatorKeyCodes]="[32, 188]"
                       placeholder="add search tag"
                     >
            </tag-input>	
```

I can see a tag input added to page, but when I add a tag (press space bar) browser complains this : 
`this.engine.setProperty is not a function ` it triggers from [as updateRenderer](TagInputComponent.html:line no 20) and  [as updateRenderer] (TagRipple.html:line no 2)

Note : I searched git, and found somewhere that I should update all my dependencies. so ran "yarn upgrade"
So, everything is uptodate.

**What do you use to build your app?. Please specify the version**
@angular/cli: 1.4.1
node: 6.11.0
os: win32 x64
@angular/animations: 4.3.6
typescript: 2.3.4
yarn install v0.27.5
wwebpack -version 3.1.0

**ngx-chips version:** : "^1.5.3",

**Browser:**  checked in [  Chrome Version 60.0.3112.113 & IE :11 ]

**Comment by Gbuomprisco** [comment]
is it the same if you populate the array at all? Try ['item'] for instance

**Comment by mayurbais** [comment]
yes..[@item] was there from the copied code, the behavior is same with or without

**Comment by Gbuomprisco** [comment]
Do you have installed @angular/animations?

**Comment by mayurbais** [comment]
yes, have this in my package.json 
"@angular/animations": "^4.3.0",

**Comment by mayurbais** [comment]
Never mind, i deleted all npm cache..recreated angular-project, matched all the dependencies version to  dependencies in package.json of your project. 
and its working. I am not getting that ripple effect but at least no error.  will debug more. 
thanks for your time.
