### ISSUE TITLE
Removing tag with backspace does not trigger confirmation

### ISSUE THREAD

**Issue by adammedford** [Gbuomprisco/ngx-chips#562]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Removal confirmation is only triggered when clicking a tag's 'remove' button; tags can be removed by other means

**Expected behavior**

Pressing backspace to remove the tag would trigger the same confirmation as with clicking

**Minimal reproduction of the problem with instructions (if applicable)**

The last example on the demo page demonstrates a confirmation dialog that appears when adding or deleting tags. 

Select the input and hit backspace until the tags are cleared to verify lack of confirmation
Add a tag (confirmation required)
Click x icon/remove button (confirmation required)

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
can you provide what versions you're using?

**Comment by adammedford** [comment]
It is the last example on your live demo at http://www.buompris.co/ng2-tag-input/

**Comment by Gbuomprisco** [comment]
that's fairly outdated
