### ISSUE TITLE
No autocomplete when allowDupes in on

### ISSUE THREAD

**Issue by nirelbaz** [Gbuomprisco/ngx-chips#567]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When 'allowDupes' feature is on the autocompletion dropdown is not appearing.

**Expected behavior**

Autocompletion should appear and show me all the items, even the items I already used.

**Minimal reproduction of the problem with instructions (if applicable)**

```
<tag-input [formControl]="formControl"
               [editable]="editable"
               [allowDupes]="true">

      <tag-input-dropdown [autocompleteItems]="options"></tag-input-dropdown>
</tag-input>
```
**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

4.2.6

**ngx-chips version:**

1.5.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Possible solution:**
/modules/components/dropdown/tag-input-dropdown.component.ts, line 346:
            const hasValue: boolean = dupesAllowed ? **true** : this.tagInput.tags.some(tag => {
Should it be with false ?:
            const hasValue: boolean = dupesAllowed ? **false** : this.tagInput.tags.some(tag => {

Thanks

**Comment by megetron** [comment]
For my opinion, 
Autocomplete list should be open after a user type a minimum characters (for huge lists).

**Comment by Gbuomprisco** [comment]
@megetron there's a property for that

**Comment by megetron** [comment]
When you view the demo examples on "Tags accepting only items from an autocomplete" whenever you click on the input I get a dropdown that opens. 

I would except it to open only if you type a character. is this a bug? or by design?

Also it is a great feature to have it open only after minimum characters (please tell what the property for this)

**Comment by Gbuomprisco** [comment]
That example has the property showDropdownIfEmpty to true, so it does that behaviour. For the text length, use minimumTextLength. It's all documented, maybe go through the properties.

**Comment by conlaoch1** [comment]
Hi @Gbuomprisco , why was this topic closed? I really need dropdowns being shown when allowDupes = true.
I tested the proposed solution from @nirelbaz and it worked perfectly. Could you maybe implement the solution? Thanks a lot!
