### ISSUE TITLE
autocomplete with multiple matches

### ISSUE THREAD

**Issue by megetron** [Gbuomprisco/ngx-chips#569]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question
```

Hey there,
Can you force ngx-chips autocomplete to look for multiple matches per value?

E.g my application would receive a json file looks like this:
```
"{cities: [{name: 'new york', alias_names: ['big apple','nyc', 'nw york', 'new york']},{name:'california', alias_names: ['cali', 'california', 'ca']]}
]}"
```

So, I would like to display the name of the city if there is an autocomplete for one of this aliases.

My old code used jquery with bloodhound and typeahead: https://twitter.github.io/typeahead.js/examples/

But looking something more sophisticated to allow multiple cities to get selected instead of one.

appreciate any feedback.

**Comment by Gbuomprisco** [comment]
You should be writing your own matching function. From the documentation:
```
matchingFn - [?matchingFn(value: string, target: TagModel): boolean]

Use this property if you are not happy with the default matching and want to provide your own implementation. The first value is the value of the input text, the second value corresponds to the value of each autocomplete item passed to the component
```

**Comment by megetron** [comment]
Thanks for the quick reply. I definitely going to try it.
