### ISSUE TITLE
Jumps over 5 items when using up/down arrows in tag-input-dropdown (ngx-chips)

### ISSUE THREAD

**Issue by vorodefdm** [Gbuomprisco/ngx-chips#573]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When I try to move in tag-input-dropdown by Up/Down arrows, it doesn't move consequently, it jumps over 5 items.

**Expected behavior**

It moves consequently

**Minimal reproduction of the problem with instructions (if applicable)**

https://prnt.sc/gqt2ak

**What do you use to build your app?. Please specify the version**

angular-cli 1.4.1

**Angular version:** 

4.6.2

**ngx-chips version:**

Current

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by abuzakaria** [comment]
+1

**Comment by hsuanweifu** [comment]
+1 from testing it. The number of items being jumped over seem to be related to the number of characters in the input field.

**Comment by bennylut** [comment]
+1

**Comment by dudzikmichal** [comment]
+1

**Comment by Gbuomprisco** [comment]
can you try v 1.8.0?

**Comment by Gbuomprisco** [comment]
cool :)

**Comment by Gbuomprisco** [comment]
Sorry I don't think there is any work around for it.

**Comment by Gbuomprisco** [comment]
It's a change done in ng2-material-dropdown which is a dependency. You may try to force install the latest version of that package, I'm not sure though which one will be used
