### ISSUE TITLE
NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by gmattworld** [Gbuomprisco/ngx-chips#574]
I am trying to use tag input in an angular 4 project using visual studio SPA and the error below is what I get after importing TagImputModule and BrowserAnimationsModule

NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined

This is how my **app.module.shared.ts** look like

_import { TagInputModule } from 'ngx-chips';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
@NgModule({
    declarations: [
    ],
    imports: [
		TagInputModule,
		BrowserAnimationsModule
	],
	providers: []
})
export class AppModuleShared {
}_

I've removed unneccessary codes...

Please help...

**Comment by Gbuomprisco** [comment]
Hi @gmattworld can you check version 1.5.7? Thanks
