### ISSUE TITLE
Unfocus doesn't work in bootstrap modal

### ISSUE THREAD

**Issue by kminhtri** [Gbuomprisco/ngx-chips#575]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When we integrate a tag input in a bootstrap modal, the unfocus of the input doesn't close the autocomplete dropdown.

**Expected behavior**

Close correctly the dropdown autocomplete when unfocus the input.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

angular 4.3

**ngx-chips version:**

the lastest : 1.5.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

on Chrome, Safari

**Comment by kminhtri** [comment]
Major help :)

**Comment by Gbuomprisco** [comment]
I am not sure what the issue is, but if this only happens in the Bootstrap modal, I am inclined to think the issue is there as it may be preventing events. If you add a plunkr I'll investigate more
