### ISSUE TITLE
Problem with non-English characters

### ISSUE THREAD

**Issue by insanehong** [Gbuomprisco/ngx-chips#576]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I get this error when input with non-english characters"
I used   [separatorKeyCodes]="[32, 188]" 

but  Press twice to operate normally with korean'

ex) https://youtu.be/w_9ATgtQbU8
 

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Webpack 2.6.1

**Angular version:** 

4.4.4

**ngx-chips version:**

v1.5.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome  61.0.3163.100

**Comment by Gbuomprisco** [comment]
Try using separatorKey attribute instead
