### ISSUE TITLE
no dropdown items !

### ISSUE THREAD

**Issue by OdaiTu** [Gbuomprisco/ngx-chips#578]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

![image](https://user-images.githubusercontent.com/12837840/31574008-1615681c-b0cf-11e7-8c5d-d3d13ec08c25.png)

**Expected behavior**

show dropdown with items

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

4.4.4

**ngx-chips version:**

1.5.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hsuanweifu** [comment]
@OdaiTu you should show your code.

**Comment by OdaiTu** [comment]
@hsuanweifu  this error comes after updated to angular 4 and use your latest version but not i solved it by adding [displayBy] to dropdown menu
thank you !
