### ISSUE TITLE
ERROR TypeError: Cannot read property 'readonly' of undefined

### ISSUE THREAD

**Issue by oliwin** [Gbuomprisco/ngx-chips#579]
https://stackoverflow.com/questions/46790349/how-to-fix-error-in-tag-input-component

**Comment by jcbowyer** [comment]
I am receiving a similar error.  What was this solution to this?

**Comment by Gbuomprisco** [comment]
Post some of your code here

**Comment by jcbowyer** [comment]
The error is resolved.  I am not sure but it seems to be related to setting a selected value in ngmodel to a value that is not valid.   If I can reproduce better, I'll leave more information.  Thank you for the prompt response.
