### ISSUE TITLE
trimTags doesn't work with reactiveForm 

### ISSUE THREAD

**Issue by samirKamalGhoneim** [Gbuomprisco/ngx-chips#583]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

### when put white spaces in my input trimTags doesn't work as tag displayed with spaces an also in model
`{display: "value   anotherValue", value: "value   anotherValue"}`

**Expected behavior**

spaces should be removed 
{display: "valueanotherValue", value: "valueanotherValue",

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular/cli: 1.2.6
node: 8.2.1

**Angular version:** 

angular 4.2.4

**ngx-chips version:**

ngx-chips: 1.5.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome  Firefox  (i don't check another ones)

**Comment by Gbuomprisco** [comment]
trim means trimming spaces at start and end of the string, not anywhere
