### ISSUE TITLE
ngOutletContext removed in Angular v5

### ISSUE THREAD

**Issue by matthewerwin** [Gbuomprisco/ngx-chips#584]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**

When using Angular v5 with the library the ngx-chips templates result in an exception about unrecognized directive ngOutletContext

**Expected behavior**

Since the library is indicated as based on Angular v4 in the readme it would make sense to migrate to the ngTemplateOutletContext directive since ngOutletContext has been deprecated for some time.

**Minimal reproduction of the problem with instructions (if applicable)**

Update your Angular to v5 rc3 on an app that has the ngx-chips library in it.

**What do you use to build your app?. Please specify the version**

Angular-cli

**Angular version:** 

Angular v5 rc.3

**ngx-chips version:**

Latest (built off of /master branch)

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
PR merged, will publish asap

**Comment by DanialV** [comment]
@Gbuomprisco
I update my project to angular 5 today and got this error
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'
when you will update?

**Comment by Anoop-Goudar** [comment]
+1

**Comment by danejur** [comment]
As of 1.5.11, this issue appears to be fixed.
