### ISSUE TITLE
How prevent keyboard from opening when using autocomplete items only

### ISSUE THREAD

**Issue by Rainyer** [Gbuomprisco/ngx-chips#586]
First of all thanks for the awesome plugin,i would like to know if is there any config to block the keyboard, i need the input to behave like a dropdown and prevent user typing, it would be perfect because im already using  [onlyFromAutocomplete] property and does not make sense for the keyboard to pop up and hide the options.

Thanks in advance.

**Comment by Gbuomprisco** [comment]
Sorry it's not possible as it's not the aim of the component to be a dropdown

**Comment by Rainyer** [comment]
All right. Thanks for your time anyways.
