### ISSUE TITLE
minimumTextLength being ignored

### ISSUE THREAD

**Issue by chanm003** [Gbuomprisco/ngx-chips#587]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

minimumTextLength set to 3, but tagInputDropdown appears as soon as first character is typed.   autoCompleteObservable is also invoked.

**Expected behavior**

tagInputDropdown should not appear until third character is typed.   autoCompleteObservable should not be invoked until third character is typed

**Minimal reproduction of the problem with instructions (if applicable)**

```
<tag-input class="form-control" formControlName="items" [maxItems]="1" [ripple]="false" [theme]="'bootstrap'" [secondaryPlaceholder]="'Search in Directory'"
        [onlyFromAutocomplete]="true" [onTextChangeDebounce]="250"  >
        <tag-input-dropdown [autocompleteObservable]="getMatchingPeople" [minimumTextLength]="3" [identifyBy]="'Id'" [displayBy]="'Title'">
          <ng-template let-item="item" let-index="index">
            {{ item.Title }}
          </ng-template>
       </tag-input-dropdown>
</tag-input>
```

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

4.0.0

**ngx-chips version:**

1.5.3

**Browser:** 
Chrome 61.0.3163.100

**Comment by Gbuomprisco** [comment]
Hi @chanm003,

can you check version 1.5.5? Thanks!

**Comment by chanm003** [comment]
@Gbuomprisco

Unable to check 1.5.5 at this time.   I upgraded to Angular 5.0.0.  I also upgraded Rxjs to 5.5.2.

Now the autocomplete doesn't work at all.   #608

**Comment by chanm003** [comment]
Yes, 1.5.5 seems to respect the minimimTextLength. Thanks
