### ISSUE TITLE
TagInputDropdown Recalculate Position

### ISSUE THREAD

**Issue by seanmt13** [Gbuomprisco/ngx-chips#588]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question
```
**Current behavior**
I have ngx-chips in a mdb-bootstrap modal. The position of the TagInputDropdown changes when i activate the modal. So my autocomplete dropdown is not positioned correctly. 

```
<div class="col-md-6">
 <tag-input [onlyFromAutocomplete]="true" [(ngModel)]="tag" theme='bootstrap' name="first">
      <tag-input-dropdown #test [showDropdownIfEmpty]="false [autocompleteItems]="productDepartmentOptions" [appendToBody]="false">
          </tag-input-dropdown>
 </tag-input>
</div>
```

I am not sure if this is the right way to do this but in my component i have tried the following

`  @ViewChild('test') test:TagInputDropdown;`

Then in my html I added the #test to the <tag-input> see above. When i call the function to display the modal i also call my test function that calls

```
testPosition(){
    console.log(this.test);
    this.test.updatePosition();
  }
```
it doesn't seem to actually update the position.

**Expected behavior**
I would expect there is some way to call and recalculate the TagInputDropdown position? I can't really use offset as that will only work for one screen. 

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
4.0

**ngx-chips version:**
1.5.3

**Browser:** 
Chrome, Edge, Firefox

**Comment by seanmt13** [comment]
So this is an issue with ng2-dropdown-menu while it would be nice to be able to use [appendToBody]="false" and have it position correctly. Or have to ability to have it recalculate it's position.  You can get around this by creating a style sheet and linking to it from the index.html 

.ng2-dropdown-menu{
    z-index: 9999 !important
}

**Comment by rysilva** [comment]
Is there any reason why we couldn't set the <tag-input> component to `position:relative` so that the dropdown can be absolutely positioned relative to the component itself? The way it works now it seems to be positioned relative to the top of the document, so if you have any other relative positioned elements you're forced to use appendToBody=true because the positioning numbers will be wrong.
