### ISSUE TITLE
esc button to close the dropdown

### ISSUE THREAD

**Issue by OdaiTu** [Gbuomprisco/ngx-chips#589]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

**Expected behavior**

when press on ESC button close the dropdown list

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

4.2.4

**ngx-chips version:**

last version
**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, this is being shipped with version 1.5.7

**Comment by OdaiTu** [comment]
@Gbuomprisco  waiting bro :)

**Comment by Gbuomprisco** [comment]
The version is out already :) get the latest one

**Comment by OdaiTu** [comment]
Thanks
