### ISSUE TITLE
How to remove an item tag without selecting it on single backspace click?? Can you help me with that ??

### ISSUE THREAD

**Issue by denis0110** [Gbuomprisco/ngx-chips#592]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

It does not remove an item on single backspace click event but just selects that item and remove that after another click event of backspace.

**Expected behavior**

It should remove an item on single backspace click event.

**Minimal reproduction of the problem with instructions (if applicable)**

1) Add an item tag by giving input.
2) Try to remove that item by using backspace clicked once

**What do you use to build your app?. Please specify the version**

angular-cli <1.3.2>

**Angular version:** 

4.2.0

**ngx-chips version:**

1.5.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
Is the input focused while you hit backspace? The tag will only get removed if it's focused

**Comment by denis0110** [comment]
Yup

The issue is that I have to hit twice the backspace key for removing a tag..

**Comment by Gbuomprisco** [comment]
Hi @denis0110, I cannot reproduce this. Can you provide a video?
