### ISSUE TITLE
Add new tag only once when Observable is a complex json object

### ISSUE THREAD

**Issue by trystesire** [Gbuomprisco/ngx-chips#595]
I'm submitting a 

[x ] bug report
[ ] support request/question

When I used the example of Observable, it works fine. However if I change the code to return 2 properties from the json response as an object. The dropdown only open for the first time I enter a chips, then it doesn't open anymore.

I believe the dropdown opens and closes very quickly as I see a glitch.
Here is my code modification of the example : 

 public requestAutocompleteItems = (text: string): Observable<Response> => {
    url = 'https://api.github.com/search/repositories?q=${text}';
    return this.http
        .get(url)
        .map(data => data.json().items.map(item => 
           { 
          return {
             Title : 
            item.full_name, 
            Email : item.full_name}; }  
}
));
};
After this change, I can only add one tag. All others attempt, the dropdown doesn't open. However queries are still fired.

Expected behavior
We should be able to add as many tags as complex object as we want

angular-cli, angular.material.io Stepper 

**Angular version: 4.4.3

**ngx-chips version: 1.5.3

**Browser:** Firefox 56, IE 11

**Comment by Gbuomprisco** [comment]
What parameters are you using for displayBy and identifyBy? Maybe paste some of your template
