### ISSUE TITLE
Property 'disabled' does not exist on type 'TagInputComponent'

### ISSUE THREAD

**Issue by eslammahgoub** [Gbuomprisco/ngx-chips#600]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
angular-cli ng build --aot --prod results in ::
in node_modules/ngx-chips/dist/modules/components/tag-input/tag-input.template.html (13,6): Property 'disabled' does not exist on type 'TagInputComponent'.

**Expected behavior**
successful build

**Minimal reproduction of the problem with instructions (if applicable)**
ng build --aot --prod

**What do you use to build your app?. Please specify the version**
```
        "@angular/animations": "^4.4.4",
        "@angular/cdk": "2.0.0-beta.8",
        "@angular/common": "^4.4.4",
        "@angular/compiler": "^4.4.4",
        "@angular/core": "^4.4.4",
        "@angular/flex-layout": "2.0.0-beta.9",
        "@angular/forms": "^4.4.4",
        "@angular/http": "^4.4.4",
        "@angular/material": "2.0.0-beta.8",
        "@angular/platform-browser": "^4.4.4",
        "@angular/platform-browser-dynamic": "^4.4.4",
        "@angular/platform-server": "^4.4.4",
        "@angular/router": "^4.4.4",
        "@types/core-js": "^0.9.43",
        "@types/d3": "^4.10.1",
```

**Angular version:** 
``` "@angular/core": "^4.4.4" ```

**ngx-chips version:**
      ```  "ngx-chips": "1.5.7" ```

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Quick Solution:**
``` Revert ngx-chips to v1.5.3 ```

**Comment by Gbuomprisco** [comment]
Hi, please use the property disable instead of disabled now

**Comment by eslammahgoub** [comment]
I didn't use it at all in my code. is it required to put disabled in tag input component?

**Comment by Gbuomprisco** [comment]
No sorry, it was a property still being referenced somewhere. Will be fixed by https://github.com/Gbuomprisco/ngx-chips/pull/601/files

**Comment by Gbuomprisco** [comment]
can you try the latest version?

**Comment by eslammahgoub** [comment]
yes it works Thkx :thumbsup:
