### ISSUE TITLE
property issue after 1.5.9

### ISSUE THREAD

**Issue by vincent-cm** [Gbuomprisco/ngx-chips#604]
[at-loader] Checking finished with 2 errors
[at-loader] ./compiled/node_modules/ngx-chips/dist/modules/components/tag-input/tag-input.ngfactory.ts:259:32 
    TS2551: Property 'disabled' does not exist on type 'TagInputComponent'. Did you mean 'disable'? 
using typescript 2.6.1 and angular 4

**Comment by Gbuomprisco** [comment]
Use 'disable' now
