### ISSUE TITLE
First operator not imported and fails in onAdding

### ISSUE THREAD

**Issue by thaoula** [Gbuomprisco/ngx-chips#606]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When using the onAdding method and successfully returning an observable. The code in the following function fails

```
    TagInputComponent.prototype.onAddingRequested = function (fromAutocomplete, tag, index) {
        var _this = this;
        if (!tag) {
            return;
        }
        var subscribeFn = function (model) {
            return _this.addItem(fromAutocomplete, model, index);
        };
        this.onAdding ?
            this.onAdding(tag)
                **.first()**
                .subscribe(subscribeFn) : subscribeFn(tag);
```
Resulting in this error -
TypeError: this.onAdding(...).first is not a function

Please import the rxjs'First' operator.

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

1. add chips components.
2. configure onAdding callback
3. return an observable
4. get error

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

Angular 4.4.6

**ngx-chips version:**

1.5.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Should be fixed with 1.5.10 :)
