### ISSUE TITLE
Lettable Operators support

### ISSUE THREAD

**Issue by hudzenko** [Gbuomprisco/ngx-chips#607]
Please provide Lettable Operators support.

I use last 1.5.9 v. and [this](https://github.com/Gbuomprisco/ngx-chips/issues/484) issue is still existing.
To work without an error:
```
ERROR TypeError: this.tagInput.onTextChange.debounceTime is not a function
 ...
```
I have to make an additional imports by myself:
```
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/debounceTime';
```
I have just upgraded my app to Angular 5 and I am going to remove all operators like: `import 'rxjs/add/operator/...';` and use [Lettable Operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md) but I still want to use ngx-chips.

So my issue is fixing that and make ngx-chips up to date, because I really like this library and it is very comfortable in use. Thanks!

**Comment by maxkorz** [comment]
+1. Also, for some reason I have to import
```ts
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/first';
import 'rxjs/add/operator/filter';
```
without `'rxjs/add/operator/map'` (I don't import it anywhere else)

**Comment by Gbuomprisco** [comment]
For some reason = I forgot to add them to one of the files :)

**Comment by Gbuomprisco** [comment]
HI, in v 1.5.10 I import first too, which should be the only one not imported. Can you guys confirm?

**Comment by akkaradej** [comment]
I get the error in v1.5.10
`this.tagInput.onTextChange.asObservable(...).debounceTime is not a function`

**Comment by Gbuomprisco** [comment]
What rxjs version are you using?

**Comment by GitHubish** [comment]
I have the same problem with v1.5.11 and Angular 5, AngularCli 1.5.2 and Rxjs 5.5.2)

**Comment by Gbuomprisco** [comment]
Rx 5.5.x is definitely not supported at this time

**Comment by j2d2** [comment]
Works for me with RxJS 5.5.2 when I added to the component:
```javascript
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/filter';
```

Thanks to @Gbuomprisco for this great lib!

**Comment by hspier** [comment]
@Gbuomprisco Any estimates when Rx 5.5 will be supported?
