### ISSUE TITLE
onTagEdited does not bind new value to event function

### ISSUE THREAD

**Issue by wenderjean** [Gbuomprisco/ngx-chips#609]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When you set a function to `onTagEdited` event and try to manipulate the model at the same `fn` you'll realize that the new value is not bind in the variable.

Note: The new value is actually bind but after the event function execution.

**Expected behavior**

I'd expect that the list set in `ngModel` be updated inside my `onTagEdited` function.

**Minimal reproduction of the problem with instructions (if applicable)**

To reproduce this problem you can run the `demo`, put a `debugger` or even a `console.log` inside the function `onTagEdited` in `home.ts:87` and try to edit a tag, when debugger stop, visualize the attribute `items`, you'll see the old value instead of new one set in collection.

**What do you use to build your app?. Please specify the version**

`angular-cli`

**Angular version:** 

`4.4.6`

**ngx-chips version:**

`1.5.3`

Note: `I tried with the `master` version as well.`

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

`Chrome`

**Comment by Gbuomprisco** [comment]
If you are trying to edit an item from an output, then it's not possible as it's not meant for that. If you want to edit a tag before it is added to the model use onAdding

**Comment by wenderjean** [comment]
@Gbuomprisco I don't want to edit a tag before it is added but instead use the edit functionality already available in component, the problem is that the behavior for `onAdd` and `onTagEdited` is different, in `onAdd` I can perform some verifications in tags but in `onTagEdited` I can't because the new value is not set in model, In fact I can if I put a `setTimeout` inside `onTagEdited` function before try to use values set on model.

I really want to allow my user to edit its tags, that's the reason I can't simple use `onAdding`, but I need, also, to perform the same verification I did when adding, that new value placed by user.
