### ISSUE TITLE
Failed to execute 'animate' on 'Element': Partial keyframes are not supported

### ISSUE THREAD

**Issue by bmunna** [Gbuomprisco/ngx-chips#610]
Getting this Below error, not sure what causing. Its shows when selecting value from dropdown

version :
    "ngx-chips": "^1.5.8",

```
 <div class="formfieldsControl flight-number">
        <tag-input  formControlName="FlightsNumber" [placeholder]="'Flights'" [modelAsStrings]="true" [secondaryPlaceholder]="'Flights number and range'" [maxItems]='5' [onlyFromAutocomplete]="true">
            <tag-input-dropdown [minimumTextLength]='3' [limitItemsTo]='4' [showDropdownIfEmpty]="true" [showDropdownIfEmpty]="true" [autocompleteItems]="FlightNumber">
            </tag-input-dropdown>
        </tag-input>
        </div>



```

Error:
```
browser.es5.js:4670 Invalid keyframe value for property height: -16px

core.es5.js:1020 ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
```
Please someone help me to fix this issue :(

**Comment by bmunna** [comment]
tried with latest 1.5.9 too getting same issue, but if i use older version 1.4.3 not getting issue but older version 1.4.3 throw error on AOT (NgModule import issue) Please Help me fix this issue. Where am i doing wrong ?

**Comment by Gbuomprisco** [comment]
Try removing all your styles and check if the issue persists. Please read and use the template next time you open an issue, I normally close tickets without it

**Comment by bmunna** [comment]
@Gbuomprisco thanks keeping the question open, removed all styles and removed animation [animationDuration]="{enter: '0ms', leave: '0ms'}" too but still getting the error.

**Comment by Gbuomprisco** [comment]
Try using @disabled, Google it for correct usage

**Comment by bmunna** [comment]
tried both technic [@.disabled] and  @HostBinding('@.disabled') but no luck :(

**Comment by bmunna** [comment]
"@angular/animations": "^4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "~4.4.4",
    "@angular/compiler": "~4.4.4",
    "@angular/core": "~4.4.4",
    "@angular/flex-layout": "^2.0.0-beta.9",
    "@angular/forms": "~4.4.4",
    "@angular/http": "~4.4.4",


 "@angular/compiler-cli": "~4.4.4",
    "@compodoc/compodoc": "^1.0.0-beta.15",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/node": "^7.0.39",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.16",

**Comment by Gbuomprisco** [comment]
SOrry I am really not sure about this :(
