### ISSUE TITLE
TagModel ngx-chips@1.5.9

### ISSUE THREAD

**Issue by FARHANE** [Gbuomprisco/ngx-chips#611]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Cann not find tagModule

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
TagModel?

**Comment by Gbuomprisco** [comment]
Please add a stack trace and more information, closing for now

**Comment by FARHANE** [comment]
I can not find the type TagModel like in this example

```
public onAdding(tag: TagModel): Observable<TagModel> {
    const confirm = window.confirm('Do you really want to add this tag?');
    return Observable
        .of(tag)
        .filter(() => confirm);
}
```

**Comment by Gbuomprisco** [comment]
You don't need to use TagModel, what you need it's either an object or a string depending on what you pass to the ngmodel
