### ISSUE TITLE
How to update input tag model without losing other fields

### ISSUE THREAD

**Issue by Redrih** [Gbuomprisco/ngx-chips#614]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I need to save input tags in db in format ID: Number, Text: Tag_value, so I'm using this component:
<tag-input [(ngModel)]="myCollection" [identifyBy]="'id'" [displayBy]="'name'">
and my collection is something like:

 myCollection= [{id: 1, name: 'some text'}, {id: 2, name: 'Some other text'}];

So adding, showing already saved items and removing is working perfectly.

But when user are edited already created tag, id value are changing to text, and of course it cannot be updated in db, because of missing the Id value, if i don't specifyidentifyBy value field Id doesnt provided at all . Can i somehow solve this problem?

P.S. I could try subscribe to onTagEdited event, and make some workaround, but unfortunately event got the new value and i cannot track the changes

**Expected behavior**

When editing tag should change only [displayBy[ field and dont touch other fields

**Minimal reproduction of the problem with instructions (if applicable)**

1) Use the component like this: <tag-input [(ngModel)]="myCollection" [identifyBy]="'id'" [displayBy]="'name'"> and model like:  myCollection= [{id: 1, name: 'some text'}, {id: 2, name: 'Some other text'}];
2) Change some tag which already created
Current behavior: Id value changed to text value
Expected behavior: Id value didn't change

**What do you use to build your app?. Please specify the version**
angular cli

**Angular version:** 
5

**ngx-chips version:**
1.5.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
Hi @Redrih, can you try v 1.5.10? Now, if the field displayBy and identifyBy are different, identifyBy will be kept intact :)
