### ISSUE TITLE
Minimal Theme is not minimal

### ISSUE THREAD

**Issue by jordymeow** [Gbuomprisco/ngx-chips#616]
Hi guys,

It would be great to have a real minimal theme, which does nothing. I am not using Bootstrap, and this component has been really made for it, even the Minimal Theme. It would be awesome to have a theme that does **nothing**. This would be possible? Of course, I could make it myself but I think a lot of developers would enjoy having something raw. If there is an easy way to do this, I would love to know as well. Except that, this component is really awesome. So thanks :)

**Comment by Gbuomprisco** [comment]
Hi @jordymeow, thanks for the compliments!
It would be possible, yes, but the mixins provides should make it fairly easy to create totally different themes too. Have you checked https://github.com/Gbuomprisco/ngx-chips/blob/master/docs/custom-themes.md?

The only issue with this is the usage of ::deep. At the moment I am not sure if there is a better way besides ng-deep. Either way, it would fairly easy to set up a new theme called 'none' (maybe?) as minimal stands for minimal design :)

**Comment by jordymeow** [comment]
I actually have looked at it before but... I don't use SASS in my project and prefer to keep it as light as possible. I don't even have a CSS file! So, I will hope for a totally empty theme :) Since we can actually use our own template within the tag-input I really expected that no style would be applied to it. If there weren't any styles, it would be awesome because we could create directly craft the template with elements based specific CSS frameworks easily. Would be clean and would look great in every case.
