### ISSUE TITLE
Can we mix tags with regular strings?

### ISSUE THREAD

**Issue by gandra** [Gbuomprisco/ngx-chips#617]
Hi!
First congratulation for this great work.

I am wondering if we can mix tags with regular strings like in this example?

![image](https://user-images.githubusercontent.com/1294812/33028047-0bbd0dc6-ce15-11e7-90ac-9f0872d1dc59.png)

**Comment by Gbuomprisco** [comment]
Hi and thanks. Sorry but what you are asking is not possible
