### ISSUE TITLE
Dropdown not showing any items  if the allowDupes is true

### ISSUE THREAD

**Issue by ShravanJoopally-xo** [Gbuomprisco/ngx-chips#618]
Dropdown not showing items when allowDupes is set to true.

Its because of the condition in getMatchingItems method of tag-input-dropdown.

in return statement it has  
return  _this.matchingFn(value, item) && hasValue === false;

it evaluates to true only when the   _this.matchingFn(value, item) is true and hasValue is false, in remaining scenarios it evaluates to false.

Fix could be
return  !hasvalue && _this.matchingFn(value, item);

as we are setting hasValue to true when allowDupes is true.

**Comment by Shravan-Joopally** [comment]
fixed in https://github.com/Gbuomprisco/ngx-chips/pull/619

**Comment by Gbuomprisco** [comment]
Hi thanks for the fix. Unfortunately I won't be able to merge until Sunday as I am away for work

**Comment by Gbuomprisco** [comment]
ngx-chips@1.5.11 released :)

**Comment by Shravan-Joopally** [comment]
@Gbuomprisco thanks :+1:
