### ISSUE TITLE
how to make add the item form dropdown autocomplete if i write the same tag but click enter

### ISSUE THREAD

**Issue by OdaiTu** [Gbuomprisco/ngx-chips#622]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

i write the same tag in the dropdown autocomplete and click enter but it add it like its a new one

**Expected behavior**

i want to add the item from dropdown when i press enter if the item i wrote it is the same in the dropdown

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

4.4

**ngx-chips version:**

1.5.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, that is not implemented at this time

**Comment by Shravan-Joopally** [comment]
Hi @OdaiTu ,
I also had same kind of requirement you can fix this by using below code

```
@ViewChild(TagInputComponent) tagInput: TagInputComponent;

ngAfterViewInit() {
        this.tagInput.inputForm.onKeydown.asObservable().
        subscribe(($event) => { this.inputKeyDown($event); });
}

inputKeyDown($event) {
        if ($event.keyCode === 13) {
            const dropdown = this.tagInput.dropdown.dropdown;
            const firstItem = dropdown.menu.items.first;
            if (firstItem) {
                firstItem.click();
            }
        }
}
```
