### ISSUE TITLE
How to trigger validation on submit ?

### ISSUE THREAD

**Issue by f5kumar** [Gbuomprisco/ngx-chips#624]
Sorry its not bug or feature request, But please help me on it.
I was trying a simple validatio. On submit i need to check chip, if it is empty need to show validation error. But not sure how to do on Ngxchip. 

Could you please tell me how to trigger validation on submit ? 

I tried something like this, setting isValid boolen true if value is empty and false if value is not empty.
But class applying only to tag-input, i want to apply this to <div> which is generate dynamically inside tag-input

**" [ngClass]="{'valid': !isValid, 'ng2-tag-input--invalid': isValid}"**

```
 <tag-input " [ngClass]="{'valid': !isValid, 'ng2-tag-input--invalid': isValid}"  formControlName="origin" [placeholder]="'Origin'" [modelAsStrings]="true" [secondaryPlaceholder]="placeholderOrgin"   [maxItems]='5' [onlyFromAutocomplete]="true">
             <tag-input-dropdown class="ng2-tag-input--invalid" [minimumTextLength]='2' [limitItemsTo]='3' [autocompleteItems]="listOfDep" [identifyBy]="'DeptCode'" [displayBy]="'DepDetails'"></tag-input-dropdown>
</tag-input>
```

**Comment by Gbuomprisco** [comment]
You should add validators to a form group which has the tag input as a form control.
