### ISSUE TITLE
Validation on from submit

### ISSUE THREAD

**Issue by sundaravadivel1980** [Gbuomprisco/ngx-chips#625]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I want to validate the chip field at the time of from submit, below is my field 

 <tag-input formControlName="Orgin" [placeholder]="'Orgin'" [modelAsStrings]="true" [secondaryPlaceholder]="placeholderOrgin"
                                    [maxItems]='5' [onlyFromAutocomplete]="true">
                                    <tag-input-dropdown [minimumTextLength]='2' [limitItemsTo]='3' [autocompleteItems]="listOfAirport" [identifyBy]="'AriportCode'" [displayBy]="'AirportDetails'">
                                    </tag-input-dropdown>
                                </tag-input>

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Chips are validated when the user inputs text, otherwise validate using a formGroup

**Comment by sundaravadivel1980** [comment]
Thanks, Can you provide example please?

**Comment by Gbuomprisco** [comment]
Check out angular's forms examples or the examples in the demo app of this repository. All forms that use ReactiveFormsModule work in the same way
