### ISSUE TITLE
How to style/change the remove icon?

### ISSUE THREAD

**Issue by resting** [Gbuomprisco/ngx-chips#626]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question
```

How do I style or remove icon? Its a svg now. How can I use my own image or svg?

**ngx-chips version:**
v1.5.3

**Comment by Gbuomprisco** [comment]
Sorry there's no way to configure it at the more
