### ISSUE TITLE
autocompleteItems with onlyFromAutocomplete only works for first tag 

### ISSUE THREAD

**Issue by paddy1205** [Gbuomprisco/ngx-chips#627]
In my case autoCompleteItems with onlyFromAutocomplete is working only for first tag.
it is not providing the dropdown suggestion from the list for next tags.

<tag-input [ngModel]="tags" name="input" [identifyBy]="'id'" [displayBy]="'name'" [onlyFromAutocomplete]="true" (onAdd)="onTagAdded($event)">
                  <tag-input-dropdown [autocompleteItems]="list" [displayBy]="'name'">
                </tag-input-dropdown>
           </tag-input>

No error but still the issue.

**Comment by Gbuomprisco** [comment]
You probably need to provide identifyBy as well. Please complete the template next time

**Comment by paddy1205** [comment]
Thank you.
