### ISSUE TITLE
Keep dropdown on the bottom and avoid the weird interaction

### ISSUE THREAD

**Issue by Globix** [Gbuomprisco/ngx-chips#628]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
I have a component that uses the tag input component with a dropdown and does the interaction of the gif.
https://gyazo.com/eb1f2e7e897e2a3c6745830f0b0a0a8d

The problem is that some options hide on the top and cannot be selected by click.

**Expected behavior**
There is some way to keep the dropdown on the bot of de tag-input?
I searched a solution and i found that maybe using [appendToBody]="false", but i've tried and don't worked.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
angular-cli: 1.5.0

**Angular version:** 
4.4.6

**ngx-chips version:**
1.5.3

**Browser:** 
Chrome Versión 62.0.3202.94

**Comment by yanbr01** [comment]
im also observing this

**Comment by lotsabackscatter** [comment]
I'm also observing this on ngx-chips 1.6.2, angular 5.1.2 and angular-cli version 1.6.3.

Haven't found a workaround yet...

**Comment by lotsabackscatter** [comment]
I'm also observing this on ngx-chips 1.6.2, angular 5.1.2 and angular-cli version 1.6.3.

Haven't found a workaround yet...

**Comment by ManicMapple** [comment]
I'm also observing this on ngx-chips 1.6.2, angular 4.4.3 and angular-cli version 1.3.0

Haven't found a workaround yet...

**Comment by kisonay** [comment]
I was able to overcome this with some custom CSS. I gave the dropdown a max-height of 200px which allows for 4 items visible and the rest scroll-able. this shorter height allows the dropdown to stay below the input.

**Comment by christianpbrubaker** [comment]
I have tried overriding with custom css to set the max-height and nothing that I've done appears to work. 
@kisonay, Any chance you can share your custom css that got this to work?

**Comment by christianpbrubaker** [comment]
I Finally got it sorted. I had to add the custom css to my global styles and not in the component that was using the control.

.ng2-dropdown-menu { height: 200px !important }

Hope this helps

**Comment by kisonay** [comment]
@christianpbrubaker yup, that is exactly what I did. Thanks for posting.

**Comment by Gbuomprisco** [comment]
Check out the option [dynamicUpdate] in version 1.7.5
