### ISSUE TITLE
Ngx-chips npm install does not have styles

### ISSUE THREAD

**Issue by kultigin** [Gbuomprisco/ngx-chips#635]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I can not find this folder in the installed ngx-chips node-modules folder. 
@import "~node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss";

Under /dist I have bundle.js. /dist and /modules are in the same level and under /modules/core/ there is no /styles folder. 

**Expected behavior**

I am trying to make custom theme work and I have changed my package.json from ng2-tag-input to ngx-chips which then exposed the above issue.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Angular, grunt, browserify and package.json

**Angular version:** 

^4.1.3

**ngx-chips version:**

1.6.1

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

not related

**Comment by Gbuomprisco** [comment]
Hi, follow https://github.com/Gbuomprisco/ngx-chips/issues/632
