### ISSUE TITLE
Using AutocompleteObservable tag-input-dropdown do not showup after select one tag/chip

### ISSUE THREAD

**Issue by rosskan** [Gbuomprisco/ngx-chips#638]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Using AutocompleteObservable tag-input-dropdown 
When i input without any tag/chip the tag-input-dropdown  show up.
After I select one from the dropdown and input some text, the AutocompleteObservable triggered and server response as usual, but the dropdown did not show up.

I do this in a bootstrap 4 modal

          ` <tag-input name="assignPost" [ngModel]="items" [displayBy]="'postCod'"
         (onBlur)="onInputBlurred($event)" 
          (onTextChange)="onTextChange($event)"
          (onFocus)="onInputFocused($event)"
          (onSelect)="onSelected($event)"
          (onRemove)="onItemRemoved($event)" 
          (onAdd)="onItemAdded($event)">`
` 
          <tag-input-dropdown [autocompleteObservable]='requestAutocompleteItems' [displayBy]="'postCod'" [minimumTextLength]="2" [appendToBody]="false" [showDropdownIfEmpty]="true"> 
              
          </tag-input-dropdown>
        </tag-input>`

**Expected behavior**

The dropdown show up after i added some tag/chip

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

"@angular/cli": "1.4.9",
  "@angular/compiler-cli": "^4.4.6",

**Angular version:** 

4.4.6

**ngx-chips version:**

1.6.1

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by Gbuomprisco** [comment]
Add identifyBy too

**Comment by rosskan** [comment]
Thanks. It works.
