### ISSUE TITLE
First element not focused when I am typing

### ISSUE THREAD

**Issue by abelardolg** [Gbuomprisco/ngx-chips#647]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When I type an item, a filtered list of items is showed. The first item doesn't gain the focus automatically. 

**Expected behavior**

To gain the focus the first item of the filtered list automatically.

**Minimal reproduction of the problem with instructions (if applicable)**

1) Populate with items your component.
2) Type an item contained at the list.
3) You will see that the first item is not focused automatically.

**What do you use to build your app?. Please specify the version**

The latest version of angular-cli at the writing.

**Angular version:** 

5

**ngx-chips version:**

The latest version of this component at the writing.

**Browser:** 

[all]

**Comment by misteio** [comment]
+1

**Comment by Gbuomprisco** [comment]
This is because the input form has still the browser's focus. The item should still be pressable when yo press enter, just make sure to add the option [focusFirstElement]

**Comment by Dineshkumar-kannan** [comment]
Hi. added [focusFirstElement]="true". But still not working.

 <tag-input formControlName="Codes" [disable]="disableControl"
                                    (onAdd)="onChang('A',$event)" (onRemove)="onChange('C',$event)"
                                    [displayBy]="'Desc'" [identifyBy]="'Code'" [onlyFromAutocomplete]="true"
                                    [allowDupes]="false">
                                   
                                    <tag-input-dropdown  [focusFirstElement]="true"
                                        [showDropdownIfEmpty]="true" [dynamicUpdate]="false"
                                        [appendToBody]="false" [autocompleteObservable]="CodeList"
                                        [displayBy]="'Desc'" [identifyBy]="'Code'">
                                        <ng-template let-item="item">                                            
                                            {{ item.Desc }}
                                        </ng-template>
                                    </tag-input-dropdown>
                                </tag-input>

In ts
-----
public CodeList = (text: string): Observable<Response> => {
    return this.getCodeList(text');
  }

  getCodeList(_searchText): Observable<any> {
   
    let param = {
      code: _searchText      
    };
    const relativeUri = apiUrl;
    return this.http.get(apiUrl).map(result => {
      return result;
    });
  }


Thanks,

**Comment by bartholomej** [comment]
Same here. Not working.
Same issue is here https://github.com/Gbuomprisco/ngx-chips/issues/815 and here https://github.com/Gbuomprisco/ngx-chips/issues/148 @Gbuomprisco
