### ISSUE TITLE
Impossible to return to the input field when you are navigating through the list with keyboard

### ISSUE THREAD

**Issue by abelardolg** [Gbuomprisco/ngx-chips#648]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

1) I type an item then the list is showed. 
2) When I am navigating through the list with the keyboard, I can't use it to return back to the input field. E.g.: if I press Shift+Tab then the next item is selected.

**Expected behavior**

When I press Shift+Tab then the input field gains the focus

**Minimal reproduction of the problem with instructions (if applicable)**

1) I type an item then the list is showed. 
2) When I am navigating through the list with the keyboard, and I can't use it to return back to the input field. If I press Shift+Tab then the next item is selected.

**What do you use to build your app?. Please specify the version**

angular-cli : the latest version at the writing.

**Angular version:** 

5.

**ngx-chips version:**

 The latest version at the writing.

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
It's not a bug, it's just never been implemented. I will have a look once all the bugs are closed.
