### ISSUE TITLE
When the return key is pressed the typed item is deleted

### ISSUE THREAD

**Issue by abelardolg** [Gbuomprisco/ngx-chips#649]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When I type an item contained at the list and I press the Return key, this inputted item is deleted.

**Expected behavior**

The inputted item should be tagged when I press the Return key.

**Minimal reproduction of the problem with instructions (if applicable)**

1) Write any item contained at the list.
2) Press Enter.
3) You will notice that the inputted item was deleted.

**What do you use to build your app?. Please specify the version**

The latest version of angular-cli at the writing.

**Angular version:** 

5

**ngx-chips version:**

The latest version at the writing.

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all.

**Comment by Gbuomprisco** [comment]
Do you have any validator firing?

**Comment by abelardolg** [comment]
Hi, @Gbuomprisco : No, I haven't any validator at that component.

**Comment by Gbuomprisco** [comment]
Post some of your code or better an online demo
