### ISSUE TITLE
onTouchedCallback is not a function error. Tag is showed twice.

### ISSUE THREAD

**Issue by abelardolg** [Gbuomprisco/ngx-chips#650]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

My code is composed by:

- a high-level component called "kg-bultos.component" 

- a low-level component called 'mytag-input' which embeds your 'tag-input' component directly.

My kg-bultos.component.HTML is:
``
<app-mytag-input
[setAllowDupes]="true"
[mySecondaryPlaceholder]="'Ejs.: 56.6 o 56,6'"
[isEditable]="true"
[textoRestriccion]="'Puede usar la \',\' o el \'.\' para los decimales. '"
[isKGBultos]="true"
[numBultos]="pesoBultos"
[totalKilos]="'Total kilos'"
[sumaPeso]="pesajeTotal"
[pesoMedio]="'Peso medio'"
[pesoMaximo]="maximoPeso"
[pesoMaximoStr]="'Peso máximo'"
[miTabIndex]="0"
[isExceedWeight]="pesajeExcedido"
(nuevoPeso)="calcularPesaje($event)">
</app-mytag-input>
``

My mytag-input.component.HTML is:

``
<tag-input  [allowDupes]="setAllowDupes"
            [placeholder]="''"
            [secondaryPlaceholder]="mySecondaryPlaceholder"
            [editable]='isEditable'
            theme='bootstrap'
            (onAdd)="textChange($event)" -> I changed 'onAdd' by 'onAdding' but this error remains.
            [tabIndex]="miTabIndex"
            [errorMessages]="errorMessages"
            [validators]="validators">
</tag-input>
``

When I insert a tag, this is showed twice 
![captura2](https://user-images.githubusercontent.com/22522883/34666242-9efc6d56-f463-11e7-9021-ee305cd95a43.PNG)
and at the moment, this error is showed:
![captura3](https://user-images.githubusercontent.com/22522883/34666256-b16c5a64-f463-11e7-9252-b9c607cafa84.PNG)

**Expected behavior**

Don't show twice the inputted value and don't show that error.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

The latest version of angular-cli.

**Angular version:** 

5 

**ngx-chips version:**

The latest version of this component at the writing.

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
You don't have an ngmodel or a form control

**Comment by Gbuomprisco** [comment]
You don't have an ngmodel or a form control
