### ISSUE TITLE
Unable to find styles in version 1.6.2 (latest)

### ISSUE THREAD

**Issue by ReemLamaa** [Gbuomprisco/ngx-chips#652]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I can't find the styles folder in the downloaded node module (version 1.6.2)

**Expected behavior**

I can customize the tags-input

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Angular-cli

**Angular version:** 

IT IS

**ngx-chips version:**

IT IS

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
There's a ticket for this already
