### ISSUE TITLE
IE11 (Internet explorer 11) and Edge issue - Enter key

### ISSUE THREAD

**Issue by vsm** [Gbuomprisco/ngx-chips#653]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
We are using "tag-input" element for handling tags. 

**Expected behavior**
This should add and remove tags. - Working fine in Chrome. but not in IE11 and Edge
Internet explorer 11

**Minimal reproduction of the problem with instructions (if applicable)**
Steps to reproduce in IE11 or Edge:
1) Write any text. press enter key - this is adding to the taglist and also submitting the form. From this user is not able to enter next consecutive tags

Click on the 'Enter a new tag' box and type 'Tag1' and press enter to commit the tag.  Once you hit enter, the Validate button will also be pressed. 

**What do you use to build your app?. Please specify the version**
 "@types/webpack": "3.8.1",
"html-webpack-plugin": "2.30.1",
"ngc-webpack": "3.2.0",
    "webpack": "3.10.0",
    "webpack-dev-middleware": "1.10.2",
    "webpack-dev-server": "2.9.7",
    "webpack-dll-bundles-plugin": "1.0.0-beta.5",
    "webpack-merge": "4.1.0",

**Angular version:** 
    "@angular/compiler-cli": "4.4.6",

**ngx-chips version:**
    "ngx-chips": "1.4.1",

**Browser:**
Internet Explorer 11 and Edge

**Comment by agam16** [comment]
is there any update to this. i am also facing this issue

**Comment by vsm** [comment]
Removed form.submit action. Moved submit function to submit button

**Comment by Gbuomprisco** [comment]
Thanks!

**Comment by vishwa1004** [comment]
hi,
ngx-chips drop down is not working in IE, but working in chrome.
Current Behavior : in input field if i type some thing it not showing any drop down and after entering something if hit enter then that field resetting that field
` <tag-input [ngModel]="item" [onlyFromAutocomplete]="true" (onRemove)="remove($event)" style="background-color: #fff; width:100%;"
                    placeholder="Search here"   secondaryPlaceholder="Search here">
                        <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="suggestions">
                            <ng-template let-item="item" let-index="index">
                                <p (click)="select(item)">{{ item.display }}</p>
                            </ng-template>
                        </tag-input-dropdown>
                    </tag-input>`

**Comment by prabhashust** [comment]
Please upgrade ngx-chips to the latest version ( 1.9.3).

**Comment by vishwa1004** [comment]
Yeah, Super Its working, thank you @prabhashust
