### ISSUE TITLE
[ngModel] not working 

### ISSUE THREAD

**Issue by otrifo** [Gbuomprisco/ngx-chips#660]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

 Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'tag-input'.

   <tag-input [ERROR ->][ngModel]="'item'">
        <tag-input-dropdown [autocompleteItems]="allFontsList">
        </tag-inp"): ng:///DynamicFormModule/FormFontSelectComponent.html@27:17
No provider for NgControl ("
      
      
      [ERROR ->]<tag-input [ngModel]="'item'">
        <tag-input-dropdown [autocompleteItems]="allFontsList">
      "): ng:///DynamicFormModule/FormFontSelectComponent.html@27:6

**Expected behavior**
ngModel not working and if I remove this there is another problem 
 this._onChangeCallback is not a function  

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
angular-cli 1.5.0

**Angular version:**
 5.2.0

**ngx-chips version:**
 1.6.3

**Browser:**  all

**Comment by Gbuomprisco** [comment]
It seems you don't import reactive forms module
