### ISSUE TITLE
how to show invalid text as simple text

### ISSUE THREAD

**Issue by na-le** [Gbuomprisco/ngx-chips#662]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**_Question:_**

I want to add validation on text with some requirements:
if the text is invalid - I should show it as simple text. but not to delete it
if there is invalid input I should throw an error
in the validator I should use a collection from the component

so, my questions are:
1. how can I show the text as simple when it invalid?
2. how can I throw an error? it doesn't work when I'm trying to use:
```
 public onValidationError(item) {
    console.log("invalid service " + item);
    this.serviceNameError.emit(item);
  }
```

3. I can't use any property of the component in the validator (like:
```
private serviceValidateAsync(control: FormControl): Promise<any> {
    return new Promise(resolve => {
      const value = control.value;
      const result: any = t!his.myCollection.includes(value)? {
        isInvalid: true
      } : null;

      setTimeout(() => {
        resolve(result);
      }, 1);
    });

```
I get an error that "can't find myCollection of undefined"

can you advice please?

**Current behavior**

I get an error that "can't find myCollection of undefined"

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
You're losing context when you call "this". You need to bind it to your class. Use an arrow function.
