### ISSUE TITLE
Tags and input box order

### ISSUE THREAD

**Issue by AndreyPanasenk-o** [Gbuomprisco/ngx-chips#669]
Hello.
I'm wondering if it's possible to add the option to change the order of selected tags and the input. For now the input is in the end and it will be good to have an option to move it to the beginning: the input box in the beginning and then selected tags are displayed.

Thank you.

**Comment by Gbuomprisco** [comment]
Hi, sorry but new options are not planned as the component is pretty fat already. You can try overriding the CSS instead?
