### ISSUE TITLE
How to make single items in dropdown un-selectable

### ISSUE THREAD

**Issue by Wealing** [Gbuomprisco/ngx-chips#672]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I get the dropdown items correctly

**Expected behavior**

I would like certain of those dropdown items to not be selectable.

**Minimal reproduction of the problem with instructions (if applicable)**
<tag-input
            [(ngModel)]="audiencePath"
            displayBy="name"
            identifyBy="id"
            [secondaryPlaceholder]="placeholder"
            (onAdd)="onAdd($event)"
            (onRemove)="onRemove($event)"
            class="d-inline-block"
            placeholder="" >
      <ng-template let-item="item">
        {{ item.name }} <i class="fa fa-chevron-right"></i>
      </ng-template>
      <tag-input-dropdown [autocompleteObservable]="requestAutocompleteItems"
                          displayBy="name"
                          identifyBy="id"
                          [appendToBody]="false"
                          placeholder="Select an audience"
                          [showDropdownIfEmpty]="true"
                          [keepOpen]="true"
                          [minimumTextLength]="0"
      >
        <ng-template let-item="item" let-index="index">
          {{ display(item)}}
        </ng-template>
      </tag-input-dropdown>
    </tag-input>

**What do you use to build your app?. Please specify the version**
angular cli 1.5

**Angular version:** 
5

**ngx-chips version:**

**Browser:** [ ]
this is tested on Chrome , haven't tested others

**Comment by Gbuomprisco** [comment]
Sorry I am not sure this is possible at all at this time... if you may be stop the propagation on click using the custom template, you could make it work
