### ISSUE TITLE
BUG: ERROR Argument of type 'undefined' is not assignable to parameter of type 'number'.

### ISSUE THREAD

**Issue by MoAsmar** [Gbuomprisco/ngx-chips#673]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

**Current behavior**
After upgrading my app to angular 5, the cli is showing the below error:
ERROR in node_modules\ngx-chips\dist\modules\components\tag-input\tag-input.template.html(7,6): : Argument of type 'undefined' is not assignable to parameter of type 'number'.

**Expected behavior**
is it working with angular latest versions ?

**Minimal reproduction of the problem with instructions (if applicable)**
Upgrade your project to angular 5 and try using the library.

**What do you use to build your app?. Please specify the version**
"@angular/cli": "^1.7.0"

**Angular version:** 
"@angular/animations": "^5.2.5",
"@angular/common": "^5.2.5",
"@angular/compiler": "^5.2.5",
"@angular/core": "^5.2.5",
"@angular/forms": "^5.2.5",
"@angular/http": "^5.2.5",
"@angular/platform-browser": "^5.2.5",
"@angular/platform-browser-dynamic": "^5.2.5",
"@angular/platform-server": "^5.2.5",
"@angular/router": "^5.2.5",


**ngx-chips version:**
"ngx-chips": "1.5.11"


**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Any

**Comment by pidompa** [comment]
Same here

**Comment by Gbuomprisco** [comment]
Try latest ngx chips

**Comment by MoAsmar** [comment]
@Gbuomprisco Latest ngx chips has another issue:
>  File to import not found or unreadable: ../../../../node_modules/ngx-chips/dist/modules/core/styles/core/_core.scss.

it does not add sass files to the module folder!

**Comment by pidompa** [comment]
My configuration, same issue

"@angular/animations": "5.2.1",
    "@angular/common": "5.2.1",
    "@angular/compiler": "5.2.1",
    "@angular/core": "5.2.1",
    "@angular/forms": "5.2.1",
    "@angular/http": "5.2.1",
    "@angular/platform-browser": "5.2.1",
    "@angular/platform-browser-dynamic": "5.2.1",
    "@angular/router": "5.2.1",

"ngx-chips": "1.6.4",

**Comment by MoAsmar** [comment]
@Gbuomprisco Do you have a fast solution for this? as I am depending on ngx-chips in my app.

**Comment by Gbuomprisco** [comment]
it's a compilation issue likely to be in older versions, so nothing you can do until it's fixed.

**Comment by Gbuomprisco** [comment]
Maybe try downgrading angular by some version

**Comment by MoAsmar** [comment]
downgrading causes new issues with packages importing
