### ISSUE TITLE
Array of numbers as value

### ISSUE THREAD

**Issue by williangd** [Gbuomprisco/ngx-chips#676]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
I am using an array of numbers as the value for the component and the array is not displayed correctly. The span/svg does not display the number, just the remove button.

**Expected behavior**
Display numbers correctly.

**Minimal reproduction of the problem with instructions (if applicable)**
Just pass a array of numbers as value.

**What do you use to build your app?. Please specify the version**
angular-cli@1.7.1 and angular-cli@1.6

**Angular version:** 
angular@5.2.6 and angular@5.1.0

**ngx-chips version:**
1.6.4

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome and Firefox

**Comment by Gbuomprisco** [comment]
Why not just map numbers to strings? :)

**Comment by Gbuomprisco** [comment]
I suppose If the doc says you need to pass strings, the issue is on the user end rather than in the control. It's really easy to fix on your side imho

**Comment by SteveAndrews** [comment]
@Gbuomprisco Just because a use case doesn't make sense to you does not make it unnecessary.

**Comment by Gbuomprisco** [comment]
If a simple change can be made in userland I don't get why we should make the control more complex.
