### ISSUE TITLE
showDropdownIfEmpty is not working for first time in case of Autocomplete with observable items

### ISSUE THREAD

**Issue by yatendrasingh93** [Gbuomprisco/ngx-chips#679]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
If I use AutoComplete having items fetched from third-party API, it is not showing the items when clicked for the first time. Property "showDropdownIfEmpty" is set to true. If I type something and erase the text, then results are shown on focus. 

**Expected behavior**
API call should be made the very first time when tag input element is in focus. It could have a separate property for this behavior. Along with this, the drop-down is only visible on focus if I click on the text "+ Tag". If it is away from this text on right, then nothing happens when focused.

**Minimal reproduction of the problem with instructions (if applicable)**

It can be reproduced on [demo page](https://angular-mfppay.stackblitz.io/)

**What do you use to build your app?. Please specify the version**
angular-cli - 1.5.3

**Angular version:** 

```
Angular CLI: 1.5.3
Node: 9.2.0
OS: linux x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.0-rc.1
@angular/cli: 1.5.3
@angular/material: 5.0.0-rc.1
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
```

**ngx-chips version:**

    "ngx-chips": "^1.6.5",

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Have you set [minimumTextLength] to 0?
