### ISSUE TITLE
minimumTextLength not work when you set it to 0 value with observable 

### ISSUE THREAD

**Issue by mhamad91** [Gbuomprisco/ngx-chips#680]

**Comment by Gbuomprisco** [comment]
Fill template please

**Comment by mhamad91** [comment]
We've the same issue posted below:
[showDropdownIfEmpty is not working for first time in case of Autocomplete with observable items #679](https://github.com/Gbuomprisco/ngx-chips/issues/679)
We can't do the first call for the observable onFocus or click, we've done a workaround by setting the minumumTextLength to 0 and strange behavior happened the dropdown-menu appear and once close it's open another dropdown-menu at the left top corner..
