### ISSUE TITLE
<tag-input> tag breaks the application

### ISSUE THREAD

**Issue by sarahysh12** [Gbuomprisco/ngx-chips#688]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I am new to Angular and I want to add a tag component to my page. Based on your documentation, I install the module with " npm install ngx-chips --save ".
Then, I imported the module and the dependencies: 
```

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { UserModule } from './user/user.module';
import { QuestionModule } from './question/question.module';
import { HttpModule } from '@angular/http';
import { TagInputModule } from 'ngx-chips';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    TagInputModule,
    BrowserAnimationsModule,
    FormsModule,
    ReactiveFormsModule,
    BrowserModule,
    AppRoutingModule,
    UserModule,
    QuestionModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Now I want to add a basic tag component into my page:
```
`import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from "@angular/forms";
import { QuestionService } from "../question.service";
import { Question} from "../question";
import {ActivatedRoute, Router} from '@angular/router';

@Component({
  selector: 'app-question-create',
  templateUrl: './question-create.component.html',
  styleUrls: ['./question-create.component.css'],
  providers: [QuestionService]

})
export class QuestionCreateComponent implements OnInit {
  items= ['A','B','C'];`
}`

```
Everything is good so far, but as soon as I added html tag to to html file the app does not work anymore, I mean other component (images, lables,...) are also disappeared from the page.
```
`<tag-input [(ngModel)]='items'></tag-input>`

```
I have no idea what is the problem and why the module does not work, I searched online but I couldn't find similar issue.

**Expected behavior**

A simple component to add and remove tags.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli 1.7.2

**Angular version:** 

Anular 5.2.0
**ngx-chips version:**

"ngx-chips": "^1.6.7"

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @sarahysh12, your code seems correct. Except you should probably remove BrowserModule and keep BrowserAnimationsModule. Can you check your console and see if there's a stacktrace for errors?

**Comment by sarahysh12** [comment]
`compiler.js:485 Uncaught Error: Template parse errors:
'tag-input' is not a known element:
1. If 'tag-input' is an Angular component, then verify that it is part of this module.
2. If 'tag-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
            <div class="col-md-8">
              <label>Tag input</label>
              [ERROR ->]<tag-input [(ngModel)]='items'></tag-input>
            </div>
          </div>
"): ng:///QuestionModule/QuestionCreateComponent.html@33:14
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24668)
    at JitCompiler._parseTemplate (compiler.js:34621)
    at JitCompiler._compileTemplate (compiler.js:34596)
    at eval (compiler.js:34497)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34497)
    at eval (compiler.js:34367)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34366)
syntaxError @ compiler.js:485
TemplateParser.parse @ compiler.js:24668
JitCompiler._parseTemplate @ compiler.js:34621
JitCompiler._compileTemplate @ compiler.js:34596
(anonymous) @ compiler.js:34497
JitCompiler._compileComponents @ compiler.js:34497
(anonymous) @ compiler.js:34367
then @ compiler.js:474
JitCompiler._compileModuleAndComponents @ compiler.js:34366
JitCompiler.compileModuleAsync @ compiler.js:34260
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:239
PlatformRef.bootstrapModule @ core.js:5567
(anonymous) @ main.ts:11
./src/main.ts @ main.bundle.js:219
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:227
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1`

**Comment by Gbuomprisco** [comment]
Try importing taginpitmodule in the question module.

**Comment by sarahysh12** [comment]
It is working. Thank you so much.
