### ISSUE TITLE
Can we use textarea instead of input text ?

### ISSUE THREAD

**Issue by thisisirfan** [Gbuomprisco/ngx-chips#690]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I want to add multiline tag

**Expected behavior**

Need textarea so that i can add multiline statment

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

 angular-cli

**Angular version:** 

Angular 5.0.0

**ngx-chips version:**

1.6.7

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All Browsers

**Comment by Gbuomprisco** [comment]
Sorry, that's not available

**Comment by EnKrypt** [comment]
Why is this issue closed? Add a `feature-request` tag and either assign someone to work on it, or will till someone from the community decides to donate their time and write a PR to address this.

**Comment by EnKrypt** [comment]
Why is this issue closed?

Add a `feature-request` label and either assign someone to work on it, or will till someone from the community decides to donate their time and write a PR to address this.

**Comment by Gbuomprisco** [comment]
Hi, this component is pretty fat as it is (my fault) and I don't intend to add additional features. With that said, everyone is free to fork and republish as they like.
