### ISSUE TITLE
Found 9 elements with non-unique id

### ISSUE THREAD

**Issue by dholakiyaankit** [Gbuomprisco/ngx-chips#691]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

```
<tag-input id="{{item.name}}"  [theme]="'bootstrap'" [secondaryPlaceholder]="'(after add press enter)'" [attr.required]="item.required" [ripple]="false" [(ngModel)]="dropdownDataSelectOptions[item.holderId]"  [theme]="'bootstrap'" [maxItems]="1"  [identifyBy]="'id'" [onlyFromAutocomplete]="false">
                        <tag-input-dropdown id="{{item.name}}" [showDropdownIfEmpty]="true"
                            [focusFirstElement]="true"
                            [displayBy]="'value'"
                            [identifyBy]="item.name"
                            [autocompleteItems]="dropdownData[item.holderId]">
                              <ng-template let-item="item" let-index="index">
                              {{ item.value }}
                          </ng-template>
                      </tag-input-dropdown>
                    </tag-input>
```

**Expected behavior**

Works as expected, everything is working. The only issue is in the browser I am getting 
`Found 9 elements with non-unique id `# error this is because I am looping through an array and adding the **tag-input**. I have tried adding name and id property but some how its not working.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Webpack

**Angular version:** 

Angular 5

**ngx-chips version:**

latest

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
Which element has a non unique ID? I see you are manually assigning it. Are you sure the problem isn't there?

**Comment by dholakiyaankit** [comment]
![1111](https://user-images.githubusercontent.com/6862074/37241792-2090418e-2485-11e8-9572-9df126dd41ec.jpg)
Check the screenshot I have uploaded.

**Comment by Gbuomprisco** [comment]
Try [inputId]="item.name" on <tag-input>

**Comment by Gbuomprisco** [comment]
Otherwise this https://github.com/Gbuomprisco/ngx-chips/pull/692 will probably fix it

**Comment by dholakiyaankit** [comment]
`[inputId]="item.name"` works
