### ISSUE TITLE
Forbid autocomplete to change position

### ISSUE THREAD

**Issue by BrsJsk** [Gbuomprisco/ngx-chips#693]
**I'm submitting a ...** 
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

```

**Current behavior**
I've got an input field near the bottom of the page. The autocomplete shows up underneath the input element, and when I move my mouse it goes over the input, so the input is not visible and does not respond to typing. This issue is probably related to #162 
Initially it's below the input.
![screenshot_2](https://user-images.githubusercontent.com/26108825/37607978-9d664f08-2b99-11e8-9d40-3bd3605be060.png)
When there is not enough space, it switches to top.
![screenshot_3](https://user-images.githubusercontent.com/26108825/37607979-9dcbec46-2b99-11e8-80b6-3dbad6853470.png)

**Expected behavior**
If we could set a position*bottom, top) and make it fixed, so for example it stays below the input field and has a scrollbar when there is a lot data for a small space.

**Angular version:** 
5.2.0

**ngx-chips version:**
1.6.2

**Browser:** 
All

**Comment by Gbuomprisco** [comment]
Check out the option [dynamicUpdate] in version 1.7.5
