### ISSUE TITLE
Chips does not appear until input is focused when module is inside a ng2-smart-table

### ISSUE THREAD

**Issue by somq** [Gbuomprisco/ngx-chips#695]
Hi, I'm facing a really weird issue where I'm trying to make ngx-chips inside a [ng2-smarttable](https://github.com/akveo/ng2-smart-table).

**I'm submitting a ...**
```
[*] bug report => search github for a similar issue or PR before submitting
[*] support request/question

```

**Current behavior**

The chips doesn't appear until the input is focused, either by a click or a tab. It happened that all the chips appeared at the same time while  manipulating the console (changing tab, can't reproduce here at work)

**Expected behavior**

The chips are supposed to appear once page load is done.

**Minimal reproduction of the problem with instructions (if applicable)**

https://stackblitz.com/edit/angular-sfjtp1

* Load the page
* Focus an input => the chip appear.

**What do you use to build your app?. Please specify the version** angular-cli

**Angular version:**  5.2.8

**ngx-chips version:** 1.6.7

**ng2-smart-table version:** 1.2.2

**Browser:** [all]

**What I tried:**

I felt like it was an issue with changes detection so I tried to manually trigger the render with both ngZone run and appRef.tick() with no success...
Apart from deep debugging both modules, I'm out of ideas...

**Comment by Gbuomprisco** [comment]
Have you tried ng zone's mark for check?

**Comment by Gbuomprisco** [comment]
It is possible the parent component is using onPush as detection method. Try using reactive forms with observables

**Comment by somq** [comment]
Hi, thanks for your answer.

It was indeed probably due to change detection strategy.
Both **this.ref.markForCheck();** and tag-input inside a **reactive form** did the trick.

Thanks again for your fast and accurate answer.

**Comment by somq** [comment]
For reference; better solution is to listen on statusChanges

```ts
this.form.statusChanges.subscribe((status) => {
  switch (status) {
    case 'VALID':
      this.currentClasses = 'form-control'
      break;

    case 'INVALID':
      this.currentClasses = 'form-control form-control-danger'
      break;

    default:
      this.currentClasses = 'form-control'
      break;
  }
});
```
