### ISSUE TITLE
How to set width of Dropdowm menu item?

### ISSUE THREAD

**Issue by paddyfink** [Gbuomprisco/ngx-chips#696]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
How do we set the width of dropdown menu item to 100% of the windows?

<img src="https://i.imgur.com/z4tMjBt.png">

**What do you use to build your app?. Please specify the version**

**Angular version:** 
5

**ngx-chips version:**
latest

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by BrsJsk** [comment]
You can play around with ng2-dropdown-menu and ng2-menu-item.

**Comment by paddyfink** [comment]
thanks

**Comment by benjii** [comment]
@paddyfink Sorry if this is obvious, but I too am having a problem setting the width of the dropdown. When you say "play around with ng2-dropdown-menu and ng2-menu-item" do you mean those are classes that you can apply a style to?

**Comment by BrsJsk** [comment]
@benjii Yup, those are the classes

**Comment by benjii** [comment]
Sorry - I should have tagged you @BrsJsk ... so something like this should work?

```
.ng2-dropdown-container {
  width: 750px !important;
}
```

**Comment by BrsJsk** [comment]
@benjii Yeah, should work. Worked for me, I was able to manipulate style of it, just took me some time to see what classes are being used.

**Comment by benjii** [comment]
@BrsJsk Thanks again! Got it working now.

For those that have stumbled across this, the basic thing I got working was this:

```
.ng2-dropdown-menu {
  width: 50% !important;
  height: 20% !important;
}
```

And in case this is relevant, in my case (and I think that this is the default?) the drop-down menu div's were appended to the body tag, not the actual controls tag.

Thanks again!

**Comment by Yulin777** [comment]
I am trying to make it's width 100% of the **chips container** instead of a constant value so I can use it properly in different places in my project. 

@benjii was right, its parent is not the `tag-input` selector so a simple style like `width: 100% !important ` doesn't work in my case.

two things that may help mentioning:
1. I used one of the themes and overrode some styles to custom it to my needs.
2. I use the component inside a modal

any help would be appreciated, thanks

**Comment by shametim** [comment]
In your root styles.css

```
.ng2-dropdown-menu {
  width : 70vh !important;
}
```
