### ISSUE TITLE
Add tag as array of strings if autocompleteItems exist &  [trimTags]="false" also

### ISSUE THREAD

**Issue by iCRG** [Gbuomprisco/ngx-chips#698]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Hi,
I have been used [modelAsStrings]="true" [trimTags]="false" in tag-input tag &[autocompleteItems]="['qwerty','mani']" in tag-input-dropdown tag. if value is adding from autocompletitems, it is storing as array of objects([{display:"qwerty",value:'qwerty'}]). if value is new , it is storing as array of string(['qwerty']).

<tag-input [(ngModel)]="listSearch.labels" name="labels-search" [clearOnBlur]="true"  [onlyFromAutocomplete]="true" [modelAsStrings]="true" (ngModelChange)="searchListRisk()"  [trimTags]="false" #labelSearch >
 <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="availableLabels" [limitItemsTo]="5" [keepOpen]="false" >
  </tag-input-dropdown>
 </tag-input>

**Expected behavior**

 both scenarios I need to add an array of strings. how to handle it?

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Angular cli 1.7.3

**Angular version:** 

5.2.0

**ngx-chips version:**

1.6.7

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browser

**Comment by Gbuomprisco** [comment]
How do you add new values if you set onlyFromAutocomplete=true?
