### ISSUE TITLE
While disable false, i am able to enter the tag. if i click the enter, it is not adding to Model array.

### ISSUE THREAD

**Issue by iCRG** [Gbuomprisco/ngx-chips#699]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

sample code
<tag-input [(ngModel)]="addproject.accountableInfo" name="accountableInfo" [modelAsStrings]="true"  (onAdd)="accountEmailValidation($event)"  [onlyFromAutocomplete]="false" #accountableInfo="ngModel" required #accountTag [maxItems]="1" [disable]="perm.access.projects.add_edit_accountable ? false : true">
                                    <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="auditorAccountList" [limitItemsTo]="accountAutoComplete.limitItemsTo">
                                    </tag-input-dropdown>
                                </tag-input>
i have typed the value, if enter it is not adding to the model. the problem is permission information it will come after the API call, By default disable is true, after getting APi values it is becaming false. How to handle this situation.

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Angular cli 1.7.3

**Angular version:** 

5.2.0 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
The explanation is a bit unclear to me, sorry. Anyway, there's a PR for the disable issue.
