### ISSUE TITLE
AOT not working with ngx-chips version 1.6.x

### ISSUE THREAD

**Issue by Drishika** [Gbuomprisco/ngx-chips#701]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
My package.json
  " angular/animations": "4.4.6",
    "angular/common": "4.4.6",
    "angular/compiler": "4.4.6",
    "angular/core": "4.4.6",
    "angular/forms": "4.4.6",
    "angular/http": "4.4.6",
    "angular/platform-browser": "4.4.6",
    "angular/platform-browser-dynamic": "4.4.6",
    "angular/router": "4.4.6",
    "ngx-chips": "1.6.3",

AOT compiler gives the following error

ERROR in ./build/aot/node_modules/ngx-chips/ngx-chips.ngfactory.ts
**Module not found: Error: Can't resolve 'ngx-chips/components/index'** in '/Users/abhinav/Projects/test/build/aot/node_modules/ngx-chips'
 @ ./build/aot/node_modules/ngx-chips/ngx-chips.ngfactory.ts 7:0-716
 @ ./build/aot/src/main/webapp/app/entities/job/job-dialog.component.ngfactory.ts
 @ ./build/aot/src/main/webapp/app/app.module.ngfactory.ts
 @ ./src/main/webapp/app/app.main-aot.ts

I tried with angular version 4.3.2,4.4.6 and all ngx-chips (1.6.0-1.6.3).

Moving to angular 5 is an expensive thing at this Time for me.

Any help appreciated.

Saw earlier you said this is fixed in 1.6.5 but that needs angular 5. Do you have a solution to share on 1.6.3 ?

**Expected behavior**

Should compile in AOT

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
Webpack 3.6.0

**Angular version:** 
was on 4.3.2 upgraded to 4.4.6 for trouble shooting this probelm

**ngx-chips version:**
started with 1.6.0,1.6.1 now 1.6.3. Changed versions to trouble shoot. problem on all versions

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, sorry but a release for Angular 4 is not available. It's already tough to support the latest versions :)

**Comment by Drishika** [comment]
Can you please let know if this could be a problem with ngx ? Am happy to help fix it but my project uplift to angular 2 at this stage is a huge problem

**Comment by Gbuomprisco** [comment]
Have you tried already 1.6.5?

**Comment by Drishika** [comment]
That would require me to move upgrade to angular 5, right ?

**Comment by Gbuomprisco** [comment]
Upgrading was a suggestion but I am not sure it was strictly necessary so you may still try installing that one

**Comment by Drishika** [comment]
I did... got this..

Error: Metadata version mismatch for module /Users/abhinav/Projects/gradzcircle/node_modules/ngx-chips/ngx-chips.d.ts, found version 4, expected 3

**Comment by Gbuomprisco** [comment]
No I usually use the latest cli

**Comment by Gbuomprisco** [comment]
have you tried reinstalling your node modules? I'd remove both angular and ngx chips and retry...

**Comment by Drishika** [comment]
Yeah I have done that. I went down the path to upgrade to Angular 5 last night but realised not a good use of time. 

Moreover am using Jhipster as a framework so makes it more difficult to upgrade.

Am now looking at the webpack, compiler options... intriguing why only /components/index is not being picked up. Have spent 4 days on this .. no light yet.. :)

**Comment by Drishika** [comment]
I have noticed onething.

In node_modules/ngx-chips/ngx-chips.ngfactory.ts

export {TagInputDropdown as TagInputDropdown_32,DeleteIconComponent as DeleteIconComponent_34,TagInputForm as TagInputForm_36,TagRipple as TagRipple_38,TagComponent as TagComponent_40,TagInputComponent as TagInputComponent_42,TagInputDropdown as TagInputDropdown_43,DeleteIconComponent as DeleteIconComponent_44,TagInputForm as TagInputForm_45,TagRipple as TagRipple_46,TagComponent as TagComponent_47,TagInputComponent as TagInputComponent_48,TagInputDropdown as TagInputDropdown_49,DeleteIconComponent as DeleteIconComponent_50,TagInputForm as TagInputForm_51,TagRipple as TagRipple_52,TagComponent as TagComponent_53,TagInputComponent as TagInputComponent_54} from 'ngx-chips/components/index';

Is the first line and causing an issue. Does this ring a bell ?

In all other lib the first line is always as import followed by export. This one has inverse. Looks like an issue with ngx - chips . What do you think ?

**Comment by Gbuomprisco** [comment]
You can try downgrading to 1.5.11. It worked for some other users

**Comment by Drishika** [comment]
I tried doing that too... then I get a scss issue

Module parse failed: /Users/abhinav/Projects/gradzcircle/node_modules/ngx-chips/dist/modules/components/icon/icon.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../../core/styles/themes/_themes.scss";
| 
| :host(delete-icon) {:
SyntaxError: Unexpected character '@' (1:0)
    at /Users/abhinav/Projects/gradzcircle/node_modules/ngc-webpack/src/webpack-resource-loader.js:52:28

Am very new to this world... any idea on how to fix this ?

**Comment by Gbuomprisco** [comment]
Sorry I am out of ideas, but the latter may be a Webpack config problem

**Comment by Drishika** [comment]
Thanks a lot for your help. I was finally able to do it. Worked with 1.5.11. Resolved webpack issues.
