### ISSUE TITLE
when you edit a tag, you are allow to change to existing tag (duplicate tag).

### ISSUE THREAD

**Issue by sonicwong** [Gbuomprisco/ngx-chips#702]
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

**Current behavior**
when you edit a tag, you are allow to change to existing tag (duplicate tag).

**Expected behavior**
duplicate should not allowed, right?

**Comment by Gbuomprisco** [comment]
this should be fixed with v 1.7.0
