### ISSUE TITLE
Bug in dropdown when validation provided

### ISSUE THREAD

**Issue by MusicalEcho** [Gbuomprisco/ngx-chips#703]
**I'm submitting a ...**  (check one with "x")
[x] bug report 

**Current behavior**
When you select item in dropdown with validation function that is in your demo, the function returns null(like expected for the value validated before upload it to server) but tag has not been added and OnAdding function doesn't fire

**Expected behavior**
Validate the value, fire OnAdd function and show the tag

**Minimal reproduction of the problem with instructions (if applicable)**
1. Set global options 
`tagInput: {
        displayBy: 'title',
        identifyBy: 'title',
        theme: 'foundation-theme',
        placeholder: '',
        secondaryPlaceholder: 'Start typing',
        addOnPaste: true,
        ripple: false,
        addOnBlur: true
    },
    dropdown: {
        displayBy: 'title',
        identifyBy: 'title'
    }`
2. Provide data:
`autocompleteTags: Array<any> = [
{
    "id": 1,
    "tag": "item1",
    "title": "item1",
    "created_by": 1,
    "created_at": "2018-03-22 17:25:02"
  },
  {
    "id": 2,
    "tag": "item2,
    "title": "item2",
    "created_by": 1,
    "created_at": "2018-03-22 17:25:02"
  },
  {
    "id": 3,
    "tag": "node",
    "title": "node",
    "created_by": 1,
    "created_at": "2018-03-22 17:52:36",
  }
]`
3. Set more options in template 
`<tag-input [ngModel]="tags"
                   [validators]="validators"
                   [errorMessages]="errorMessages"
                   (onAdd)="tagOnAdd($event)"
                   (onRemove)="onRemove($event)"
                   [ngModelOptions]="{standalone: true}">
            <tag-input-dropdown [autocompleteItems]="autocompleteTags"
                                [showDropdownIfEmpty]="true">
            </tag-input-dropdown>
        </tag-input>
`
4. Provide validation methods from your demo:
`
public validators = [this.startsWithAt, this.endsWith$];
 private startsWithAt(control: FormControl) {
        if (control.value.charAt(0) !== '@') {
            return {
                'startsWithAt@': true
            };
        }
        return null;
    }

    private endsWith$(control: FormControl) {
        if (control.value.charAt(control.value.length - 1) !== '$') {
            return {
                'endsWith$': true
            };
        }
        return null;
    }
`
5. When your dropdown shows, select some item there. Even when you added some tag already.
6. Tag won't show in added tags

**What do you use to build your app?. Please specify the version**
angular-cli 1.6.3

**Angular version:** 
Angular 5.2.9

**ngx-chips version:**
1.6.7

**Browser:** Chrome 65

**Comment by architgarg** [comment]
facing the same issue :(

**Comment by Gbuomprisco** [comment]
you're providing OnAdd, not OnAdding

**Comment by helloankit** [comment]
I want to not apply validation on dropdown values. :)
@Gbuomprisco How can I do that? 

I currently have email validation on my tag-input. But in dropdown items, I have some wildcards which will be always valid and will not be in the form of a valid email address. Please suggest if it can be implemented using some existing feature.
