### ISSUE TITLE
No adaptative tag model

### ISSUE THREAD

**Issue by cloudmelon** [Gbuomprisco/ngx-chips#704]
When I am using Tag model for to save a table with array list of object tag model such as   { display: 'display', value: 124242 } , then save this to server. 

![image](https://user-images.githubusercontent.com/4621560/37967555-111f3c1a-31cc-11e8-97c7-249068b6a3dd.png)

But it not addaptive for situation if I need only one list of tag name. So I should create my own function to format the object in array to list of string to array. 

Please provide a way to simplify the work ,  a way to use directly the array list of string so that we can save
![image](https://user-images.githubusercontent.com/4621560/37967746-96d23e70-31cc-11e8-81e8-ddfa034238c3.png)

PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Not sure I understand, but have a look at modelAsStrings

**Comment by cloudmelon** [comment]
Hello all,

I tried it. it is working. thank you very much :)

**Comment by Gbuomprisco** [comment]
:)
