### ISSUE TITLE
default placeholder is showing when chip is marked disabled

### ISSUE THREAD

**Issue by dolphinsd** [Gbuomprisco/ngx-chips#707]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

See image
https://gyazo.com/4826517d629120e646ce40affe85b440

**Expected behavior**

Tag+ should not appear

**Minimal reproduction of the problem with instructions (if applicable)**

  <tag-input name="ContextBadges" theme="bootstrap"  [disable]="true" [(ngModel)]="record.contextBadgesArray"></tag-input>

BUT this one removes Tag+ tag
<tag-input name="DataBadges" theme="bootstrap" [placeholder]="disable" [disable]="true" [(ngModel)]="record.dataBadgesArray"></tag-input>

**What do you use to build your app?. Please specify the version**

Angular 5.1.1

**Angular version:** 

Angular 5.1.1

**ngx-chips version:**

1.6.7

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, sorry, but I am not sure this is a bug.
