### ISSUE TITLE
 Possibility of the dragzone to copy the contents and paste and not to cut

### ISSUE THREAD

**Issue by renanmoraes** [Gbuomprisco/ngx-chips#720]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
Today the dragzone when you rotate to another zone it simply deletes (strips one and puts in the other)

**Expected behavior**
When it is dragged to another zone it creates a copy, that is, it has the same item in each zone. However it would be interesting if the values ​​of the inputs could be different as in the example below.

> INPUT 01
> ['aa', 'bb', 'cc']
> 
> INPUT 02
> ['bb', 'dd']

The value of bb was used by the dragzone option, but you can see that there are different values ​​in fields 01 and 02

**Comment by Gbuomprisco** [comment]
Sorry I am not able to understand what you mean. Is it a bug or a feature request?

**Comment by renanmoraes** [comment]
In fact it is a doubt. Today when I use dragzone and drag and drop an item, it simply exits from one and goes to another, the interesting thing for me would be that it would generate a copy, the same item I have here would have it there, as in the array example I gave in case of input 01 and 02

**Comment by Gbuomprisco** [comment]
Basically you would like to retain the value rather than cut the tag. I see your point, but this is more of a feature request than a bug, so I'll have to postpone once all the bugs are out of the way :)

**Comment by renanmoraes** [comment]
So that would be a new feature? Because this is really what I need, how can I get inside new implementations in this case that I asked?

**Comment by Gbuomprisco** [comment]
as written above, new features/behaviour are currently ignored as I am trying to stabilize the project and reduce the number of bugs. If you want, you can open a PR and I'll review it.
