### ISSUE TITLE
Adding empty chips and causing promise error in console after pressing enter on empty input

### ISSUE THREAD

**Issue by kassomeone** [Gbuomprisco/ngx-chips#725]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
version 1.7.7 and onwards breaking the code. when we try to enter witout typing anything empty chip is added also get promise error.

**Expected behavior**
version before 1.7.7 does have such behaviour.

**Minimal reproduction of the problem with instructions (if applicable)**

bug

**What do you use to build your app?. Please specify the version**

webpack

**Angular version:** 

Angular 5

**ngx-chips version:**

version 1.7.7

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Hi, can you please try 1.7.8?
