### ISSUE TITLE
Autocomplete - List get's not refreshed after upgrading to 1.7.4

### ISSUE THREAD

**Issue by pschalk** [Gbuomprisco/ngx-chips#729]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**
When typing in letters into the tag input field, which should filter the autocomplete list, nothing happens. If the letters could be found in the list, they get be marked bold in the list, but when I then enter a word which is not shown in the current list, the list get's not refreshed. The list just gets refreshed when clicking somewhere else an clicking back into the tag input field. So looks like some focus / refresh bug? 

<img width="288" alt="screen shot 2018-04-07 at 18 43 57" src="https://user-images.githubusercontent.com/8512329/38457874-7f66c080-3a96-11e8-83fd-14bda3354b58.png">

(There are entries which start with "glu", so they should get listed in the list instead of the old stuff)

**Expected behavior**
List just shows entries which matches the entered pattern. 

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
angular-cli (1.7.4)

**Angular version:** 
5.2.9

**ngx-chips version:**
1.7.4 (Was working with 1.7.3)
+ ng2-material-dropdown 0.9.5

**Browser:**
Newest Chrome and Firefox

**Comment by pschalk** [comment]
Sry, I forgot to mention that I've tried it already with 1.8.0

After facing the issue, I tried all versions before, that's why I know exactly that it is not longer working after 1.7.4

**Comment by MrBra1nwash** [comment]
+1

**Comment by ceeliro** [comment]
Same issue on 1.8.0

**Comment by Gbuomprisco** [comment]
@pschalk I'm not being able to reproduce for some reason: are you able to reproduce on the demo page? Can you post your code or fork the demo for reproduction?

**Comment by Gbuomprisco** [comment]
Can anyone try v 1.8.2?? Thanks!
