### ISSUE TITLE
Edit does not work on second time in ngx-chip

### ISSUE THREAD

**Issue by Debanjan123** [Gbuomprisco/ngx-chips#731]
Hi i am using editable ngx-chips.
ex:  <tag-input [editable]='true' (onTagEdited)="onTagEdited($event)" [(ngModel)]="items"></tag-input> 
version: "ngx-chips": "^1.8.0"
first time editable works but when i do it 2nd time changing value does not get update.
Even onTagEdited() does not fire

**Comment by Gbuomprisco** [comment]
Dupe, see other issues

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ngx-chips/issues/722
