### ISSUE TITLE
auto complete items are overwritten when refreshing the auto complete array

### ISSUE THREAD

**Issue by alpernakin** [Gbuomprisco/ngx-chips#737]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
`//our root app component
import {Component, VERSION} from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <tag-input [(ngModel)]="selectedTags" [onlyFromAutocomplete]="true" theme="dark">
            <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="autoCompleteTags">
            </tag-input-dropdown>
        </tag-input>
       <button (click)="reload()">Reload</button>
  `,
})
export class AppComponent {

  autoCompleteTags : Tag[];
  selectedTags: Tag[];
    
  constructor() {
    this.autoCompleteTags= [{ new Tag("item 1", "1"), new Tag("item 2", "2") }];
  }
  reload() {
      this.autoCompleteTags = [];
      this.autoCompleteTags.push(new Tag("item 3", "3"));
      this.autoCompleteTags.push(new Tag("item 4", "4"));
  }

}

export class Tag {
    constructor(display: string, value: string) {
        this.display = display;
        this.value = value;
    }

    display: string;
    value: string;
}`

it overwrites item 3 and 4 on item 1 and 2

autcomplete pops:
item 1, item 2, item  3, item  4

**Expected behavior**
it refreshes the autocomplete and show only item 3 and 4

expected pop up:
item  3, item  4

**Angular version:** 
5.2.9

**ngx-chips version:**
1.8.0

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @alpernakin, what was the issue?

**Comment by alpernakin** [comment]
Hi @Gbuomprisco , thanks for your interest.

The problem simply originated from my mistake, as I had parallel threads inserting data at the same time as it caused undesirable data insertion to autocompleteItems.

Everything works fine!
