### ISSUE TITLE
Change overflow to visible with costume theme

### ISSUE THREAD

**Issue by TheSorm** [Gbuomprisco/ngx-chips#743]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

```

**Current behavior**
I can not change the overflow to visible in a costume tag's theme.

**Expected behavior**
I try to combine the chips with color picker but because overflow is hidden the color picker is not shown probably.

**Minimal reproduction of the problem with instructions (if applicable)**
I am using the example foundation theme and just added "overflow: visible" to the "$foundation-tag-theme"

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
Angular 5

**ngx-chips version:**
newest

**Browser:** [Chromium Version 64.0.3282.140  ]

**Comment by TheSorm** [comment]
Notest that the costume theme don't work at all, i have the right _core.scss path and import the foundation-themes.scss file in the styleUrls. Have no errors, it just uses the standard design.

**Comment by Gbuomprisco** [comment]
Post an online reproduction, it's impossible to find out your issue with little details

**Comment by TheSorm** [comment]
https://plnkr.co/edit/OJFDB6bMgEU2mbBuFM8y?p=preview

Hope this is ok, newer worked with plunker before.

**Comment by Gbuomprisco** [comment]
The documentation has typos: 

Instead of :ng-deep, use ::ng-deep

**Comment by TheSorm** [comment]
nice that works for the theme :) but there is no way to change overflow to visible for the tag?

**Comment by Gbuomprisco** [comment]
You just need to add the class to the selector via ::ng-deep, you don't really have to use the theming for all properties
