### ISSUE TITLE
typeError: defaults$1 is not a constructor at new TagInputComponent (ngx-chips.js:1631)

### ISSUE THREAD

**Issue by oudekaas** [Gbuomprisco/ngx-chips#744]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

https://github.com/Gbuomprisco/ngx-chips/issues/634
typeError: defaults$1 is not a constructor at new TagInputComponent (ngx-chips.js:1631)

**Expected behavior**

When using target: es5 in the tsconfig everything works, but as per the earlier post mentioned by someone else, with es6 I am getting the above typeError. 

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

using angular-cli with webpack 

**Angular version:** 

latest version Angular 

**ngx-chips version:**

latest version

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome.

**Comment by Gbuomprisco** [comment]
I am not sure why you're targeting es6 if it needs to run in a browser

**Comment by oudekaas** [comment]
Ah I will read up about es6, some of my other dependencies don't seem to run without es6, For instance
Quill.register('module/imageresize', ImageResize)

So from your answer es6 is not fully accepted on browsers yet?

Verstuurd vanaf mijn iPhone

Op 24 apr. 2018 om 22:42 heeft Giancarlo Buomprisco <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I am not sure why you're targeting es6 if it needs to run in a browser

**Comment by oudekaas** [comment]
I think only ie11 is not supporting es6? But I can maybe use polyfills to fix that?

Verstuurd vanaf mijn iPhone

Op 24 apr. 2018 om 22:42 heeft Giancarlo Buomprisco <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I am not sure why you're targeting es6 if it needs to run in a browser

**Comment by Gbuomprisco** [comment]
There are many es6 features that are still unsupported, which is why the Cli will by default target es5.

**Comment by oudekaas** [comment]
I did some more reading, but it seems most browser support es6 and that using babel es6 can easily be transformed to es5 to make it work in ie11? A lot of programmers are already using es6, I am a beginner in terms of using javascrip/ typescript and half way the project I came across some issues that I solved by using arrow functions, I believe arrow functions are es6, but manually changing them all to return to es5 is going to be painful.
I love your tags dependency, so would prefer to use it, maybe you can add it in the future, for now I have  a less nice looking tag dependency. You obviously have a lot more experience, so the fact that you question why i am using es2015/ es6 makes me wonder if I am better off changing all arrow functions back to normal functions or just go with babel. I will try the latter first. Any tips welcome 😄

Thanks!

Verstuurd vanaf mijn iPad

Op 25 apr. 2018 om 16:39 heeft Giancarlo Buomprisco <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


There are many es6 features that are still unsupported, which is why the Cli will by default target es5.

**Comment by Gbuomprisco** [comment]
Probably I was misunderstood: you can totally use es6 in your code, but this needs to be transpiled to es5 code

**Comment by oudekaas** [comment]
Thx! Will it be hard to make ngx-chips work on es6?

kr

Frank

Verstuurd vanaf mijn iPad

Op 26 apr. 2018 om 10:10 heeft Giancarlo Buomprisco <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Probably I was misunderstood: you can totally use es6 in your code, but this needs to be transpiled to es5 code

**Comment by Gbuomprisco** [comment]
Your best bet is debug why defaults is not a constructor. Other than this, I can't stress it enough: don't target es6

**Comment by Gbuomprisco** [comment]
It's simple: you write es6 code but by targeting es5 you will bundle es5 compliant code. The target represents how the code will be transpiled during the compilation process

**Comment by oudekaas** [comment]
That is great thx for explaining!

Verstuurd vanaf mijn iPhone

Op 26 apr. 2018 om 19:52 heeft Giancarlo Buomprisco <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


It's simple: you write es6 code but by targeting es5 you will bundle es5 compliant code. The target represents how the code will be transpiled during the compilation process

**Comment by dbusacca** [comment]
As far as I know the only real use of ES6 target is in Angular Elements:
https://angular.io/guide/elements#browser-support
