### ISSUE TITLE
Some small suggestions/fixes

### ISSUE THREAD

**Issue by rosslavery** [Gbuomprisco/ngx-chips#75]
Hi! First off -- great component, much better than my attempt at a tag input.

I have noticed a few things that I thought I'd mention:
- When using an autocomplete, an option to pre-select the first item would be nice, to prevent the user from having to press down->enter, instead of just enter.
- When using an autocomplete with more than a few items, the dropdown that appears can obstruct the rest of the view, and also seems to flicker as it finds whether it should appear above or below the input
  - Maybe an option for maximum number of results to show in the dropdown
  - Maybe an option for minimum number of characters before the dropdown shows
- When using an autocomplete, the backspace behaviour is a bit buggy, most of the time it just re-displays the autocomplete dropdown on keydown, and will never select/remove an earlier tag. If you tab off of the field and shift-tab back to the field, it lets you remove a single tag with backspace before returning to the aforementioned behaviour

angular@2.0.2
ng2-tag-input@0.3.7

**Comment by Gbuomprisco** [comment]
Hi @rosslavery, thanks! 

I'll have a look! Most of these bugs belong to another library I've written, but I've actually spent little time on it so far

**Comment by kkotak** [comment]
I second these issues. On iPhone/Pixel form factor (Chrome, Safari), other issues are - auto-complete pop-up flickering up/down, obstructing the input field, hiding the X on long tags, not being able to delete with delete key, and not allowing editing of the tag in a consistent manner.
