### ISSUE TITLE
Can't compile after updating to Angular6

### ISSUE THREAD

**Issue by ChristianLJ** [Gbuomprisco/ngx-chips#752]
**I'm submitting a ...**
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**
After upgrading to Angular6b i get the following error when compiling:

```
ERROR in node_modules/ngx-chips/components/tag-input/tag-input.d.ts(10,30): error TS2307: Cannot find module '../../core/providers'.
node_modules/ngx-chips/core/index.d.ts(3,15): error TS2307: Cannot find module './helpers'.
node_modules/ngx-chips/core/index.d.ts(4,15): error TS2307: Cannot find module './pipes'.
node_modules/ngx-chips/core/index.d.ts(6,15): error TS2307: Cannot find module './providers'.
node_modules/ngx-chips/tag-input.module.d.ts(1,10): error TS2305: Module '".../node_modules/ngx-chips/core/index"' has no exported member 'Options'.
```

**Expected behavior**
Compile without errors when using Angular@6.0.0.

**Minimal reproduction of the problem with instructions (if applicable)**
Upgrade your solution to Angular6 and compile.
```
"@angular/animations": "^6.0.0",
"@angular/common": "^6.0.0",
"@angular/compiler": "^6.0.0",
"@angular/core": "^6.0.0",
"@angular/forms": "^6.0.0",
"@angular/http": "^6.0.0",
"@angular/platform-browser": "^6.0.0",
"@angular/platform-browser-dynamic": "^6.0.0",
"@angular/router": "^6.0.0",
```

**What do you use to build your app?. Please specify the version**
AngularCLI

**Angular version:** 
6.0.0

**ngx-chips version:**
1.9.0

**Browser:**
All

**Comment by wellno14** [comment]
i got the same issue

**Comment by francoberton** [comment]
Same issue

**Comment by Gbuomprisco** [comment]
Can you try v 1.9.1?

**Comment by wellno14** [comment]
thanks for the quick response.
i updated to V 1.9.1
using "ng serve" everything is working fine.
but using "ng serve --prod"
i get:
"Uncaught TypeError: r.style is not a function at Object.<anonymous> (main.b7047cfe20171f30ce0f.js:formatted:19600)"

here is a pretty print of the line in main.js where the bug is coming from:

u = o([r.Component({
                    selector: "ng2-dropdown-menu",
                    styles: [t(13)],
                    template: t(14),
                    animations: [r.trigger("fade", [r.state("visible", r.style({
                        display: "block",
                        overflow: "*"
                    })), r.state("hidden", r.style({
                        display: "none",
                        overflow: "hidden",
                        width: "0"
                    }))

thanks for the help and for making this great component, it is very useful for me!

**Comment by ChristianLJ** [comment]
Version 1.9.1 works for me, without any problems.

**Comment by DnyaneshwarShivbhakta** [comment]
@wellno14  I am getting the same error as you mentioned. Have You got any solution for this?
