### ISSUE TITLE
Angular 6 wan't compile with ngx-chips - "cannot find module" error

### ISSUE THREAD

**Issue by wellno14** [Gbuomprisco/ngx-chips#753]
**Current behavior**

in angular 6, after running "ng serve" i get the following error"
ERROR in node_modules/ngx-chips/components/tag-input/tag-input.d.ts(10,30): error TS2307: Cannot find module '../../core/providers'.
node_modules/ngx-chips/core/index.d.ts(3,15): error TS2307: Cannot find module './helpers'.
node_modules/ngx-chips/core/index.d.ts(4,15): error TS2307: Cannot find module './pipes'.
node_modules/ngx-chips/core/index.d.ts(6,15): error TS2307: Cannot find module './providers'.
node_modules/ngx-chips/tag-input.module.d.ts(1,10): error TS2305: Module '"c:/angular/modu/node_modules/ngx-chips/core/index"' has no exported member 'Options'.

**Expected behavior**
no errors

**Minimal reproduction of the problem with instructions (if applicable)**
install angular 6 add add "import { TagInputModule } from 'ngx-chips';" to a file

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
Angular CLI: 6.0.0
Node: 8.9.0
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.0.28
@angular-devkit/schematics        0.0.51
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

**ngx-chips version:**
1.9.0

**Comment by ChristianLJ** [comment]
#752

**Comment by wellno14** [comment]
duplication of #752
