### ISSUE TITLE
tag-input-dropdown is visible by default in an Angular Material's tab

### ISSUE THREAD

**Issue by fncamm** [Gbuomprisco/ngx-chips#754]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When you use **tag-input** with the autocomplete feature and place it into an Angular Material tab that isn't first in order, the **tag-input-dropdown** is visible by default. 
![image](https://user-images.githubusercontent.com/32817720/39702145-796d5fd0-520c-11e8-9765-16592392d86e.png)

**Expected behavior**

The **tag-input-dropdown** should be hidden by default.

**Minimal reproduction of the problem with instructions (if applicable)**

Example fo the bug: https://stackblitz.com/edit/angular-s3adjk

**What do you use to build your app?. Please specify the version**

angular-cli 1.7.4

**Angular version:** 

6.0.0

**ngx-chips version:**

1.8.2

**Browser:** Chrome 66 (didn't test in other browsers)

I've figured out that the actual element being visible is a direct child of **ng2-dropdown-menu** and the problem in its styles. The element should have this styles
```
    z-index: 1000;
    display: none;
    overflow: hidden;
    height: 0px;
    width: 0px;
```
But when it's placed in a tab that isn't first in order it has only this style
```
z-index: 1000;
```
it's fixed after you search for items and close the dropdown with suggestions, so it looks wrong only the first time you see it.

I've came up with an ugly fix that works for me.

```
@ViewChild("tagInputDropdown") tagInputDropdown: TagInputDropdown;

ngOnInit() {
    this.tagInputDropdown.dropdown.menu.element.nativeElement.children[0].style = `z-index: 1000;
          display: none;
          overflow: hidden;
          height: 0px;
          width: 0px`;
  }
```

**Comment by Gbuomprisco** [comment]
It's clearly an issue with the animations as the styles don't get applied correctly: But - I don't see how the problem is caused by this library - if the issue does not happen in isolation.
