### ISSUE TITLE
Building error: cannot find module

### ISSUE THREAD

**Issue by n7229** [Gbuomprisco/ngx-chips#755]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

[0m[1m[31mERROR in node_modules/ngx-chips/components/tag-input/tag-input.d.ts(10,30): error TS2307: Cannot find module '../../core/providers'.[39m[22m[0m
[0m[1m[31mnode_modules/ngx-chips/core/index.d.ts(3,15): error TS2307: Cannot find module './helpers'.[39m[22m[0m
[0m[1m[31mnode_modules/ngx-chips/core/index.d.ts(4,15): error TS2307: Cannot find module './pipes'.[39m[22m[0m
[0m[1m[31mnode_modules/ngx-chips/core/index.d.ts(6,15): error TS2307: Cannot find module './providers'.[39m[22m[0m
[0m[1m[31mnode_modules/ngx-chips/tag-input.module.d.ts(1,10): error TS2305: Module 

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

5.2.10

**ngx-chips version:**

1.9.0

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Dupe

**Comment by JLanghauser** [comment]
@Gbuomprisco this is a dupe of this right? https://github.com/Gbuomprisco/ngx-chips/issues/752

So this is not limited to angular 6 then? (I'm also having this issue with angular 5)

**Comment by Gbuomprisco** [comment]
Probably not - I'd downgrade to the previous version for now
