### ISSUE TITLE
allowDupes with onlyFromAutocomplete options do not work together

### ISSUE THREAD

**Issue by adam-nagle-customreg** [Gbuomprisco/ngx-chips#757]
**I'm submitting a ...**  
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**

allowDupes with onlyFromAutocomplete options do not work together

**Expected behavior**

Duplicates would be allowed, but only items from the autocomplete dropdown should be allowed

**Minimal reproduction of the problem with instructions (if applicable)**

Here's an example configuration but I was able to reproduce across multiple configurations

                             <tag-input 
                                    [name]="NagleIssue" 
                                    [(ngModel)]='[@yourmodel]'
                                    [modelAsStrings]="true"
                                    [allowDupes]="true"
                                    [onlyFromAutocomplete]="true">
                                    <tag-input-dropdown 
                                        [showDropdownIfEmpty]="true" 
                                        [autocompleteItems]="tickets">
                                        <ng-template let-item="item" let-index="index">
                                           <i class="fa fa-ticket"></i> {{ item.display }}
                                        </ng-template>
                                    </tag-input-dropdown>
                                </tag-input>

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

5

**ngx-chips version:**

1.5.9

**Browser:** all

**Comment by Gbuomprisco** [comment]
The ngx chips version looks old. Have you tried the latest?

**Comment by adam-nagle-customreg** [comment]
I have not, sorry.  (I am a little away from being able to upgrade my Angular version)  I understand if you need to close this because of that.
I have some more detail for you.  allowDupes seems to be completely disabling the autocomplete lookup

**Comment by Gbuomprisco** [comment]
Which Angular version are you running at the moment? I can point you to the latest for your version and see if this is solved. As far as I know it should work with Angular5
