### ISSUE TITLE
ERROR in Metadata version mismatch for module ../ngx-chips/ngx-chips.d.ts

### ISSUE THREAD

**Issue by Nilesh-TA** [Gbuomprisco/ngx-chips#761]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When i try to execute npm install or ng serve. i getting below error.

ERROR in Metadata version mismatch for module D:/..../node_modules/ngx-chips/ngx-chips.d.ts, found version 4, expected 3, resolving symbol AppModule in D:/..../src/app/app.module.ts, resolving symbol AppModule in D:/..../src/app/app.module.ts

ERROR in ./~/ngx-chips/esm5/ngx-chips.js
Module not found: Error: Can't resolve 'rxjs/operators' in 'D:\....\node_modules\ngx-chips\esm5'
~/ngx-chips/esm5/ngx-chips.js 4:0-66
/src/app/app.module.ts
/src/main.ts
ulti ./src/main.ts

**Expected behavior**

I have also tried with latest version of ngx-chips (1.9.2). But it also not working. It giving same error. Please kindly assist asap .. trying to fix the error from last two days.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

angular/cli: 1.0.4
angular/common: 4.1.3
angular/compiler: 4.1.3
angular/compiler-cli: 4.1.3
angular/core: 4.1.3
angular/forms: 4.1.3
angular/http: 4.1.3
angular/platform-browser: 4.1.3
angular/platform-browser-dynamic: 4.1.3
angular/platform-server: 4.1.3
angular/router: 4.1.3

**ngx-chips version:**

"ngx-chips": "^1.5.3",

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
Edge
Ie11

**Comment by bob44240** [comment]
Having similar prob - but ngx-chips 1.9.2 ...using ang 4.x..latest stable node, npm etc.

**Comment by Gbuomprisco** [comment]
Normally deleting node modules and reinstalling solves the issue

**Comment by Nilesh-TA** [comment]
Hi @Gbuomprisco 

I did as you suggested. delete node modules and reinstall but still it's not working

**Comment by Gbuomprisco** [comment]
You need to align Angular and ngx chips version. The latest works with Angular 6

**Comment by fjeglinski** [comment]
Which ngx-chips version does still work with Angular 4?

**Comment by shekharsumanpandey-tudip** [comment]
When I try to execute  ng build. I getting below error.
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/lt-149/Documents/ShekharProject/haines-web/web-app/src'
ERROR in Error: Metadata version mismatch for module /home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/ng2-material-dropdown/ng2-material-dropdown.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24474:34)
    at StaticSymbolResolver._createSymbolsOf (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24260:46)
    at StaticSymbolResolver.getSymbolsOf (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:14)
    at /home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler/bundles/compiler.umd.js:23023:30
    at Array.forEach (native)
    at extractProgramSymbols (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler/bundles/compiler.umd.js:23022:79)
    at AotCompiler.compileAll (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler/bundles/compiler.umd.js:22720:47)
    at CodeGenerator.codegen (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@angular/compiler-cli/src/ngtools_api.js:61:30)
    at _donePromise.Promise.resolve.then (/home/lt-149/Documents/ShekharProject/haines-web/web-app/node_modules/@ngtools/webpack/src/plugin.js:428:58)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--" "--prod" "--aot"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Haines@1.0.0 build: `npm run clean:dist && ng build "--prod" "--aot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Haines@1.0.0 build script 'npm run clean:dist && ng build "--prod" "--aot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Haines package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && ng build "--prod" "--aot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Haines
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Haines
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lt-149/Documents/ShekharProject/haines-web/web-app/npm-debug.log

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:prod" "--" "--aot"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Haines@1.0.0 build:prod: `npm run build -- --prod "--aot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Haines@1.0.0 build:prod script 'npm run build -- --prod "--aot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Haines package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build -- --prod "--aot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Haines
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Haines
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lt-149/Documents/ShekharProject/haines-web/web-app/npm-debug.log

**Comment by cyberrspiritt** [comment]
facing the same issue
