### ISSUE TITLE
Separator keys on mobile

### ISSUE THREAD

**Issue by lukashlobil** [Gbuomprisco/ngx-chips#762]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question
```

**Current behavior**
Seperator codes do not work on Android Chrome

**Expected behavior**
Provided separator key should separate the chips even on mobile.

**Minimal reproduction of the problem with instructions (if applicable)**
https://stackblitz.com/edit/angular-kmbugo

**What do you use to build your app?. Please specify the version**
Irrelevant, provided online demo

**Angular version:** 
5 and 6

**ngx-chips version:**
latest

**Browser:**
 Mobile Chrome 66.0.3359.158

Hi, separator keys do not work on mobile chrome - it is not an issue of this repo - there seems to be a bug in [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=118639) - keycodes are not being sent and appear as 209 or 0. What I am looking for is a way to have them enabled in this component.
Thanks

**Comment by lukashlobil** [comment]
I tried, didn't solve the issue. What we found interesting is some mobile phones automatically send a space with the comma. We worked around the issue like so: https://stackblitz.com/edit/angular-44tdlp

**Comment by Gbuomprisco** [comment]
Thanks for posting your solution. I'll close the ticket but I'll keep an eye open on the Chrome bug.
