### ISSUE TITLE
Override css of ngx-chips component

### ISSUE THREAD

**Issue by itsvick** [Gbuomprisco/ngx-chips#769]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I am using ngx-chips in my app. And I need to override some CSS of the drop-down menu. I used `:host .ng2-dropdown-menu {
    font-size: 1.6rem;
}`
But it didn't work at all. Please suggest how to override CSS of your component.

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Webpack

**Angular version:** 

5.0.3

**ngx-chips version:**

1.8.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Follow the tutorial on how to create teams.
