### ISSUE TITLE
addOnBlur sets focus back to chips input

### ISSUE THREAD

**Issue by michalkubat** [Gbuomprisco/ngx-chips#770]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] support request/question
```

**Current behavior**
When addOnBlur is set to true and you leave chips input by clicking to another input, focus "jumps" back to chips input.

**Minimal reproduction of the problem with instructions (if applicable)**
See example: https://stackblitz.com/edit/angular-2tdkxm-p3zjqq (write something in chips input and then click to normal input)

**build**: angular-cli - 1.6.3
**angular version**: 5.2.5
**ngx-chips version**: 1.9.2
**browser**: Chrome 66.0.3359.181

**Comment by deepgupta1991** [comment]
Facing same issue. It's not fixed.

**Comment by michalkubat** [comment]
@deepgupta1991 Yes, I couln't get it to work as well, that's why I've implemented chips input by using material design's chips. See my working example: https://stackblitz.com/edit/angular-2tdkxm-7kk2wp

**Comment by michalkubat** [comment]
@deepgupta1991 Yes. I couldn't get it to work as well, that's why I've implemented chips input by using Material's chips. See working example: https://stackblitz.com/edit/angular-2tdkxm-7kk2wp (I'm using ngx-formly as a form builder).
