### ISSUE TITLE
Remove Enter from separatorKeyCodes

### ISSUE THREAD

**Issue by TheSorm** [Gbuomprisco/ngx-chips#775]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```
I would like to ask if i can disable that the Enter key is a separator KeyCode?
Just want to have my own setted ones and not Enter.

**Comment by Gbuomprisco** [comment]
Hi, the options don't allow that, sorry.
