### ISSUE TITLE
npm start failure after npm install

### ISSUE THREAD

**Issue by oyes** [Gbuomprisco/ngx-chips#776]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
``` 
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

After cloning this repo and initial npm install
- cd demo
- npm start or ng serve
- ERROR in ./node_modules/rxjs/observable/of.js
Module not found: Error: Can't resolve 'rxjs-compat/observable/of' in 'c:\codes\ngx-chips3\node_modules\rxjs\observable'
 @ ./node_modules/rxjs/observable/of.js 6:9-45
 @ ./demo/home/home.ts
 @ ./demo/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:3010 ./demo/app.ts

**Expected behavior**

-

**Minimal reproduction of the problem with instructions (if applicable)**

 - git clone  https://github.com/Gbuomprisco/ngx-chips.git
 - npm install
- npm start 
- ERROR in ./node_modules/rxjs/observable/of.js
Module not found: Error: Can't resolve 'rxjs-compat/observable/of' in 'c:\codes\ngx-chips3\node_modules\rxjs\observable'
 @ ./node_modules/rxjs/observable/of.js 6:9-45
 @ ./demo/home/home.ts
 @ ./demo/app.ts
 @ multi (webpack)-dev-server/client?http://localhost:3010 ./demo/app.ts

**What do you use to build your app?. Please specify the version**

- Webpack

**Angular version:** 

Angular CLI: 6.0.8
Node: 8.10.0
OS: win32 x64
Angular: 6.0.0

**ngx-chips version:**

  "name": "ngx-chips",
  "version": "1.9.2",

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Just need to fix the demo, no changes needed in the package :)
