### ISSUE TITLE
Include single text among tags

### ISSUE THREAD

**Issue by giorgosde** [Gbuomprisco/ngx-chips#780]
This is not an actual issue, but is there any way to include both random text and tags in the same input, with the current API?
My goal is to be able to write a sentence in the input and tag only words starting and ending with a specific character.
Following the documentation:
```
private startsWithAt(control: FormControl) {
  if (control.value.charAt(0) !== '@') {
        return {'startsWithAt@': true };
   }
        return null;
}
private endsWithAt(control: FormControl) {
  if (control.value.charAt(control.value.length - 1) !== '@') {
        return {'endsWith$': true};
   }
      return null;
}
public validators = [this.startsWithAt, this.endsWithAt];
```

and on view:
`<tag-input [(ngModel)]='items' 
           [validators]="validators"></tag-input>`

To summarise in a case scenario, let's say I want to type: "It is such a @sunny@ day today." In this example, I want to store the whole sentence in a variable and the word sunny in the tags array.

Another approach would be to use separatorKeys. Let's say that we set a separator key "@" and the tag starts with the character "$".. So in a case scenario of "Today is $Monday", after I type "@", it will get as a tag the word "Monday"..

Thank you for taking the time, any help is welcome.

**Comment by Gbuomprisco** [comment]
Hi, unfortunately no it's not been designed with that use case

**Comment by darlontrofy** [comment]
@giorgosde where you able to figure out a way to do this? I really need this. thanks

**Comment by giorgosde** [comment]
@darlontrofy I did my implementation using pipe on view.

**Code:**
`import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'tagpipe'
})
export class TagPipe implements PipeTransform {

  transform(value: any, args?: any): any {
    if (!value) return value;

    return value.replace(/@\w+/g, function (txt) {
      return "what_ever_styling_here";
    });
  }

}
`

**Usage:**
`<span>{{inputText | tagpipe}}</span>`

I hope that helps

**Comment by darlontrofy** [comment]
@giorgosde Yes, this should really help. In the code "what_ever_styling_here", I want words starting with "@" to be made an input tag with ngx-chips and others ignored and left as free form text.  What did you have in your own case? thanks again.

**Comment by darlontrofy** [comment]
@giorgosde can you please tell me what style you used in order not to show a tag in the field. I can't figure that out and it keeps creating a tag even after I added the pipe. thanks.
