### ISSUE TITLE
this._onTouchedCallback is not a function

### ISSUE THREAD

**Issue by jollymind** [Gbuomprisco/ngx-chips#785]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I use the tag-input component inside a bootstrap modal (v 4.0.0+) and when open tag-input-dropdown
I have this error in console:

TypeError: this._onTouchedCallback is not a function
    at TagInputComponent.TagInputAccessor.onTouched (ngx-chips.js:188)
    at TagInputComponent.blur (ngx-chips.js:1107)
    at Object.eval [as handleEvent] (TagInputComponent.html:52)
    at handleEvent (core.js:13589)
    at callWithDebugContext (core.js:15098)
    at Object.debugHandleEvent [as handleEvent] (core.js:14685)
    at dispatchEvent (core.js:10004)
    at eval (core.js:12343)
    at SafeSubscriber.schedulerFn [as _next] (core.js:4354)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:243)

**Expected behavior**

I'm using ReactiveForm.
The example code inside the page works but when i move in the bootstrap modal don't work.  

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

Webpack, angular-cli,

**Angular version:** 

angular 5

**ngx-chips version:**

1.9.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
Please provide an online reproduction.

**Comment by webcat12345** [comment]
same issue here

**Comment by webcat12345** [comment]
issue resolved after setting formControlName.
