### ISSUE TITLE
How to specify Tag color based on a specific attribut.

### ISSUE THREAD

**Issue by pvalette** [Gbuomprisco/ngx-chips#791]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Hello, 
I am using the version with Objects and I would like to have different color for the tag based on the value of a specific attribute of the object.
Is it possible with the current version or need to send a PR

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

v6

**ngx-chips version:**

latest

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

Thanks in advance, 
Philippe

**Comment by Gbuomprisco** [comment]
Hi, it's not currently possible, unless you hack the tag CSS yourself.
