### ISSUE TITLE
Editable allows duplicate

### ISSUE THREAD

**Issue by nomanyaqubny** [Gbuomprisco/ngx-chips#794]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
On "editable=true' it does not check for duplicate. If I edit a value, and change it to something that already exists then I have duplicates.

**Expected behavior**
Should not allow duplicate in any case.

**Minimal reproduction of the problem with instructions (if applicable)**
Set editable-true
Insert two values
Edit one of them and change it to as the other is
Update with duplicate

**What do you use to build your app?. Please specify the version**
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

**Angular version:** 
6.0.0

**ngx-chips version:**
1.9.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by Gbuomprisco** [comment]
Hi @nomanyaqubny, sorry, but I am not able to reproduce the same behaviour using the demo
