### ISSUE TITLE
Unable to add input as tag in case of 2-way data binding

### ISSUE THREAD

**Issue by srv1009** [Gbuomprisco/ngx-chips#802]
I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
I am trying to add date to tag-input , as far as i observed date-picker support is not there in tag-inputs. So, I am using angular material datePicker to set date in a variable defined in the component which i have binded 2-way with my tag-input through the property inputText. What i want is as soon as my value gets set in the tag input, it gets added as tag. I tried using ngModel and in my component i pushed the data in modelled variable but the tags being added are empty.

**Expected behavior**
Date Should be added as tag when i am selecting the date through date picker

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
6.0.3

**ngx-chips version:**
1.9.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Add some code

**Comment by srv1009** [comment]
https://stackblitz.com/edit/angular-hzukom?file=app%2Fdatepicker-overview-example.html

Please have a look here.

**Comment by srv1009** [comment]
Could you please tell me how to trigger the event which is being triggered by seperatorkeycode property, if anyhow i can trigger that event from my tag input then i  might be able to convert it in tag.

**Comment by srv1009** [comment]
I got that issue , perhaps it was some mistake from my end only. But still, it's a request to you to add date-picker support too. Thanks !
