### ISSUE TITLE
Cannot find module '../../modules'

### ISSUE THREAD

**Issue by raghulXander** [Gbuomprisco/ngx-chips#806]
**Current behavior**
node_modules/ngx-chips/core/accessor.d.ts(2,34):

**Angular version:** 
6

**ngx-chips version:**
1.9.5

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers where this could be reproduced

**Comment by wisespace-io** [comment]
I got the same error described above.

**Comment by xyl1993** [comment]
Cannot find module '../../modules'  ng-version:6

**Comment by xyl1993** [comment]
npm install modules --save-dev   can resolve it

**Comment by Gbuomprisco** [comment]
Try v 1.9.6
