### ISSUE TITLE
Use different colors for different tags based on first letter

### ISSUE THREAD

**Issue by darlontrofy** [Gbuomprisco/ngx-chips#810]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I would like to use different colors for different tags in a field. My case is if the tag starts with @, the color of the tag should be blue and if there is none, it should be green. Is there a way to customize the color and display of the tags?

**Expected behavior**

Set the display color of the tag based on a constraint, specifically the first letter for the string

**Minimal reproduction of the problem with instructions (if applicable)**

On any demo page

**What do you use to build your app?. Please specify the version**

**Angular version:** 

5

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi, sorry, this is not supported by the component. You could play with a custom template and CSS to achieve the result, but it's hacky.

**Comment by qqilihq** [comment]
Did you come up with a solution, @darlontrofy ?
