### ISSUE TITLE
disable +tag?

### ISSUE THREAD

**Issue by donniekerr** [Gbuomprisco/ngx-chips#812]
Is there a way to not show the +tag?  my tags are added programmatically.

Thanks,
Donnie

**Comment by Gbuomprisco** [comment]
Do you mean the placeholder?

**Comment by donniekerr** [comment]
I basically only need the ability to remove, not add.  Adds are done in angular when array changes.  Not a huge deal, if it’s not possible for my rare use case. 
Thanks 
Donnie

**Comment by Gbuomprisco** [comment]
Try the option hideForm

**Comment by donniekerr** [comment]
excellent!  don't know how I missed that!  Thanks!
excellent product and easy to setup in Angular 5/6!  Not many are!
