### ISSUE TITLE
Can't bind to 'lazyLoad' since it isn't a known property of 'img' tag in ionic3?

### ISSUE THREAD

**Issue by kapilSoni101** [Gbuomprisco/ngx-chips#813]
Hello to all,
I have created a app using ionic3 with angular2 technology and it is working fine but i have implemented the lazy-loading on image.

**Current behavior**
After load the page i got error ''Can't bind to 'lazyLoad' since it isn't a known property of 'img' tag in ionic3'' and i have properly installed ng2-lazyload-image and properly imported in the app.module.ts file ?
**Expected behavior**
My expected behaviour is that the after load the page show default image for during image is not fully loaded from DB .i don't understand what's  the wrong in my code

Steps I took:

Run Npm: npm install ng2-lazyload-image --save`

Imported into my component: import { LazyLoadImageDirective } from 'ng2-lazyload-image';

In my template:

In above template userProduct.ImageCollection is array of dynamic image that is get from the Fire-store but i got above error after load page. Maybe there’s something I’m overlooking, but I can’t seem to see what it is.

**Angular version:** 
   Angular 2

1. app.module.ts file
`import { BrowserModule }                            from '@angular/platform-browser';
import { ErrorHandler, NgModule, enableProdMode }   from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { TranslateModule, TranslateLoader }         from '@ngx-translate/core';
import { LazyLoadImageModule }                      from 'ng2-lazyload-image';

@NgModule({
		declarations: [
		  MyApp,
		  ImageSlider
		],
		imports: [
				BrowserModule,
				LazyLoadImageModule,
				IonicModule.forRoot(MyApp),
				IonicStorageModule.forRoot(),
				TranslateModule.forRoot({
					loader     : {
						provide    : TranslateLoader,
						useFactory : (createTranslateLoader),
					   deps       : [HttpClient]
					}
				 })
		],
		bootstrap: [IonicApp],
		entryComponents: [
			  MyApp,
			  ImageSlider,
		],
		providers: [
			 StatusBar,
			SplashScreen,
			Clipboard,
			{provide: ErrorHandler , useClass: IonicErrorHandler},
			Network
		]
})
export class AppModule {}
enableProdMode();

export function createTranslateLoader(http: HttpClient) {
	return new TranslateHttpLoader(http, './assets/i18n/', '.json');`

2.HTML file
`<img [defaultImage]="assets/imgs/product_defaultImg.png" 
[lazyLoad]="userProduct.ImageCollection[0].url" [offset]="offset">`

**Comment by Gbuomprisco** [comment]
wrong package...

**Comment by kapilSoni101** [comment]
Sir which package we have to import to fix this error?

**Comment by Gbuomprisco** [comment]
This package is ngx-chips. Your error comes from another one

**Comment by kapilSoni101** [comment]
Sir why we need this package ngx-chips here?
