### ISSUE TITLE
Custom Template Support for Delete Icon/Box

### ISSUE THREAD

**Issue by firstor** [Gbuomprisco/ngx-chips#814]
Currently it's allowed to define custom template for `<tag-input>`. So could you also provide custom template feature for `<delete-icon>` like the following?
```html
<tag-input ...>
    <ng-template template-identifier="delete-icon">
        <i class="fas fa-times"></i>
    </ng-template>
</tag-input>
```

**Comment by Gbuomprisco** [comment]
If you create a custom template for a tag, you can define your own template for the icon too. Check out the code in the demo app in this repo.
