### ISSUE TITLE
Data missing until after second focus event

### ISSUE THREAD

**Issue by mcalhoun** [Gbuomprisco/ngx-chips#818]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

We have a case in our app where the control doesn't display the bound data until after the 2nd focus event on the form. See the gif below...

![2018-09-18_16-42-19](https://user-images.githubusercontent.com/930247/45715638-aee17380-bb62-11e8-9ca0-71f21d019f3c.gif)

As you can see, when the form is first loaded, the already entered options are not present. After clicking on two different fields, they appear.

This is how we're using the control:

```
<tag-input theme="bootstrap"
                         [(ngModel)]="input.options"
                         modelAsStrings="true"
                         addOnBlur="true"
                         editable="true"
                         placeholder="+ option">
              </tag-input>
```

**Expected behavior**

The control shows the bound data on load

**Minimal reproduction of the problem with instructions (if applicable)**

I'm not sure as this is a simple use case and we are using the control in several places in our app. One location works, but others do not.

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

Angular 6.1.7

**ngx-chips version:**

1.9.7

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chome

**Comment by Gbuomprisco** [comment]
You could try disabling the animations on that instance?

**Comment by mcalhoun** [comment]
Setting `[ripple]="false" [animationDuration]="{enter: '0ms', leave: '0ms'}"` has no effect (the issue still exists)

**Comment by Gbuomprisco** [comment]
I think the reason is it seems to be in a Bootstrap modal? Many people have had a similar issue, but I am bit lost on the cause.

**Comment by mcalhoun** [comment]
I can confirm that this only happens when within a modal and:

- input.options IS available when the component is initiated
- zone.markForCheck() DOES NOT resolve the issue
- Moving to formControl rather than ngModel DOES resolve the issue.
