### ISSUE TITLE
Item separator for mouse-out or focus lost event

### ISSUE THREAD

**Issue by bhaumikdarji** [Gbuomprisco/ngx-chips#821]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
I need to know how can we use separatorKeyCodes or separatorKey for separate item when mouse-out or focus lost? 

**Expected behavior**
separatorKeyCodes

**Minimal reproduction of the problem with instructions (if applicable)**
This is not bug but I am asking for information

**What do you use to build your app?. Please specify the version**
AngluarJS CLI

**Angular version:** 
5

**ngx-chips version:**
latest

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by Gbuomprisco** [comment]
I am not sure I understand the question, sorry.

**Comment by Gbuomprisco** [comment]
That's not currently implemented, sorry
