### ISSUE TITLE
Event onSelect is not fired twice

### ISSUE THREAD

**Issue by Boriszn** [Gbuomprisco/ngx-chips#823]
Hi 

**I'm submitting a question(or issue)**

Could you please help.
Please do not remove this issue/question really need your help. 

Related with this opened issue https://github.com/Gbuomprisco/ngx-chips/issues/181. BUT issue was fixed there (v0.8.3) I'm using v1.5.11 and this is issue still exists (fired event once) 

What I'm doing wrong ?
Or, should I reopen (or ask in) existing issue ?

**Many Thanks in advance** 

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question
```

**Current behavior**

   1. Click on [Tag]
   2. Event onSelect is fired
   3. Click somewhere else on
   4. [Tag] loses focus
   5. Click on (the same) [Tag]
   6. Event onSelect is not fired

**Expected behavior**
Click on selected twice (or whatever times) will fire onSelect 

**Version**
angular-cli

**Angular version:** 
4.1

**ngx-chips version:**
1.5.11

**Browser:** [all | Chrome XX | Firefox XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser ]

**Comment by Gbuomprisco** [comment]
Hi, I cannot reproduce the behaviour on the latest version. You'll have to upgrade.
