### ISSUE TITLE
Get onInit items with *ngFor

### ISSUE THREAD

**Issue by BoJIbFbI4** [Gbuomprisco/ngx-chips#827]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] support request/question
```

**Current behavior**
Can't get initial value from tag-input on *ngFor with [(ngModel)].

**Expected behavior**
[onInit] Output 

**Minimal reproduction of the problem with instructions (if applicable)**
For save feature i need to check if current array not equal to initial array.  All that I need, that's to know initial array of tag-input. But I have some trouble couse I use ngFor with ngModel (see code below)

```
<mat-toolbar  *ngFor="let info of ruleItem.channelsInfoList">
            <tag-input title="selected channels" class="input border-white" dnd-droppable theme='dark' [identifyBy]="'name'"
                   [(ngModel)]='info.channels' [displayBy]="'name'" [onlyFromAutocomplete]="true"             
                   (ngModelChange)="onChange($event)" (onClick)="checkDuplicates(info.channels)"
                   (onDropSuccess)="onDrag(info.channels, $event.dragData);">
          <tag-input-dropdown [autocompleteItems]="autocomplete" [displayBy]="'name'" [identifyBy]="'name'">
          </tag-input-dropdown>
        </tag-input>
    </mat-toolbar>
```

**Angular-cli version **6.2.2****
**Angular version: **6.1.7**** 
**ngx-chips version: **1.9.8****

**Browser:** [ all ]

**Comment by Gbuomprisco** [comment]
Not sure what you're trying to ask

**Comment by BoJIbFbI4** [comment]
Thanks, tried to explain better

**Comment by Gbuomprisco** [comment]
the tags will be edited cause that's the ngModel. All you can do is store a clone in your parent component.
