### ISSUE TITLE
Replace default placeholder when new placeholder text is provided.

### ISSUE THREAD

**Issue by rspandi1985** [Gbuomprisco/ngx-chips#829]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
If I change placeholder text, it will still show old placeholder 'Enter a new tag' until you add at least one item.

**Expected behavior**
It should show new placeholder on initial load and not wait for addition of one item.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**
angular-cli,

**Angular version:** 
angular 5

**ngx-chips version:**
1.9.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome

**Comment by Gbuomprisco** [comment]
You have two placeholders [placeholder] and [secondaryPlaceholder]. You can change them or remove them by providing an empty string.

**Comment by Gbuomprisco** [comment]
If I use this code, it works:

`
<tag-input [(ngModel)]="empty"
                        [placeholder]="'A different placeholder'"
                        [secondaryPlaceholder]="'A different placeholder again'">
            </tag-input>
`

Can you paste your code?

**Comment by Zabbas2006** [comment]
By any chance can we change the font of placeholder to italics?
