### ISSUE TITLE
editable - returnkey, arrow keys doesnt work

### ISSUE THREAD

**Issue by ddanninger** [Gbuomprisco/ngx-chips#830]
**I'm submitting a ...**  
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

If editable is true only normal letter keys work - return key, arrow keys will leave the editable focus. 
The returnkey will even trigger the remove event.
In version 1.9.4 everything works as it should.

**Minimal reproduction of the problem with instructions (if applicable)**

`<tag-input [editable]="true"></tag-input>`

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
6.1.9

**ngx-chips version:**
1.9.8

**Browser:** 
Chrome, Firefox

**Comment by cisasteelersfan** [comment]
stackblitz: https://stackblitz.com/edit/angular-ffih2j

**Comment by tomavic** [comment]
I can't Use `CTRL + C` or `CTRL + A` into the editable  tag. It's still an issue
