### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by ilianiv** [Gbuomprisco/ngx-chips#835]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question
```

**Current behavior**

When I try to install ngx-chips to an angular 7 project it produces a warning:

```
warning " > ngx-chips@1.9.8" has incorrect peer dependency "@angular/animations@^6.0.0".
warning " > ngx-chips@1.9.8" has incorrect peer dependency "@angular/common@^6.0.0".
warning " > ngx-chips@1.9.8" has incorrect peer dependency "@angular/core@^6.0.0".
warning " > ngx-chips@1.9.8" has incorrect peer dependency "@angular/forms@^6.0.0".
```

**Expected behavior**

To be compatible with angular 7

**Minimal reproduction of the problem with instructions (if applicable)**

Run into an angular 7 project
```
npm install ngx-chips
```

**What do you use to build your app?. Please specify the version**

`angular-cli@7.0.2`

**Angular version:** 

7.0.2

**ngx-chips version:**

1.9.8

**Comment by olegkap** [comment]
To add to this issue.
When I upgraded to Angular 7.0.2 and trying to compile application in production mode I get following error:
`ERROR in : Template parse errors:
The pipe 'highlight' could not be found ("
            <span *ngSwitchCase="false"
                  [ERROR ->][innerHTML]="item[displayBy] | highlight : tagInput.inputForm.value.value">
            </span>
")`

Thanks,
Oleg

**Comment by LukasKlement** [comment]
Did you set "enableIvy" to false in tsconfig.json? The ivy renderer is not yet ready for production use.

**Comment by moxival** [comment]
For us with Angular 7 / Typescript 3 it is totally broken:

```
zone.js:192 Uncaught TypeError: defaults$2 is not a constructor
    at new TagInputComponent (ngx-chips.js:1457)
    at createClass (core.js:23005)
    at createDirectiveInstance (core.js:22828)
    at createViewNodes (core.js:24376)
    at createEmbeddedView (core.js:24235)
    at callWithDebugContext (core.js:25738)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (core.js:25016)
    at TemplateRef_.createEmbeddedView (core.js:22333)
    at ViewContainerRef_.createEmbeddedView (core.js:22114)
    at NgIf._updateView (common.js:3891)
```

**Comment by alippai** [comment]
Added a basic PR (https://github.com/Gbuomprisco/ngx-chips/pull/831)

**Comment by olegkap** [comment]
Thanks, 
I disabled ivy compiler and it worked.

Thanks,
Oleg

**Comment by Gbuomprisco** [comment]
2.0.0-beta.0 released with A7 support
