### ISSUE TITLE
tags not working properly when using "Tags within an autocomplete component (clear on blur events)" example

### ISSUE THREAD

**Issue by leemerlas** [Gbuomprisco/ngx-chips#836]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
When I tried to emulate the example on https://github.com/Gbuomprisco/ng2-tag-input/blob/master/demo/home/home.html#L67, it does not work. There are no options to choose from.

**Expected behavior**
What I want it to do is exactly what it does in the example.

**Minimal reproduction of the problem with instructions (if applicable)**
Here's the code that I used: 

`<tag-input [ngModel]="selectedExercises"
                   [clearOnBlur]="true">
          <tag-input-dropdown [focusFirstElement]="true" [autocompleteItems]="exercises">
          </tag-input-dropdown>
      </tag-input>`

where `selectedExercises` is an empty array where I want to store the tags I select and `exercises` is an array of objects where I want to choose from.

**What do you use to build your app?. Please specify the version**
angular-cli

**Angular version:** 
6.0.2

**ngx-chips version:**
1.9.8

**Browser:** Chrome

**Comment by Gbuomprisco** [comment]
Check out the properties displayBy and identifyBy. You need to define the keys, the component doesn't know about your object.
