### ISSUE TITLE
multiple selection in dropdown

### ISSUE THREAD

**Issue by harshabada** [Gbuomprisco/ngx-chips#842]
**I'm submitting a bug

**Current behavior**
selecting a value will close the dropdown and again dropdown will reappear in a second

**Expected behavior**
selecting a value should not close the dropdown and multiple selection should be there

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Multiple selection has never been added, yours is a feature request.
