### ISSUE TITLE
Dynamic Items for TagInput and TagDropDown

### ISSUE THREAD

**Issue by KhalilKothia** [Gbuomprisco/ngx-chips#855]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```
I am creating 3 TagInput controls dynamically based on the data received from Service. I would like to assign separate items for each TagInput Items and Dropdown items dynamically. Is there anyway I could achieve above needs.

Also, It would be great if you could redirect me to the place where I could find the demo sample code.

**Current behavior**

I cannot pass <tag-input name='f.id'  [(ngModel)]='**tformFields[0].values**' [onlyFromAutocomplete]="true"  [identifyBy]="'id'" [displayBy]="'name'">

I cannot call the function which returns items, which can be bind to [ngModel]

If I pass array index dynamically, all my TagInputs controls (created dynamically) have items from last elements.

I am trying to create TagInput control dynamically based on below json object

view.component.ts

 tformFields = [
        { 
           id: 1,
           name: '1st Field',
           values : [      
              {id: '11', name: "11name"},
              {id: '12', name: "12name"}
           ] 
        },
       { 
           id: 2,
           name: '2nd Field',
           values : [
      
              {id: '21', name: "21name"},
              {id: '22', name: "22name"}
           ]
        },
        { 
            id: 0,
            name: '3nd Field',
            values : [
       
               {id: '31', name: "31name"},
               {id: '32', name: "32name"}
            ]
         }
 
      ]

code in view.component.html to create TagInput control

 ```
<div class="form-group has-feedback row" *ngFor="let f of tformFields">
                    <label for="inputFieldName{{f.name}}" class="col-md-3 text-md-right control-label col-form-label">{{f.name}}</label>
                    <div class="col-md-9" >
                        <tag-input name='{{f.id}}'  [(ngModel)]='tformFields[f.id].values' [onlyFromAutocomplete]="true"  [identifyBy]="'id'" [displayBy]="'name'">
                            <tag-input-dropdown showDropdownIfEmpty='true'   [identifyBy]="'id'" [displayBy]="'name'">
                            </tag-input-dropdown>
                        </tag-input>
                    </div>               
                </div>

```

**Expected behavior**

Expected behavior would be to allow to create control, populate selected items and drop down items dynamically.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

7.0

**ngx-chips version:**

"ngx-chips": "^2.0.0-beta.0",

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by KhalilKothia** [comment]
I guess, the pasted code in issue is not visible. Please find view.compontent.html below

 <div class="form-group has-feedback row" *ngFor="let f of tformFields">
                    <label for="inputFieldName{{f.name}}" class="col-md-3 text-md-right control-label col-form-label">{{f.name}}</label>
                    <div class="col-md-9" >
                        <tag-input name='f.id'  [(ngModel)]='tformFields[f.id].values' [onlyFromAutocomplete]="true"  [identifyBy]="'id'" [displayBy]="'name'">
                            <tag-input-dropdown showDropdownIfEmpty='true'   [identifyBy]="'id'" [displayBy]="'name'">
                            </tag-input-dropdown>
                        </tag-input>
                    </div>               
                </div>

**Comment by HDaghash** [comment]
for dynamic input tags value check this [here](https://github.com/Gbuomprisco/ngx-chips/issues/858#issuecomment-465537412) maybe it will help.
