### ISSUE TITLE
While deleting one tag, i want to delete all tags after that tag

### ISSUE THREAD

**Issue by MsumanP** [Gbuomprisco/ngx-chips#864]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I wrote this function to remove all tags after the deleting tag. But Every time its deleting 2 elements.
```
HTML File:
<tag-input [(ngModel)]="items" (onRemove)="onRemoving($event)"> </tag-input>
TS File:
 items: string[] = ["1", "2", "3", "4"];
  public onRemoving(tag: any) {
    this.items.splice(this.items.indexOf(tag), this.items.length);
  }
```
**Expected behavior**

It should delete all tags after the deleting tag.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

**Angular version:** 

**ngx-chips version:**

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hupptechnologies** [comment]
If you want to delete tags before it that you can filter tags which index is less than deleted tag and assign new filtered array to the ngModel.

If you delete all tags then simply blank the ngModel array.

**Comment by MsumanP** [comment]
> If you want to delete tags before it then you can filter tags which index is less than deleted tag and assign new filtered array to the ngModel.
> 
> If you delete all tags then simply blank the ngModel array.

**Comment by Gbuomprisco** [comment]
You should drive this from the model, as @hupptechnologies suggested
