### ISSUE TITLE
TagInputModule.withDefaults 'disable' property it's setting in other components

### ISSUE THREAD

**Issue by Hellogark** [Gbuomprisco/ngx-chips#865]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**
Implementig 

```
TagInputModule.withDefaults({
  tagInput: {
      placeholder: '',
      disable:true      
  } ,});
```
it gets disabled in other components where chips are implemented and not only in the desired component. if i set `disable:false` in other components chis are enabled in all components ignoring the `disable:ture`

**Expected behavior**
When using disable:true in one component it should be disabled in only that  component

**Minimal reproduction of the problem with instructions (if applicable)**
First component 
```
import { TagInputModule } from 'ngx-chips';
TagInputModule.withDefaults({
  tagInput: {
      placeholder: '',
      disable:true
   
  } });
```
Second component
```
import { TagInputModule } from 'ngx-chips';
TagInputModule.withDefaults({
  tagInput: {
      placeholder: 'Add a new person',
 
  } ,
  dropdown: {
    identifyBy:'_id',
      displayBy: 'name'

  }});

```

**What do you use to build your app?. Please specify the version**
```
Angular CLI: 6.0.8
Node: 10.15.1
OS: win32 x64
```

**Angular version:** 
`6.1.10`

**ngx-chips version:**
`"^1.9.8"`

**Browser:** Firefox 66.0.1

**Comment by Gbuomprisco** [comment]
Are you saying that the values set in the defaults are set for all components? 

If so, that's that that's for

**Comment by Hellogark** [comment]
So, how can I use read only in specific components? Using readonly as attribute in input tag?

**Comment by Gbuomprisco** [comment]
Either that or add disable attribute to the specific component, don't add it globally

**Comment by Hellogark** [comment]
i've tried something like this `<tag-input readonly disable class="disabled"></tag-input>`  but still the same but chips  still enabled

**Comment by Hellogark** [comment]
i have to use an if else statement like this
```
if(this._userService.user.role === 'USER_ROLE'){
        TagInputModule.withDefaults({
          tagInput: {
              placeholder: '',
              removable: false
              // add here other default values for tag-input
          }     
        });
      }else{
        TagInputModule.withDefaults({
          tagInput: {
              placeholder: 'Add user',
              removable: true
              // add here other default values for tag-input
          }  });   }
```
