### ISSUE TITLE
TagInputDropdown DEBOUNCE_TIME configurable

### ISSUE THREAD

**Issue by startswithaj** [Gbuomprisco/ngx-chips#867]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

TagInputDropdown has DEBOUNCE_TIME, is there any reason it's not configurable?

Happy to do a PR that includes a change to make it an Input if it's likely to be merged.

**Comment by Derekjohnson277** [comment]
There is a configuration for the the text change debounce time, if that's what you're looking for. In the docs it says: 

`onTextChangeDebounce - [?number]`

Number of ms for debouncing the onTextChange event (defaults to 250)

**Comment by Gbuomprisco** [comment]
That should be correct
