### ISSUE TITLE
Dynamically translate dropdown elements and tag

### ISSUE THREAD

**Issue by ALex75Z** [Gbuomprisco/ngx-chips#871]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Here is my tag-input:

<tag-input [ngModel]="targetsSelected" displayBy="value" identifyBy="id" 
      [onlyFromAutocomplete]="true"  (onAdd)="addItem(filter, $event)" 
      (onRemove)="removeItem(filter, $event)" name="tag-input-targets">
      <tag-input-dropdown [appendToBody]="false" [autocompleteItems]="targets" 
          displayBy="value" identifyBy="id" [keepOpen]="false"
          [showDropdownIfEmpty]="true"></tag-input-dropdown>
</tag-input>

targets = [{ id: 0, value: "BRAZIL" }, ...]
"value" is a key of translation.

**Expected behavior**

Is it possible to translate (dynamically) the elements of dropdown and tags ?

I tried:
[displayBy]="{{ value | translate }}"
displayBy="{{ value | translate }}"
[displayBy]="value | translate"
but does not work.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli

**Angular version:** 

5.0.0

**ngx-chips version:**

1.9.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
I'm afraid you'd have to pass down to the component the already translated value
