### ISSUE TITLE
Incompatibility issue with ES6 fix breaks the build

### ISSUE THREAD

**Issue by wozniakm** [Gbuomprisco/ngx-chips#874]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When I try to build the project from master branch, the build fails and there are bunch of similar errors: `modules/components/dropdown/tag-input-dropdown.component.ts(46,38): error TS2348: Value of type 'Type<TagInputDropdownOptions>' is not callable. Did you mean to include 'new'?`. That's caused by [last commit](https://github.com/Gbuomprisco/ngx-chips/commit/fffce3d249abbe78e100a971d8592bdba2a173ba).

**Expected behavior**

The package should build successfully.

**Minimal reproduction of the problem with instructions (if applicable)**

1) Pull the repository and checkout master branch,
2) Run `npm install`,
3) Run `npm run build`

**What do you use to build your app?. Please specify the version**

The same as in master branch.

**Angular version:** 

The same as in master branch.

**ngx-chips version:**

Master branch.

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Not related.

**Comment by Gbuomprisco** [comment]
Should be fixed with latest release?
