### ISSUE TITLE
Update to work with Angular 8

### ISSUE THREAD

**Issue by craig-dae** [Gbuomprisco/ngx-chips#875]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

**Current behavior**
Appears to bug out on Angular 8 with: `ERROR TypeError: defaults$2 is not a constructor`



**Expected behavior**
Updated to work with Angular 8



**Minimal reproduction of the problem with instructions (if applicable)**
Update to Angular 8


**What do you use to build your app?. Please specify the version**
angular-cli


**Angular version:** 
8


**ngx-chips version:**
2.0.0-beta.0

**Browser:** Chrome

**Comment by wozniakm** [comment]
It should work with the latest version (from master), but there is another bug that makes not possible to build the code.

**Comment by Marcelh1983** [comment]
Today I did a attempt to support Angular8. I upgraded all packages.
Everything seems to work fine but still have some work to do before I can do a pull request hopefully I have some time tomorrow and if someone wants to help, feel free :): 

- 2 test randomly fail
- coverage script should be checked/replaced
- check warning circular reference
- docs

https://github.com/Marcelh1983/ngx-chips

**Comment by milons** [comment]
@Gbuomprisco @Marcelh1983 - can we help you somehow to fix this issue?

**Comment by Gbuomprisco** [comment]
Hi @milons, @Marcelh1983 the PR is good except the CI file was deleted and therefore the PR cannot be merged yet, I'm waiting for an update and will then will merge

**Comment by milons** [comment]
@Gbuomprisco are you able to give us a (pre)release date?

**Comment by Gbuomprisco** [comment]
If the file is back in today I will be able to publish it right away

**Comment by Gbuomprisco** [comment]
version 2.0.1 has been released! Thanks to @Marcelh1983

**Comment by alignsoft** [comment]
The 2.0.1 has exacerbated another issue here: #877 

Typeahead dropdowns worked in Chrome and Firefox with the 2.0.0.beta-0, but Safari did not. None work with 2.0.1.

**Comment by Gbuomprisco** [comment]
2.0.2 has been released, but Safari still not working

**Comment by dalu** [comment]
```
                  Package "ngx-chips" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0" (extended), would install "8.0.3").
                  Package "ngx-chips" has an incompatible peer dependency to "@angular/forms" (requires "^6.0.0" (extended), would install "8.0.3").
                  Package "ngx-chips" has an incompatible peer dependency to "@angular/animations" (requires "^6.0.0" (extended), would install "8.0.3").
                  Package "ngx-chips" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0" (extended), would install "8.0.3").

```
