### ISSUE TITLE
Basic autocomplete does not add items to the tag list

### ISSUE THREAD

**Issue by tigrenok00** [Gbuomprisco/ngx-chips#879]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

Clicking on item in the autocomplete dropdown does not add it to the tag list.

**Expected behavior**

The selected item would be added.

**Minimal reproduction of the problem with instructions (if applicable)**

html:

`<tag-input [(ngModel)]="selectedLoc" [onlyFromAutocomplete]="true" (onAdd)="onItemAdded($event)">
  <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="locList"  [displayBy]="'display'"
  [identifyBy]="'value'">
  </tag-input-dropdown>
</tag-input>`

ts:

`  locList = [{ value: '7010', display: "7010" }, { value: '7011', display: "7011" }, { value: '7012', display: "7012" },];
  selectedLoc = [];`

The items are displayed in the dropdown correctly, however, when clicked, the dropdown closes without adding the item. The onItemAdded event does not fire.
If I set inital items in the selectedLoc array they show in the tags correctly. But no new items being added through autocomplete.

**What do you use to build your app?. Please specify the version**

"@angular/cli": "~7.3.4",

**Angular version:** 

7.2.0

**ngx-chips version:**

2.0.1

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Tried with Chrome

**Comment by tigrenok00** [comment]
@Gbuomprisco Thanks, when will this version be available?

**Comment by Gbuomprisco** [comment]
Version 2.0.2 just published :)
