### ISSUE TITLE
Dropdown selection loses focus on first keyboard keydown.

### ISSUE THREAD

**Issue by yagizozturk** [Gbuomprisco/ngx-chips#887]
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

After autocomplete menu is shown, first element loses highlight after first keydown pressed.

**Expected behavior**

It should hold the highlight

**Minimal reproduction of the problem with instructions (if applicable)**

type something. Open Autocomplete, select first item with keyboard keydown. İt gets highlighted and quickly loses highlight. On a second attempt it works. 

**What do you use to build your app?. Please specify the version**

Webpack

**Angular version:** 

8

**ngx-chips version:**

last

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by andn99** [comment]
I got the same issue.

**Comment by vsarunov** [comment]
What is your setup for it?

**Comment by yagizozturk** [comment]
I am on macbook pro. 2.6Ghz. 16 GB Ram. 64 Bit 70.0.3538.110 chrome

**Comment by akirpichnikov** [comment]
@Gbuomprisco is there any chance that this PR will be merged?
