### ISSUE TITLE
Build failure with latest Angular

### ISSUE THREAD

**Issue by mgechev** [Gbuomprisco/ngx-chips#901]
Because of the type definitions in `ng2-menu-item.d.ts` and the removal of the deprecated `Renderer`, `ngx-chips` no longer works with the latest `@angular/core`.

You can find the failure in the CI [here](https://circleci.com/gh/mgechev/ngcc-validation/101).

In the official version 9 release, we'll no longer have `Renderer` part of Angular.

**Comment by Gbuomprisco** [comment]
Hi @mgechev, released v2.1.0, should fix that (hopefully) :)
