### ISSUE TITLE
Angular Universal Issues with Angular v8 & 9

### ISSUE THREAD

**Issue by omardoma** [Gbuomprisco/ngx-chips#938]
https://github.com/Gbuomprisco/ngx-chips/blob/d98c05f4ad6a06e2fef7dd15ba4d0945081b40c8/modules/components/tag-input/tag-input.ts#L47

This line causes SSR to fail, it should be `typeof window !== 'undefined' && (window as any).DragEvent`

**Comment by Gbuomprisco** [comment]
This should be done. Please use the template next time, it's there for a reason
