### ISSUE TITLE
not compatible with Angular 9

### ISSUE THREAD

**Issue by Ranaman196** [Gbuomprisco/ngx-chips#939]
i am upgrading angular version from 5.2 to 9 and having issue
Package "ngx-chips" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would
install "6.1.10").
Package "ngx-chips" has an incompatible peer dependency to "@angular/animations" (requires "^8.0.0" (extended), would install "6.1.10").uld install "6.1.10"). stall "6.1.10").
Package "ngx-chips" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would innstall "6.1.10").stall "6.1.10").
@Gbuomprisco please help me out
anybody help please

**Comment by stnor** [comment]
It works fine with Angular 9 but we could benefit from a dep bump to Angular 9 to avoid the warning.

**Comment by ralftar** [comment]
Also the dependency` ng2-material-dropdown` yelds lack of angular 9 support. https://github.com/Gbuomprisco/ng2-material-dropdown/issues/73
