### ISSUE TITLE
Input from textbox above the list tags

### ISSUE THREAD

**Issue by StevRoger** [Gbuomprisco/ngx-chips#948]
[ ] bug report => search GitHub for a similar issue or PR before submitting
[x] support request/question

**Current behavior**
There's no other option to add a separate input or I'm so new to this package.

**Expected behavior**
I just need a textbox input and the list tags will be stay below the input. After we input and hit enter text will add as a new tag.

**Minimal reproduction of the problem with instructions (if applicable)**
Feature request.

**What do you use to build your app?. Please specify the version**
Angular CLI

**Angular version:** 
Angular version 7 with typescript 3.x.x

**ngx-chips version:**
Ngx-chips lastest version.

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by Gbuomprisco** [comment]
Hi, what you can see in the demo page is all it is possible with the package, sorry!
