### ISSUE TITLE
Bump peerDependency of Angular to ^10

### ISSUE THREAD

**Issue by bjornharvold** [Gbuomprisco/ngx-chips#950]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

When running an ng update @angular/core it fails because ngx-chips has outdated peer dependencies. To bypass this, a developer would have to --force the update. Shouldn't be necessary.

`ngx-chips" has an incompatible peer dependency to "@angular/animations" (requires "^8.0.0" (extended), would install "10.0.0")`

**Expected behavior**

ngx-chips project should always use the latest peerDependency of Angular that it supports. ng update should work without having to --force the update.

**Minimal reproduction of the problem with instructions (if applicable)**
`ng update @angular/core @angular/cli`

**What do you use to build your app?. Please specify the version**
Angular CLI

**Angular version:** 
Angular 10

**ngx-chips version:**
Yes

**Comment by elvispdosreis** [comment]
is an excellent component, awaiting support at Angular10

**Comment by akamal88** [comment]
yes, i wish they support angular 10

**Comment by armved** [comment]
Guys, is there any progress with adding support of Angular 10?
This stops lot of projects from upgrading Angular version

**Comment by akamal88** [comment]
I create PR to fix this, but the owner of the project didn't reply, so, i created a clone that has this fix 
npm install ngx-chips-angular

**Comment by akamal88** [comment]
Thanks @Gbuomprisco for merging the PR, the new version is alive in npm package

**Comment by Gbuomprisco** [comment]
Thank you for the PR :) @akamal88
