### ISSUE TITLE
Publish the latest version of library on NPM

### ISSUE THREAD

**Issue by eneajaho** [Gbuomprisco/ngx-chips#971]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

The current version that is on NPM is from 1 year ago.  Yesterday a pull request was merged and bumped Angular version to 9.

**Expected behavior**

Update the npm package with the latest version that is on master branch.

**Comment by eneajaho** [comment]
@Gbuomprisco

**Comment by Gbuomprisco** [comment]
Released :)
