### ISSUE TITLE
Bind removable and edit data loaded from database 

### ISSUE THREAD

**Issue by truongtokiet** [Gbuomprisco/ngx-chips#996]
1. itemsAsObjects = [{id: 0, name: 'Angular', readonly: true}, {id: 1, name: 'React'}];
Can we use the same way to bind "removable"?
Because I want to build "non-removable" for data loaded from database and "removable" for new tags added.

2. Can we edit data loaded from database ? 
I tried to modify tag name but I can't and it is just editable for new tags added.

**Comment by Gbuomprisco** [comment]
Please complete the template. If possible, add a reproduction
